// True local PostgreSQL sessions and server barrier; no hosted project or credentials.
import assert from 'node:assert/strict';import{execFile,execFileSync}from'node:child_process';import{promisify}from'node:util';import{mkdtempSync,mkdirSync,readFileSync,rmSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';import{randomUUID as uid}from'node:crypto';import{migrationOrder}from'./migration-order.mjs';import{f,h,fixtureSQL,activationFixtureSQL}from'./activation-fixture.mjs';
const run=promisify(execFile),bin=process.env.TEST_POSTGRES_BIN||'/opt/homebrew/opt/postgresql@17/bin',exe=x=>join(bin,x),root=mkdtempSync(join(tmpdir(),'comm-h1-pg-')),data=join(root,'data'),socket=join(root,'socket');mkdirSync(socket);const port='55502',args=['-X','-q','-A','-t','-v','ON_ERROR_STOP=1','-h',socket,'-p',port,'-U','postgres','postgres'],sql=s=>execFileSync(exe('psql'),args,{input:s,encoding:'utf8',maxBuffer:5e6}).trim(),lit=s=>"'"+String(s).replaceAll("'","''")+"'";let started=false;
function overlap(rows){const events=rows.flatMap(r=>[[Number(r.start),1],[Number(r.end),-1]]).sort((a,b)=>a[0]-b[0]||a[1]-b[1]);let active=0,max=0;for(const [,delta]of events){active+=delta;max=Math.max(active,max)}return max;}
try{execFileSync(exe('initdb'),['-D',data,'--auth=trust','-U','postgres','--locale=C','--encoding=UTF8'],{stdio:'inherit',env:{...process.env,LC_ALL:'C',LANG:'C'}});execFileSync(exe('pg_ctl'),['-D',data,'-l',join(root,'pg.log'),'-o',`-k ${socket} -p ${port} -c listen_addresses=''`,'-w','start'],{stdio:'ignore'});started=true;
 sql(readFileSync(new URL('fixtures/supabase-test-bootstrap.sql',import.meta.url),'utf8'));sql(readFileSync(new URL('../../supabase/bootstrap/automatic-rls.sql',import.meta.url),'utf8'));for(const file of migrationOrder)sql(readFileSync(new URL('../../supabase/migrations/'+file,import.meta.url),'utf8'));sql(fixtureSQL+activationFixtureSQL);
 sql(`create table public.phaseg_barrier(run uuid,worker int,pid int,primary key(run,worker));create policy barrier_local on public.phaseg_barrier for all to authenticated,service_role using(true)with check(true);grant select,insert on phaseg_barrier to authenticated,service_role;
 create function public.phaseg_race(run uuid,n int,worker boolean,action text,p jsonb)returns jsonb language plpgsql security invoker as $$declare began numeric;answer jsonb;deadline timestamptz:=clock_timestamp()+interval '20 seconds';begin while(select count(*)from phaseg_barrier b where b.run=phaseg_race.run)<n loop if clock_timestamp()>deadline then raise exception 'Barrier timeout';end if;perform pg_sleep(.01);end loop;began:=extract(epoch from clock_timestamp());if worker then answer:=communications_provider_service(action,'${f.org}',p);else if action='consent'then answer:=communications_workspace(action,null,p||'{"organization_id":"${f.org}"}');else answer:=communications_provider_workspace(action,'${f.org}',p);end if;end if;return jsonb_build_object('pid',pg_backend_pid(),'start',began,'end',extract(epoch from clock_timestamp()),'answer',answer);end$$;grant execute on function phaseg_race(uuid,int,boolean,text,jsonb)to authenticated,service_role;`);
 const coordinator=execFile(exe('psql'),args,{maxBuffer:2e6}),pending=[];let buffer='';coordinator.stdout.on('data',s=>{buffer+=s;let i;while((i=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,i).trim();buffer=buffer.slice(i+1);if(line&&pending.length)pending.shift()(line)}});const ask=s=>new Promise(resolve=>{pending.push(resolve);coordinator.stdin.write(s+'\n')});const coord=Number(await ask('select pg_backend_pid();'));
 async function race(label,items){const key=uid(),n=items.length;await ask(`begin;select pg_advisory_xact_lock(hashtextextended('communications:external-control',0));select pg_advisory_xact_lock(hashtextextended('communications:${f.org}',0));select 'locked';`);const jobs=items.map(([worker,action,p],i)=>run(exe('psql'),args.concat(['-c',`set request.jwt.claim.sub='${worker?'':f.user}';set role ${worker?'service_role':'authenticated'};insert into phaseg_barrier values('${key}',${i},pg_backend_pid());`,'-c',`select phaseg_race('${key}',${n},${worker},${lit(action)},${lit(JSON.stringify(p))});`]),{maxBuffer:1e6}).then(r=>JSON.parse(r.stdout.trim())));
 const until=Date.now()+20000;let active=0;while(Date.now()<until){active=Number(await ask(`select pg_stat_clear_snapshot();select count(*) from pg_stat_activity where pid<>pg_backend_pid() and query like '%${key}%' and state='active' and wait_event_type='Lock';`));if(active===n)break;await new Promise(r=>setTimeout(r,30));}const ready=Number(await ask(`select count(*) from phaseg_barrier where run='${key}';`));await ask("commit;select 'released';");const rows=await Promise.all(jobs);assert.equal(active,n);assert.equal(ready,n);assert.equal(new Set(rows.map(r=>r.pid)).size,n);assert(rows.every(r=>r.pid!==coord));assert.equal(overlap(rows),n);console.log('PASS '+label+' '+JSON.stringify({workers:n,distinct_backends:n,coordinator_separate:true,server_barrier_ready:ready,peak_active_queries:active,max_overlapping_intervals:overlap(rows)}));return rows;}
 const repeat=(worker,a,p)=>Array.from({length:8},()=>[worker,a,p]);
 const staff=(a,p)=>JSON.parse(sql(`set request.jwt.claim.sub='${f.user}';set role authenticated;select communications_provider_workspace(${lit(a)},'${f.org}',${lit(JSON.stringify(p))});`));
 const worker=(a,p={})=>JSON.parse(sql(`set role service_role;select communications_provider_service(${lit(a)},'${f.org}',${lit(JSON.stringify(p))});`));
 try{
 const verification=staff('verify_request',{id:h.profile});worker('verify_result',{id:h.profile,revision:verification.revision,actor:f.user,environment:'acceptance',project_ref:h.ref,configured:true,verified:true});
 staff('enable',{id:h.profile,mode:'test_only'});staff('org_delivery',{enabled:true,email_enabled:true,sms_enabled:false});staff('global_delivery',{enabled:true});
 const preview=()=>staff('test_preview',{id:h.profile,person_id:f.person});
 const confirmArgs=(key=uid())=>{const p=preview();return{id:h.profile,person_id:f.person,request_key:key,confirmed:true,preview_subject:p.subject,preview_body:p.body,preview_recipient:p.recipient};};
 const argsA=confirmArgs(),a=await race('A duplicate single test',repeat(false,'test_confirm',argsA));
 assert.equal(Number(sql(`select count(*)from communication_provider_tests where request_key='${argsA.request_key}'`)),1);assert.equal(new Set(a.map(r=>r.answer.message_id)).size,1);const message=a[0].answer.message_id;
 const b=await race('B provider-disable vs claim',[[false,'disable',{id:h.profile}],...repeat(true,'claim_external',{message_id:message}).slice(0,7)]);
 for(const r of b)for(const j of r.answer.messages||[])assert.equal(worker('authorize_external',{message_id:j.id,lease_token:j.lease_token}).authorized,false);
 assert.equal(Number(sql(`select count(*)from communication_outbox where id='${message}'and dispatch_authorized_at is not null`)),0);
 staff('enable',{id:h.profile,mode:'test_only'});
 const revoke={audience:{kind:'person',person_id:f.person},recipient_key:'person:'+f.person,channel:'email',purpose:'transactional',status:'revoked',source:'Synthetic revoke',proof_reference:'synthetic-revoke',explicitly_reviewed:true};
 const c=await race('C consent-revoke vs claim',[[false,'consent',revoke],...repeat(true,'claim_external',{message_id:message}).slice(0,7)]);
 for(const r of c)for(const j of r.answer.messages||[])assert.equal(worker('authorize_external',{message_id:j.id,lease_token:j.lease_token}).authorized,false);
 assert.equal(Number(sql(`select count(*)from communication_outbox where id='${message}'and dispatch_authorized_at is not null`)),0);
 staff('disable',{id:h.profile});const before=Number(sql(`select count(*)from communication_audit where kind='provider.enable'`));await race('D simultaneous enable',repeat(false,'enable',{id:h.profile,mode:'test_only'}));assert.equal(Number(sql(`select count(*)from communication_audit where kind='provider.enable'`)),before+1);
 sql(`update communication_consents set status='granted'where purpose='transactional';update communication_outbox set status='cancelled',lease_token=null where status in ('sending','queued','scheduled');`);
 let test=staff('test_confirm',confirmArgs());let job=worker('claim_external',{message_id:test.message_id}).messages[0];worker('authorize_external',{message_id:job.id,lease_token:job.lease_token});worker('result_external',{message_id:job.id,lease_token:job.lease_token,outcome:'sent',provider_message_id:'synthetic-race-ref'});
 sql(`update communication_provider_controls set structured_callbacks=true where profile_id='${h.profile}';`);const attempt=sql(`select id from communication_attempts where message_id='${job.id}'and outcome='sent'`);
 const cb={id:h.profile,event_id:'synthetic-delivered',provider:'smtp_transport',provider_message_id:'synthetic-race-ref',outcome:'delivered',attempt_id:attempt};await race('E duplicate verified callback',repeat(true,'callback_external',cb));assert.equal(Number(sql(`select count(*)from communication_audit where subject_id='${job.id}'and kind='delivery.delivered'`)),1);
 test=staff('test_confirm',confirmArgs());job=worker('claim_external',{message_id:test.message_id}).messages[0];sql(`update communication_outbox set lease_until=now()-interval '1 minute'where id='${job.id}';`);
 const lease=await race('F stale pre-handoff lease recovery',repeat(true,'claim_external',{message_id:job.id}));const owners=lease.flatMap(r=>r.answer.messages||[]);assert.equal(owners.length,1);assert.notEqual(owners[0].lease_token,job.lease_token);assert.throws(()=>worker('authorize_external',{message_id:job.id,lease_token:job.lease_token}));assert.equal(worker('authorize_external',{message_id:owners[0].id,lease_token:owners[0].lease_token}).authorized,true);
 worker('result_external',{message_id:owners[0].id,lease_token:owners[0].lease_token,outcome:'sent',provider_message_id:'synthetic-recovered'});assert.equal(Number(sql(`select count(*)from communication_attempts where message_id='${job.id}'and outcome='sent'`)),1);
 console.log('PASS six H1 native PostgreSQL races; 8 independent overlapping worker sessions each; fake receipts only');
 }finally{coordinator.stdin.end();await new Promise(r=>coordinator.once('exit',r));}
}finally{if(started)execFileSync(exe('pg_ctl'),['-D',data,'-m','fast','-w','stop'],{stdio:'ignore'});rmSync(root,{recursive:true,force:true});}
