import assert from'node:assert/strict';import nodemailer from'nodemailer';import{webcrypto,createHmac}from'node:crypto';import{smtpAdapter,smtpFailure,smsAdapter,bindingFor,runExternalWorker,boundedBody,verifiedProviderEvent}from'../../supabase/functions/_shared/communications/activation.mjs';globalThis.crypto??=webcrypto;let n=0;const ok=(v,m)=>{assert.ok(v,m);n++;console.log('PASS '+m)},deny=async(fn,m)=>{await assert.rejects(fn);ok(true,m)};
const profile={id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1',organization_id:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb1',provider:'smtp_transport',from_address:'sender@example.test',reply_to:'reply@example.test',display_name:'Synthetic'},rt={environment:'acceptance',project_ref:'bkbmjisprwmkptywtmih'},binding={...rt,profile_id:profile.id,organization_id:profile.organization_id,provider:profile.provider,from:profile.from_address,reply_to:profile.reply_to,sender_approved:true,host:'smtp.example.test',port:587,username:'sender@example.test',password:'synthetic only'};
let options,envelope,verifies=0,sends=0;const fake={createTransport:o=>{options=o;return{verify:async()=>{verifies++;},sendMail:async e=>{envelope=e;sends++;return{messageId:e.messageId,accepted:[e.to],rejected:[]};},close(){}};}};
const job={id:'synthetic',organization_id:profile.organization_id,idempotency_key:'stable',channel:'email',address_snapshot:'recipient@example.test',subject:'Synthetic test',rendered_body:'Hello <script>unsafe</script>\nWorld',sender:profile};
ok(bindingFor({[profile.id]:binding},profile,rt)===binding,'environment tenant profile From binding');for(const b of[{...binding,project_ref:'other'},{...binding,organization_id:'other'},{...binding,from:'spoof@example.test'},{...binding,reply_to:'other@example.test'},{...binding,sender_approved:false}])await deny(async()=>bindingFor({[profile.id]:b},profile,rt),'wrong or unapproved binding denied');
const smtp=smtpAdapter(fake,binding);await smtp.verify();ok(verifies===1&&sends===0,'connectivity verifies without sending');ok(options.requireTLS&&options.tls.rejectUnauthorized&&options.tls.minVersion==='TLSv1.2'&&options.auth.pass===binding.password&&!options.logger&&!options.debug&&options.socketTimeout===15000,'required validated TLS bounded timeouts credential value no logs');let receipt=await smtp.send(job);ok(receipt.status==='sent'&&envelope.messageId.includes('@example.test')&&envelope.envelope.to.length===1,'single SMTP accepted normalized receipt');ok(envelope.text===job.rendered_body&&envelope.html.includes('&lt;script&gt;')&&!envelope.html.includes('<script>'),'plain fallback safe escaped HTML');ok(envelope.from.address===binding.from&&envelope.replyTo===binding.reply_to,'approved From and Reply-to');const id=envelope.messageId;await smtp.send(job);ok(envelope.messageId===id,'stable RFC Message-ID not a false exactly-once SMTP promise');for(const variant of[{subject:'Hello\r\nBcc:evil@example.test'},{address_snapshot:'a@example.test,b@example.test'},{sender:{...profile,from_address:'spoof@example.test'}},{sender:{...profile,display_name:'bad\nname'}}])await deny(()=>smtp.send({...job,...variant}),'unsafe header/envelope denied');
ok(smtpFailure({responseCode:451})==='transient'&&smtpFailure({responseCode:550})==='permanent'&&smtpFailure({code:'ETIMEDOUT'})==='uncertain'&&smtpFailure({code:'EAUTH'})==='permanent','SMTP known reject retries ambiguity reconciles');await deny(async()=>smtpAdapter(fake,{...binding,port:25}),'unsupported insecure SMTP port denied');await deny(async()=>smsAdapter(null,{}),'SMS selection missing not fake pass');let smsBody;const sms=smsAdapter({verify:async()=>({verified:true}),verifyCallback:async()=>({}),send:async p=>{smsBody=p;return{id:'sms-ref',status:'accepted',segments:2,cost:'0.02'};}},{sender_service_id:'synthetic-service'});const sm=await sms.send({...job,channel:'sms',address_snapshot:'+15550000001',rendered_body:'A\r\n'+ 'b'.repeat(250)});ok(sm.segments===2&&sm.cost==='0.02'&&smsBody.text.length===252&&!smsBody.text.includes('\r'),'SMS normalization optional metadata no silent truncation');
let sent=0,actions=[];const rpc=async(a,o,p)=>{actions.push(a);return a==='claim_external'?{...rt,mode:'external_tests',messages:[{...job,lease_token:'lease'}]}:a==='authorize_external'?{authorized:false}:{}};const resolver=async()=>({send:async()=>{sent++;return{id:'receipt',status:'sent'};}});await runExternalWorker(rpc,profile.organization_id,resolver);ok(actions.length===0&&sent===0,'runtime disabled no database/provider contact');await runExternalWorker(rpc,profile.organization_id,resolver,{enabled:true,runtime:rt});ok(sent===0&&!actions.includes('result_external'),'last handoff consent/disable rejection no send');actions=[];let ackFails=false;const live=async(a,o,p)=>{actions.push(a);if(a==='claim_external')return{...rt,mode:'external_tests',messages:[{...job,lease_token:'lease'}]};if(a==='authorize_external')return{authorized:true};if(a==='result_external'&&ackFails)throw Error('DB unavailable');return{};};await runExternalWorker(live,profile.organization_id,resolver,{enabled:true,runtime:rt});ok(sent===1&&actions.join(',')==='claim_external,authorize_external,result_external','canonical worker lifecycle no automated consumption');ackFails=true;await deny(()=>runExternalWorker(live,profile.organization_id,resolver,{enabled:true,runtime:rt}),'ack failure propagated without retrying transport');ok(sent===2,'exactly one transport call per handed-off lease');await deny(()=>runExternalWorker(rpc,profile.organization_id,resolver,{enabled:true,runtime:{environment:'production',project_ref:'different'}}),'cross environment worker guard');
const cp={structured_callbacks:true,sender:{provider:'sms_transport',channel:'sms'}},secret='synthetic-signature-key'.repeat(2),stamp=Math.floor(Date.now()/1000).toString();const payload={event_id:'synthetic-event',provider:'sms_transport',type:'delivery',status:'delivered',provider_message_id:'synthetic-ref',attempt_id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1'},raw=JSON.stringify(payload);const headers=new Headers({'x-provider-time':stamp,'x-provider-signature':createHmac('sha256',secret).update(stamp+'.'+raw).digest('hex')});
const verifier=async(raw,h,b)=>{const t=h.get('x-provider-time');if(!t||Math.abs(Date.now()/1000-Number(t))>300||h.get('x-provider-signature')!==createHmac('sha256',b.secret).update(t+'.'+raw).digest('hex'))throw Error('Invalid signature');return JSON.parse(raw);};
ok((await verifiedProviderEvent(raw,headers,cp,{secret},verifier)).payload.outcome==='delivered','vendor-verified normalized receipt bound to attempt');await deny(()=>verifiedProviderEvent(raw+' ',headers,cp,{secret},verifier),'tampered callback denied');await deny(()=>verifiedProviderEvent(raw,new Headers(),cp,{secret},verifier),'unsigned callback denied');await deny(()=>verifiedProviderEvent(raw,headers,{...cp,structured_callbacks:false},{secret},verifier),'unavailable vendor telemetry rejected');await deny(()=>verifiedProviderEvent(raw,headers,cp,{secret},null),'no selected vendor verifier fails closed');await deny(()=>verifiedProviderEvent(raw,headers,cp,{},async()=>({...payload,organization_id:'arbitrary'})),'callback cannot supply organization authority');ok((await verifiedProviderEvent('',headers,cp,{},async()=>({event_id:'stop',provider:'sms_transport',type:'preference',keyword:'STOP',address:'+15550000001'}))).action==='keyword_external','STOP START HELP handoff no payment logic');await deny(()=>boundedBody(new Request('https://example.test',{method:'POST',body:'x'.repeat(8193)})),'streamed callback size bounded');
// Actual pinned Nodemailer composes MIME locally. No socket/provider or credentials.
let mime;
const mimeFactory={createTransport(){const t=nodemailer.createTransport({streamTransport:true,buffer:true,newline:'unix',disableFileAccess:true,disableUrlAccess:true});return{close(){t.close();},sendMail:async e=>{const r=await t.sendMail(e);mime=r.message.toString();return{messageId:r.messageId,accepted:[e.to],rejected:[]};}};}};
const rendered=await smtpAdapter(mimeFactory,binding).send({...job,rendered_body:'Plain <script>literal</script> & text'});
ok(rendered.status==='sent'&&mime.includes('multipart/alternative')&&mime.includes('Reply-To: reply@example.test')&&mime.includes('To: recipient@example.test'),'actual Nodemailer MIME single approved envelope and plain/HTML alternatives');
ok(mime.replace(/=\r?\n/g,'').includes('&lt;script&gt;literal&lt;/script&gt; &amp; text')&&mime.includes('Content-Type: text/plain')&&mime.includes('Content-Type: text/html'),'actual Nodemailer preserves escaped HTML and plain fallback');
console.log(n+' H1 adapter and runtime checks passed');
