import assert from 'node:assert/strict';import{JSDOM,VirtualConsole}from'jsdom';import{readFileSync}from'node:fs';
const read=p=>readFileSync(new URL('../../'+p,import.meta.url),'utf8'),tick=()=>new Promise(r=>setTimeout(r,30));let n=0;const ok=(v,m)=>{assert.ok(v,m);n++;console.log('PASS '+m)};
async function page(name,query=''){const vc=new VirtualConsole(),errors=[];vc.on('jsdomError',e=>errors.push(e));const dom=new JSDOM(read(name+'.html'),{url:'https://example.test/'+name+'.html'+query,runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc}),w=dom.window;w.matchMedia=()=>({matches:false});w.eval(read('tools/backend-tests/fixtures/communications-browser-fixture.js'));w.eval(read('assets/js/outreach-staff-common.js'));w.eval(read('assets/js/staff-workspace.js'));w.eval(read('assets/js/communications.js'));await tick();return{w,d:w.document,dom,errors,s:w.commFixture};}
for(const name of ['staff-communications','staff-campaign-communications','staff-communication-templates','staff-communication-activity']){const h=await page(name);ok(h.d.querySelectorAll('.staff-sidebar').length===1,'shared shell '+name);ok(h.d.querySelector('[data-group=communications]'),'permission-filtered Communications navigation '+name);ok(h.errors.length===0,'no JS errors '+name);for(const node of h.d.querySelectorAll('input,select,textarea'))ok(!!node.closest('label')||!!node.getAttribute('aria-label'),'accessible label '+node.name);h.w.close();}
{const h=await page('staff-campaign-communications');const click=t=>[...h.d.querySelectorAll('button')].find(b=>b.textContent===t)?.click();click('Preview audience & message');await tick();ok(h.d.querySelector('.comm-preview')?.textContent.includes('2 recipients · 1 suppressed · 1 eligible'),'audience preview counts and suppression');ok(h.s.calls.filter(x=>x.args.p_action==='confirm').length===0,'preview never queues');const b=[...h.d.querySelectorAll('button')].find(x=>x.textContent==='Confirm & queue');ok(b.disabled,'confirmation checkbox required');const cb=h.d.querySelector('.comm-preview>label input');cb.checked=true;cb.dispatchEvent(new h.w.Event('change'));b.click();await tick();ok(h.s.calls.filter(x=>x.args.p_action==='confirm').length===1,'one confirmed server batch action');ok(h.d.querySelector('.comm-preview').textContent.includes('messages queued'),'UI says queued not delivered');h.s.deny=true;h.w.dispatchEvent(new h.w.Event('focus'));await tick();ok(!h.d.querySelector('.comm-preview')&&h.d.querySelector('.staff-state'),'revocation clears protected preview');h.w.close();}
{const h=await page('staff-campaign-communications','?organization=aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1&person=cccccccc-cccc-4ccc-8ccc-ccccccccccc1');ok(h.d.querySelector('[name=kind]').value==='person','People context constrained recipient');ok(h.s.calls.some(x=>x.args.p_action==='history'),'person history canonical endpoint');h.w.close();}
{const h=await page('staff-communication-activity');const b=[...h.d.querySelectorAll('button')].find(x=>x.textContent==='View message');b.click();await tick();ok(h.d.querySelector('.comm-body').textContent.includes('Synthetic message content'),'body fetched only on explicit permitted action');h.w.close();}
{const h=await page('staff-campaign-communications');let done;h.s.delay=new Promise(r=>done=r);[...h.d.querySelectorAll('button')].find(b=>b.textContent==='Preview audience & message').click();await tick();h.s.user=null;h.s.callbacks.forEach(fn=>fn('SIGNED_OUT',null));done();await tick();ok(!h.d.querySelector('.comm-preview'),'stale post-signout response discarded');h.w.close();}
console.log(n+' Phase G DOM checks passed');
