// True local PostgreSQL sessions and server barrier; no hosted project or credentials.
import assert from 'node:assert/strict';import{execFile,execFileSync}from'node:child_process';import{promisify}from'node:util';import{mkdtempSync,mkdirSync,readFileSync,rmSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';import{randomUUID as uid}from'node:crypto';import{migrationOrder}from'./migration-order.mjs';import{f,fixtureSQL}from'./communications-fixture.mjs';
const run=promisify(execFile),bin=process.env.TEST_POSTGRES_BIN||'/opt/homebrew/opt/postgresql@17/bin',exe=x=>join(bin,x),root=mkdtempSync(join(tmpdir(),'comm-g-pg-')),data=join(root,'data'),socket=join(root,'socket');mkdirSync(socket);const port='55501',args=['-X','-q','-A','-t','-v','ON_ERROR_STOP=1','-h',socket,'-p',port,'-U','postgres','postgres'],sql=s=>execFileSync(exe('psql'),args,{input:s,encoding:'utf8',maxBuffer:5e6}).trim(),lit=s=>"'"+String(s).replaceAll("'","''")+"'";let started=false;
function overlap(rows){const events=rows.flatMap(r=>[[Number(r.start),1],[Number(r.end),-1]]).sort((a,b)=>a[0]-b[0]||a[1]-b[1]);let active=0,max=0;for(const [,delta]of events){active+=delta;max=Math.max(active,max)}return max;}
try{execFileSync(exe('initdb'),['-D',data,'--auth=trust','-U','postgres','--locale=C','--encoding=UTF8'],{stdio:'inherit',env:{...process.env,LC_ALL:'C',LANG:'C'}});execFileSync(exe('pg_ctl'),['-D',data,'-l',join(root,'pg.log'),'-o',`-k ${socket} -p ${port} -c listen_addresses=''`,'-w','start'],{stdio:'ignore'});started=true;
 sql(readFileSync(new URL('fixtures/supabase-test-bootstrap.sql',import.meta.url),'utf8'));sql(readFileSync(new URL('../../supabase/bootstrap/automatic-rls.sql',import.meta.url),'utf8'));for(const file of migrationOrder)sql(readFileSync(new URL('../../supabase/migrations/'+file,import.meta.url),'utf8'));sql(fixtureSQL);
 sql(`create table public.phaseg_barrier(run uuid,worker int,pid int,primary key(run,worker));create policy barrier_local on public.phaseg_barrier for all to authenticated,service_role using(true)with check(true);grant select,insert on phaseg_barrier to authenticated,service_role;
 create function public.phaseg_race(run uuid,n int,worker boolean,action text,p jsonb)returns jsonb language plpgsql security invoker as $$declare began numeric;answer jsonb;deadline timestamptz:=clock_timestamp()+interval '20 seconds';begin while(select count(*)from phaseg_barrier b where b.run=phaseg_race.run)<n loop if clock_timestamp()>deadline then raise exception 'Barrier timeout';end if;perform pg_sleep(.01);end loop;began:=extract(epoch from clock_timestamp());if worker then answer:=communications_service(action,'${f.org}',p);else answer:=communications_workspace(action,'${f.campaign}',p||'{"organization_id":"${f.org}"}');end if;return jsonb_build_object('pid',pg_backend_pid(),'start',began,'end',extract(epoch from clock_timestamp()),'answer',answer);end$$;grant execute on function phaseg_race(uuid,int,boolean,text,jsonb)to authenticated,service_role;`);
 const coordinator=execFile(exe('psql'),args,{maxBuffer:2e6}),pending=[];let buffer='';coordinator.stdout.on('data',s=>{buffer+=s;let i;while((i=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,i).trim();buffer=buffer.slice(i+1);if(line&&pending.length)pending.shift()(line)}});const ask=s=>new Promise(resolve=>{pending.push(resolve);coordinator.stdin.write(s+'\n')});const coord=Number(await ask('select pg_backend_pid();'));
 async function race(label,items){const key=uid(),n=items.length;await ask(`begin;select pg_advisory_xact_lock(hashtextextended('communications:${f.org}',0));select 'locked';`);const jobs=items.map(([worker,action,p],i)=>run(exe('psql'),args.concat(['-c',`set request.jwt.claim.sub='${worker?'':f.user}';set role ${worker?'service_role':'authenticated'};insert into phaseg_barrier values('${key}',${i},pg_backend_pid());`,'-c',`select phaseg_race('${key}',${n},${worker},${lit(action)},${lit(JSON.stringify(p))});`]),{maxBuffer:1e6}).then(r=>JSON.parse(r.stdout.trim())));
 const until=Date.now()+20000;let active=0;while(Date.now()<until){active=Number(await ask(`select pg_stat_clear_snapshot();select count(*) from pg_stat_activity where pid<>pg_backend_pid() and query like '%${key}%' and state='active' and wait_event_type='Lock';`));if(active===n)break;await new Promise(r=>setTimeout(r,30));}const ready=Number(await ask(`select count(*) from phaseg_barrier where run='${key}';`));await ask("commit;select 'released';");const rows=await Promise.all(jobs);assert.equal(active,n);assert.equal(ready,n);assert.equal(new Set(rows.map(r=>r.pid)).size,n);assert(rows.every(r=>r.pid!==coord));assert.equal(overlap(rows),n);console.log('PASS '+label+' '+JSON.stringify({workers:n,distinct_backends:n,coordinator_separate:true,server_barrier_ready:ready,peak_active_queries:active,max_overlapping_intervals:overlap(rows)}));return rows;}
 const repeat=(worker,a,p)=>Array.from({length:8},()=>[worker,a,p]);
 const staff=(a,p)=>JSON.parse(sql(`set request.jwt.claim.sub='${f.user}';set role authenticated;select communications_workspace(${lit(a)},'${f.campaign}',${lit(JSON.stringify({organization_id:f.org,...p}))});`));
 const worker=(a,p={})=>JSON.parse(sql(`set role service_role;select communications_service(${lit(a)},'${f.org}',${lit(JSON.stringify(p))});`));
 try{
 await race('A automated reminder',repeat(true,'consume_events',{}));assert.equal(Number(sql(`select count(*) from communication_outbox where source_event_id='${f.event}'`)),1);
 const pr=staff('preview',{request_key:uid(),channel:'email',template_id:f.template,sender_profile_id:f.sender,audience:{kind:'contacts'}});await race('B duplicate bulk approval',repeat(false,'confirm',{id:pr.batch.id,confirmed:true}));assert.equal(Number(sql(`select count(*)from communication_batches where state='queued'`)),1);assert.equal(Number(sql(`select count(*)from communication_outbox where batch_id='${pr.batch.id}'`)),2);
 let job=worker('claim').messages[0];worker('authorize_dispatch',{id:job.id,lease_token:job.lease_token});worker('result',{id:job.id,lease_token:job.lease_token,outcome:'sent',provider_message_id:'race-sink'});
 await race('C duplicate delivered callback',repeat(true,'callback',{event_id:'race-delivered',provider:'acceptance_sink',provider_message_id:'race-sink',outcome:'delivered'}));assert.equal(Number(sql(`select count(*)from communication_audit where subject_id='${job.id}' and kind='delivery.delivered'`)),1);
 sql(`update communication_outbox set status='cancelled',lease_token=null where status<>'delivered';`);const only=staff('preview',{request_key:uid(),channel:'email',template_id:f.template,sender_profile_id:f.sender,audience:{kind:'person',person_id:f.person}});staff('confirm',{id:only.batch.id,confirmed:true});
 const revoke={audience:{kind:'person',person_id:f.person},recipient_key:'person:'+f.person,channel:'email',purpose:'event_updates',status:'revoked',source:'Synthetic revoke',proof_reference:'synthetic-revoke',explicitly_reviewed:true};const rows=await race('D revocation vs queued claim',[[false,'consent',revoke],...Array.from({length:7},()=>[true,'claim',{}])]);for(const r of rows)for(const j of r.answer.messages||[])assert.equal(worker('authorize_dispatch',{id:j.id,lease_token:j.lease_token}).authorized,false);assert.equal(Number(sql(`select count(*)from communication_outbox where batch_id='${only.batch.id}' and dispatch_authorized_at is not null`)),0);
 const drafts=[];for(let i=0;i<8;i++)drafts.push(staff('template_create',{template_key:'publish_race',channel:'email',message_type:'campaign',purpose:'event_updates',subject:'Synthetic',body:'Hello {{first_name}}'}));await race('E active template publication',drafts.map(t=>[false,'template_publish',{id:t.id,revision:t.revision}]));assert.equal(Number(sql("select count(*)from communication_templates where template_key='publish_race' and active")),1);
 staff('consent',{...revoke,status:'granted'});const retry=staff('preview',{request_key:uid(),channel:'email',template_id:f.template,sender_profile_id:f.sender,audience:{kind:'person',person_id:f.person}});staff('confirm',{id:retry.batch.id,confirmed:true});let initial=worker('claim').messages[0];worker('authorize_dispatch',{id:initial.id,lease_token:initial.lease_token});worker('result',{id:initial.id,lease_token:initial.lease_token,outcome:'transient'});sql(`update communication_outbox set scheduled_at=now()-interval '1 minute' where id='${initial.id}';`);let rs=await race('F retry worker lease',repeat(true,'claim',{}));assert.equal(rs.reduce((s,r)=>s+(r.answer.messages||[]).length,0),1);assert.equal(Number(sql(`select count(*)from communication_attempts a join communication_outbox m on m.id=a.message_id where m.batch_id='${retry.batch.id}'`)),2);
 console.log('PASS all six Phase G races with 8 independent overlapping workers');
 }finally{coordinator.stdin.end();await new Promise(r=>coordinator.once('exit',r));}
}finally{if(started)execFileSync(exe('pg_ctl'),['-D',data,'-m','fast','-w','stop'],{stdio:'ignore'});rmSync(root,{recursive:true,force:true});}
