// Disposable synthetic local databases only. Never run this fixture against a hosted project.
export const f={org:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1',other:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa2',user:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb1',limited:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb2',stranger:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb3',person:'cccccccc-cccc-4ccc-8ccc-ccccccccccc1',person2:'cccccccc-cccc-4ccc-8ccc-ccccccccccc2',campaign:'dddddddd-dddd-4ddd-8ddd-ddddddddddd1',workflow:'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeee1',sender:'ffffffff-ffff-4fff-8fff-fffffffffff1',sms:'ffffffff-ffff-4fff-8fff-fffffffffff2',template:'11111111-1111-4111-8111-111111111111',step:'22222222-2222-4222-8222-222222222222',reminder:'33333333-3333-4333-8333-333333333333',event:'44444444-4444-4444-8444-444444444444'};
export const fixtureSQL=`
insert into auth.users(id,email,email_confirmed_at)values('${f.user}','staff@example.test',now()),('${f.limited}','campaign@example.test',now()),('${f.stranger}','participant@example.test',now());
insert into organizations(id,slug,name,kind)values('${f.org}','comm-synthetic','Synthetic tenant','ministry'),('${f.other}','comm-other','Other synthetic tenant','ministry');
insert into organization_staff_directory(organization_id,user_id,display_name)values('${f.org}','${f.user}','Synthetic communications staff');
insert into organization_staff_permissions(organization_id,user_id,permission)select '${f.org}','${f.user}',unnest(array['people.read','people.create','people.update','communications.view','communications.send','communications.bulk_send','communications.templates.view','communications.templates.manage','communications.delivery.view']);
set request.jwt.claim.sub='${f.user}';
insert into organization_people(id,organization_id,first_name,last_name,email,phone)values('${f.person}','${f.org}','Ada','Synthetic','ada@example.test','+15550000001'),('${f.person2}','${f.org}','Bert','Synthetic','bert@example.test','+15550000002');
insert into outreach_workflow_templates(id,organization_id,template_key,version,title,steps)values('${f.workflow}','${f.org}','comm_synthetic',1,'Synthetic workflow','[{"key":"reminder","title":"Synthetic task","order":1}]');
insert into outreach_campaigns(id,organization_id,code,name,city,country,timezone,template_id,event_start,venue)values('${f.campaign}','${f.org}','comm_synthetic','Synthetic event','Test','US','America/New_York','${f.workflow}',now()+interval '30 days','{"site_name":"Synthetic hall"}');
insert into outreach_campaign_contacts(campaign_id,organization_id,person_id,role_key)values('${f.campaign}','${f.org}','${f.person}','host_pastor'),('${f.campaign}','${f.org}','${f.person}','local_coordinator'),('${f.campaign}','${f.org}','${f.person2}','internal_team');
insert into outreach_campaign_assignments(campaign_id,user_id,role_key,capabilities,reason)values('${f.campaign}','${f.limited}','host_pastor',array['view','communications.view','communications.send','communications.delivery.view'],'Synthetic scoped assignment');
insert into communication_settings(organization_id,delivery_mode)values('${f.org}','acceptance_sink');
insert into communication_sender_profiles(id,organization_id,channel,provider,display_name,from_address,active,approved_at)values('${f.sender}','${f.org}','email','acceptance_sink','Synthetic tenant','sink@example.test',true,now()),('${f.sms}','${f.org}','sms','acceptance_sink','Synthetic tenant','synthetic-service',true,now());
insert into communication_templates(id,organization_id,template_key,channel,message_type,purpose,version,subject,body,state,active,created_by,published_at)values('${f.template}','${f.org}','reminder','email','reminder','event_updates',1,'{{campaign_name}}','Hello {{first_name}}: {{campaign_date}}','published',true,'${f.user}',now());
insert into communication_consents(organization_id,campaign_id,recipient_key,channel,purpose,status,source,proof_reference,recorded_by)select '${f.org}','${f.campaign}','person:'||p.id,ch,'event_updates','granted','Synthetic reviewed form','synthetic-proof','${f.user}' from organization_people p cross join unnest(array['email','sms']) ch where p.organization_id='${f.org}';
update outreach_campaign_steps set id='${f.step}',due_at=now()-interval '1 day',assigned_role='host_pastor' where campaign_id='${f.campaign}' and step_key='reminder';
insert into outreach_task_reminders(id,campaign_id,step_id,reminder_key,kind,scheduled_at,due_snapshot,recipient_roles)values('${f.reminder}','${f.campaign}','${f.step}','synthetic','due',now()-interval '1 hour',now()-interval '1 day','["host_pastor"]');
update outreach_task_reminders set due_snapshot=(select due_at from outreach_campaign_steps where id='${f.step}') where id='${f.reminder}';
insert into outreach_campaign_events(id,campaign_id,event_key,kind,subject_id)values('${f.event}','${f.campaign}','reminder:${f.reminder}','outreach.task.due','${f.step}');
insert into communication_routes(organization_id,campaign_id,event_kind,template_id,sender_profile_id,audience,enabled,approved_by,approved_at)values('${f.org}','${f.campaign}','outreach.task.due','${f.template}','${f.sender}','{"kind":"contacts"}',true,'${f.user}',now()-interval '1 minute');
`;
