import os from 'node:os';import path from 'node:path';
import {JSDOM} from 'jsdom';import fs from 'node:fs';import assert from 'node:assert/strict';
const read=f=>fs.readFileSync(new URL('../../'+f,import.meta.url),'utf8'),snapshot=JSON.parse(fs.readFileSync(path.join(os.tmpdir(),'dream-team-synthetic-snapshot.json')));const tick=()=>new Promise(r=>setTimeout(r,20));let tests=0;
async function mount({state='started',defer=false}={}){const d=new JSDOM(read('dream-team-application.html'),{url:'https://preview.example/dream-team-application.html',runScripts:'outside-only'}),w=d.window;w.structuredClone=structuredClone;w.HTMLCanvasElement.prototype.getContext=()=>({clearRect(){},beginPath(){},moveTo(){},lineTo(){},stroke(){}});w.confirm=()=>true;let user={id:'synthetic'},callback,resolve,revision=2,calls=[];const model=()=>({available:true,application:{id:'app',status:state,revision,identity_ready:true,documents:[]},form:snapshot.form,answers:structuredClone(snapshot.answers)});w.ChampionLifeAuth={getUser:async()=>user,getSession:async()=>user?{user,access_token:'test'}:null,client:{auth:{onAuthStateChange:f=>callback=f}}};w.CHAMPION_LIFE_SUPABASE={url:'https://db.example',publishableKey:'test'};w.fetch=async(_,opts)=>{const data=JSON.parse(opts.body);calls.push(data);if(defer&&data.p_action==='get')await new Promise(r=>resolve=r);if(data.p_action==='save'){assert.equal(data.p_data.revision,revision);revision++;}return {ok:true,json:async()=>model()};};for(const f of ['dream-track-common','dream-team-common','dream-team'])w.eval(read('assets/js/'+f+'.js'));await tick();return {d,w,calls,signOut:async()=>{user=null;callback('SIGNED_OUT',null);await tick();resolve?.();await tick();}};}
let t=await mount();for(let page=1;page<=8;page++){assert.match(t.w.document.querySelector('form h2').textContent,new RegExp('Page '+page));const schema=snapshot.form.fields.filter(f=>f.page===page&&!f.hidden);assert.equal(t.w.document.querySelectorAll('fieldset').length,schema.length);for(const f of schema){const field=t.w.document.querySelector(`[data-field="${f.id}"]`);assert(field);assert.equal(field.querySelector('legend').textContent,f.label||'Additional agreement');}assert(!t.w.document.querySelector('[data-field="id_33"]'));if(page<8){[...t.w.document.querySelectorAll('button')].find(b=>b.textContent==='Save & continue').click();await tick();}}tests+=8;t.d.window.close();
t=await mount();const name=t.w.document.querySelector('#first_11');name.value='Changed synthetic';name.dispatchEvent(new t.w.Event('input'));[...t.w.document.querySelectorAll('button')].find(b=>b.textContent==='Save now').click();await tick();assert.equal(t.calls.at(-1).p_data.answers.id_11.first_11,'Changed synthetic');assert.match(t.w.document.querySelector('[role=status]').textContent,/Saved/);await t.signOut();assert(!t.w.document.querySelector('fieldset'));assert(!t.w.document.body.textContent.includes('Changed synthetic'));tests++;t.d.window.close();
t=await mount({defer:true});await t.signOut();assert(!t.w.document.querySelector('fieldset'));tests++;t.d.window.close();
for(const state of ['submitted','under_review','approved_for_placement','declined','withdrawn']){t=await mount({state});assert(!t.w.document.querySelector('form'));assert(t.w.document.querySelector('#dream-team-app h2'));tests++;t.d.window.close();}
console.log('PASS '+tests+' native page fidelity, navigation, save, account clearing, delayed response and status scenarios');
