begin;
do $test$
declare org uuid; person uuid:=gen_random_uuid(); learner uuid:=gen_random_uuid(); reviewer uuid:=gen_random_uuid(); outsider uuid:=gen_random_uuid(); app jsonb; state jsonb; dep uuid; answers jsonb:=$answers${"id_11":{"last_11":"Synthetic response","first_11":"Synthetic response","middle_11":""},"id_12":{"input_12":"synthetic@example.test"},"id_13":{"input_13_full":"(555) 123-4567"},"id_15":{"id_15_date":"2026-10-02"},"id_16":{"input_16_city":"Synthetic response","input_16_state":"Synthetic response","input_16_postal":"Synthetic response","input_16_addr_line1":"Synthetic response","input_16_addr_line2":"Synthetic response"},"id_18":{"input_18_day":"2","input_18_year":"1990","input_18_month":"1"},"id_22":{"input_22":"Synthetic response"},"id_23":["CHILDREN'S* Please choose specific class(es) in next section.","YOUTH","MUSIC (WORSHIP/BAND)","SOUND"],"id_25":{"input_25":"Synthetic response"},"id_26":{"id_26_date":"2026-10-02"},"id_27":{"input_27":"Single"},"id_29":{"last_29":"Synthetic response","first_29":"Synthetic response","middle_29":"Synthetic response"},"id_32":["TOBACCO"],"id_34":["TOBACCO"],"id_36":["YES"],"id_37":{"input_37":"Synthetic response"},"id_38":["YES"],"id_39":["YES"],"id_40":["YES"],"id_41":{"input_41":"Synthetic response"},"id_42":["YES"],"id_43":["YES"],"id_44":{"input_44":"Synthetic response"},"id_45":{"input_45":"Synthetic response"},"id_49":{"input_49":"Synthetic response"},"id_50":{"input_50":"Synthetic response"},"id_53":["YES"],"id_54":["YES"],"id_55":{"input_55":"Synthetic response"},"id_56":{"input_56":"Synthetic response"},"id_57":["YES"],"id_58":["YES"],"id_59":{"input_59":"Synthetic response"},"id_60":{"input_60":"Synthetic response"},"id_61":["In the Virgin Birth and Deity of our Lord Jesus Christ."],"id_71":[[[0.1,0.2],[0.3,0.6],[0.8,0.2]]],"id_72":{"id_72_date":"2026-10-02"},"id_77":["I have read and agree to the General Dream Team Code of Ethics for Levels 1-2-3 Dream Team Members."],"id_81":["N/A"],"id_82":["YES","NO"],"id_83":["YES"],"id_86":{"input_86":"Synthetic response"},"id_87":{"input_87":"Synthetic response"},"id_88":{"input_88":"Synthetic response"},"id_89":["Yes"],"id_91":{"input_91":"Synthetic response"},"id_92":["Yes"],"id_93":{"input_93":"Synthetic response"},"id_95":["I have read and agree to the Additional Dream Team Code of Ethics for Level 2 & 3 Dream Team Members."],"id_96":{"input_96":"Synthetic response"},"id_102":["Growth Track (4 week series)"]}$answers$; denied boolean; before_grants integer; begin
 select id into org from public.organizations where slug='champion-life';
 insert into auth.users(id,email,email_confirmed_at) values(learner,'dream-team-rollback-learner@example.test',now()),(reviewer,'dream-team-rollback-reviewer@example.test',now()),(outsider,'dream-team-rollback-outsider@example.test',now());
 insert into public.organization_staff_directory(organization_id,user_id,display_name)values(org,reviewer,'Synthetic rollback reviewer');
 insert into public.organization_staff_permissions(organization_id,user_id,permission)select org,reviewer,p from unnest(array['people.read','dream_team.application.read','dream_team.application.manage','dream_team.application.restricted','dream_team.placement.manage'])p;
 alter table public.organization_people disable trigger user;
 insert into private.people(id)values(person);insert into public.organization_people(id,human_id,organization_id,first_name,last_name)values(person,person,org,'Synthetic','Rollback');
 alter table public.organization_people enable trigger user;
 insert into public.portal_account_links(organization_id,person_id,user_id,verification_note)values(org,person,learner,'Rollback synthetic reviewed association');
 perform set_config('request.jwt.claim.sub',reviewer::text,true);set local role authenticated;
 app:=public.dream_team_admin(org,'enable',jsonb_build_object('person_id',person));if app->>'status'<>'available' then raise exception 'Manual eligibility failed';end if;
 reset role;perform set_config('request.jwt.claim.sub',learner::text,true);set local role authenticated;
 state:=public.dream_team('get','{}');state:=public.dream_team('save',jsonb_build_object('revision',state#>'{application,revision}','answers',answers));
 denied:=false;begin perform public.dream_team('save',jsonb_build_object('revision',0,'answers',answers));exception when others then denied:=true;end;if not denied then raise exception 'Stale write allowed';end if;
 state:=public.dream_team('submit',jsonb_build_object('revision',state#>'{application,revision}'));if state#>>'{application,status}'<>'submitted' then raise exception 'Submit failed';end if;
 state:=public.dream_team('submit',jsonb_build_object('revision',0));if jsonb_array_length(state->'submissions')<>1 then raise exception 'Duplicate submission';end if;
 denied:=false;begin perform public.dream_team_admin(org,'review',jsonb_build_object('id',app->>'id','status','approved_for_placement'));exception when others then denied:=true;end;if not denied then raise exception 'Applicant decision allowed';end if;
 reset role;perform set_config('request.jwt.claim.sub',outsider::text,true);set local role authenticated;
 state:=public.dream_team('get',jsonb_build_object('id',app->>'id'));if(state->>'available')::boolean then raise exception 'Other account access';end if;
 denied:=false;begin perform public.dream_team_admin(org,'detail',jsonb_build_object('id',app->>'id'));exception when others then denied:=true;end;if not denied then raise exception 'Unprivileged detail';end if;
 denied:=false;begin perform public.dream_team_worker('claim','{}');exception when others then denied:=true;end;if not denied then raise exception 'Client worker allowed';end if;
 reset role;perform set_config('request.jwt.claim.sub',reviewer::text,true);set local role authenticated;
 app:=public.dream_team_admin(org,'detail',jsonb_build_object('id',app->>'id'));
 app:=public.dream_team_admin(org,'review',jsonb_build_object('id',app->>'id','revision',app->'revision','status','more_info_requested','note','PRIVATE SYNTHETIC NOTE','request','Please clarify availability.'));
 reset role;perform set_config('request.jwt.claim.sub',learner::text,true);set local role authenticated;
 state:=public.dream_team('get','{}');if state::text like '%PRIVATE SYNTHETIC NOTE%' then raise exception 'Private note leaked';end if;
 state:=public.dream_team('respond',jsonb_build_object('revision',state#>'{application,revision}','response','Synthetic clarification'));
 reset role;perform set_config('request.jwt.claim.sub',reviewer::text,true);set local role authenticated;
 app:=public.dream_team_admin(org,'detail',jsonb_build_object('id',app->>'id'));
 app:=public.dream_team_admin(org,'review',jsonb_build_object('id',app->>'id','revision',app->'revision','status','approved_for_placement'));
 if app->>'placement_status'<>'unassigned' then raise exception 'Approval assigned automatically';end if;
 reset role;
 denied:=false;begin update private.dream_team_submissions set snapshot='{}' where application_id=(app->>'id')::uuid;exception when others then denied:=true;end;if not denied then raise exception 'Snapshot mutable';end if;
 if exists(select 1 from private.domain_events where source_id=(app->>'id')::uuid and to_jsonb(domain_events)::text like '%Synthetic response%')then raise exception 'Event answer leakage';end if;
 if not exists(select 1 from private.dream_team_jobs where application_id=(app->>'id')::uuid and kind='pdf' and status='queued')then raise exception 'PDF not queued';end if;
end $test$;
rollback;
select 'PASS: hosted synthetic eligibility, autosave/stale rejection, immutable submission/replay, account isolation, restricted review, worker gate, more information/private notes, approval separation and PDF queue; all fixtures rolled back' as result;
