-- Rollback-only synthetic acceptance. Never run against production.
begin;
create function pg_temp.assert_true(v boolean,m text) returns void language plpgsql as $$begin if v is distinct from true then raise exception 'Dream Track assertion failed: %',m;end if;end$$;
select pg_temp.assert_true((select count(*)=140 from public.course_questions where active),'140 active questions');
select pg_temp.assert_true((select count(*)=7 from public.course_lessons),'seven reused videos');
select pg_temp.assert_true(not exists(select 1 from public.course_lessons l where (select count(*) from public.course_questions q where q.course_id=l.course_id and q.lesson_number=l.lesson_number and q.active)<>20),'20 questions each');
insert into auth.users(id,email,email_confirmed_at)values('49000000-0000-4000-8000-000000000001','dream-acceptance-manager@example.test',now()),('49000000-0000-4000-8000-000000000002','dream-acceptance-student@example.test',now());
insert into public.organization_staff_directory(organization_id,user_id,display_name)select id,'49000000-0000-4000-8000-000000000001','Synthetic Dream manager' from public.organizations where slug='champion-life';
insert into public.organization_staff_permissions(organization_id,user_id,permission)select id,'49000000-0000-4000-8000-000000000001','courses.manage' from public.organizations where slug='champion-life';
select set_config('request.jwt.claim.sub','49000000-0000-4000-8000-000000000001',true);
set local role authenticated;
select public.dream_track_admin((select id from public.organizations where slug='champion-life'),'code','{"code":"synthetic-acceptance-code","active":true}');
reset role;
select set_config('request.jwt.claim.sub','49000000-0000-4000-8000-000000000002',true);
set local role authenticated;
select pg_temp.assert_true((public.dream_track('claim_code','{"code":"wrong"}')->>'error') is not null,'wrong code fails honestly');
select pg_temp.assert_true((public.dream_track('claim_code','{"code":"synthetic-acceptance-code"}')->>'enrolled')::boolean,'correct code enrolls');
select pg_temp.assert_true(not (public.dream_track('dashboard')->'lessons'->1->>'unlocked')::boolean,'next lesson locked');
select pg_temp.assert_true((public.dream_track('lesson','{"lesson":1}')->'questions') is not null,'enrolled lesson loads');
reset role;
-- Exact boundary fixture: watched ranges are trusted test setup, never learner input.
update public.lesson_progress set watched_ranges=nummultirange(numrange(0,1925*.949,'[)')) where user_id='49000000-0000-4000-8000-000000000002' and lesson_number=1 and course_id=(select id from public.courses where slug='dream-track');
create temp table dream_submission as select jsonb_build_object('lesson',1,'request_id',gen_random_uuid(),'answers',jsonb_object_agg(question_number,case when question_number<=16 then correct_answer else 'synthetic wrong' end))v from public.course_questions where course_id=(select id from public.courses where slug='dream-track') and lesson_number=1;
grant select on dream_submission to authenticated;
set local role authenticated;
select pg_temp.assert_true((public.dream_track('submit',(select v from dream_submission))->'lessons'->0->>'mastered')::int=16,'16 mastered');
select pg_temp.assert_true(not(public.dream_track('dashboard')->'lessons'->1->>'unlocked')::boolean,'94.9 percent does not pass');
reset role;
update public.lesson_progress set watched_ranges=nummultirange(numrange(0,1925*.95,'[)')) where user_id='49000000-0000-4000-8000-000000000002' and lesson_number=1 and course_id=(select id from public.courses where slug='dream-track');
set local role authenticated;
select pg_temp.assert_true((public.dream_track('save','{"lesson":1}')->'lessons'->1->>'unlocked')::boolean,'exact95 plus16 unlocks');
select pg_temp.assert_true((public.dream_track('lesson','{"lesson":1}')->'questions'->19->>'mastered')::boolean=false,'four misses need not be corrected');
reset role;
select pg_temp.assert_true((select count(*)=20 from public.course_attempts where enrollment_id=(select id from public.course_enrollments where user_id='49000000-0000-4000-8000-000000000002' and course_id=(select id from public.courses where slug='dream-track'))),'immutable first attempt rows');
select pg_temp.assert_true(not has_table_privilege('authenticated','public.course_questions','SELECT'),'no client answer key read');
select pg_temp.assert_true(not has_function_privilege('authenticated','public.course_invite_delivery(uuid,uuid,boolean)','EXECUTE'),'browser cannot forge email sent');
select pg_temp.assert_true((select count(*)=0 from public.course_completions c join public.course_enrollments e on e.id=c.enrollment_id where e.user_id='49000000-0000-4000-8000-000000000002' and c.badge_awarded_at is not null),'no premature badge');
select pg_temp.assert_true((select count(*)=0 from public.organization_staff_permissions where user_id='49000000-0000-4000-8000-000000000002'),'no course authority grant');
rollback;
