import os from 'node:os';import path from 'node:path';
import {PGlite} from '@electric-sql/pglite';import fs from 'node:fs';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
const db=new PGlite(),q=(s,a=[])=>db.query(s,a);const root=new URL('../../',import.meta.url);let count=0;const check=(v,m)=>{assert.ok(v,m);count++;console.log('PASS '+m)},deny=async(fn,m)=>{await assert.rejects(fn);check(true,m)};
await db.exec(fs.readFileSync(new URL('fixtures/supabase-test-bootstrap.sql',import.meta.url),'utf8'));await db.exec(fs.readFileSync(new URL('supabase/bootstrap/automatic-rls.sql',root),'utf8'));for(const f of fs.readdirSync(new URL('supabase/migrations',root)).sort())await db.exec(fs.readFileSync(new URL('supabase/migrations/'+f,root),'utf8'));
const form=JSON.parse(fs.readFileSync(new URL('assets/data/dream-team-form.json',root)));assert.deepEqual((await q('select definition from private.dream_team_forms')).rows[0].definition,form);check(form.fields.length===52&&form.fields.filter(f=>!f.hidden).length===51,'52 fields, 51 visible, exact database/browser definition');check(form.fields.filter(f=>f.required).length===45,'45 original required markers');check(form.fields[16].id==='id_33'&&form.fields[16].hidden,'hidden required duplicate preserved');check(form.fields.find(f=>f.id==='id_102').controls.some(c=>c.value==='Dream Track (6 week series)'),'approved six week wording preserved');
const fidelity=JSON.parse(fs.readFileSync(new URL('fixtures/dream-team-source-fidelity.json',import.meta.url)));
assert.deepEqual(form.fields.map(f=>({id:f.id,label:f.label,required:f.required,page:f.page,type:f.type,options:['checkbox','radio'].includes(f.type)?f.controls.map(c=>c.value):[],sensitivity:f.sensitivity,selects:f.controls.filter(c=>c.options).map(c=>({id:c.id,options:c.options}))})),fidelity.fields);check(true,'all 52 prompts, ordered options, requiredness and source sensitivity match independent handoff fixture');
const id=n=>`50000000-0000-4000-8000-${String(n).padStart(12,'0')}`,org=(await q("select id from organizations where slug='champion-life'")).rows[0].id,other=(await q("select id from organizations where slug='sowgo'")).rows[0].id,cid=(await q("select id from courses where slug='dream-track'")).rows[0].id;
for(let n=1;n<=6;n++)await q('insert into auth.users(id,email,email_confirmed_at) values($1,$2,$3)',[id(n),`team-${n}@example.test`,n===6?null:new Date()]);
for(const n of [1,4,5])await q("insert into organization_staff_directory(organization_id,user_id,display_name)values($1,$2,'Synthetic reviewer')",[org,id(n)]);
for(const key of ['dream_team.application.read','dream_team.application.manage','dream_team.application.restricted','dream_team.placement.manage','communications.send','people.read','people.create','people.update','portal.manage','courses.manage'])await q('insert into organization_staff_permissions(organization_id,user_id,permission)values($1,$2,$3)',[org,id(1),key]);
for(const [n,key]of [[4,'people.read'],[5,'dream_team.application.read']])await q('insert into organization_staff_permissions(organization_id,user_id,permission)values($1,$2,$3)',[org,id(n),key]);
const as=async(n)=>{await db.exec('reset role');await q("select set_config('request.jwt.claim.sub',$1,false)",[n?id(n):'']);await db.exec('set role '+(n?'authenticated':'anon'))};
const rpc=async(action,data={})=>(await q('select dream_team($1,$2) v',[action,JSON.stringify(data)])).rows[0].v;
const admin=async(action,data={},o=org)=>(await q('select dream_team_admin($1,$2,$3) v',[o,action,JSON.stringify(data)])).rows[0].v;
await db.exec('alter table organization_people disable trigger user');const pid=id(100);await q('insert into private.people(id)values($1)',[pid]);await q("insert into organization_people(id,human_id,organization_id,first_name,last_name)values($1,$1,$2,'Synthetic','Applicant')",[pid,org]);await db.exec('alter table organization_people enable trigger user');await db.exec('alter table organization_departments disable trigger user');await q("insert into organization_departments(organization_id,name)values($1,'Synthetic ministry')",[org]);await db.exec('alter table organization_departments enable trigger user');
await db.exec('reset role');await q("insert into portal_account_links(organization_id,person_id,user_id,verification_note) values($1,$2,$3,'Synthetic reviewed account association')",[org,pid,id(2)]);
await as(0);await deny(()=>rpc('get'),'anonymous denied');await as(6);await deny(()=>rpc('get'),'unverified denied');await as(2);check(!(await rpc('get')).available,'no self-enable');await deny(()=>admin('enable',{person_id:pid}),'learner cannot enable');await as(1);let a=await admin('enable',{person_id:pid});check(a.status==='available'&&a.identity_ready,'manual availability before course enrollment');await db.exec('reset role');check((await q('select count(*)::int n from course_enrollments')).rows[0].n===0,'manual enable does not alter course progress');await as(1);await admin('send',{id:a.id});await deny(()=>admin('send',{id:a.id}),'resends rate limited');await as(4);await deny(()=>admin('list'),'ordinary people staff denied application list');await as(5);await deny(()=>admin('detail',{id:a.id}),'read-only summary permission cannot read restricted responses');await as(1);await deny(()=>admin('list',{},other),'cross-org denied');
await as(2);let s=await rpc('get');check(s.application.status==='invited','account invitation available');const answers={};for(const f of form.fields){if(f.hidden)continue;if(f.type==='signature')answers[f.id]=[[[.1,.2],[.3,.6],[.8,.2]]];else if(['checkbox','radio'].includes(f.type))answers[f.id]=[f.controls[0].value];else answers[f.id]=Object.fromEntries(f.controls.map(c=>[c.id,c.type==='select'?c.options.find(o=>o.value)?.value:c.type==='date'?'2026-10-02':c.type==='email'?'synthetic@example.test':f.type==='phone'?'(555) 123-4567':'Synthetic response']));}
answers.id_18={input_18_month:'1',input_18_day:'2',input_18_year:'1990'};answers.id_23=form.fields.find(f=>f.id==='id_23').controls.slice(0,4).map(c=>c.value);answers.id_82=['YES','NO'];answers.id_11.middle_11='';
s=await rpc('save',{revision:s.application.revision,answers});check(s.application.status==='started','draft starts');const rev=s.application.revision;await deny(()=>rpc('save',{revision:rev-1,answers}),'stale save rejected');await as(3);check(!(await rpc('get',{id:a.id})).available,'other account cannot select application');await as(2);s=await rpc('get');assert.deepEqual(s.answers,answers);check(true,'cloud draft restored after account switch');await deny(()=>rpc('approve',{id:a.id}),'learner cannot approve');
await deny(()=>rpc('save',{revision:s.application.revision,answers:null}),'null answers rejected');
await deny(()=>rpc('save',{revision:s.application.revision,answers:{...answers,id_33:{input_33:'hidden injection'}}}),'hidden duplicate cannot accept answers');
await deny(()=>rpc('save',{revision:s.application.revision,answers:{...answers,id_71:[[[0,0],[2,1]]]}}),'out-of-bounds signature rejected');
const noName=structuredClone(answers);noName.id_11.first_11='';s=await rpc('save',{revision:s.application.revision,answers:noName});await deny(()=>rpc('submit',{revision:s.application.revision}),'required visible name enforced');
const missing=structuredClone(answers);delete missing.id_71;s=await rpc('save',{revision:s.application.revision,answers:missing});await deny(()=>rpc('submit',{revision:s.application.revision}),'required drawn signature enforced');s=await rpc('save',{revision:s.application.revision,answers});s=await rpc('submit',{revision:s.application.revision});check(s.application.status==='submitted'&&s.submissions.length===1,'immutable submitted snapshot');check((await rpc('submit',{revision:1})).submissions.length===1,'submit replay idempotent');await deny(()=>rpc('save',{revision:s.application.revision,answers}),'submitted draft cannot overwrite');
await db.exec('reset role');await deny(()=>q("update private.dream_team_submissions set snapshot='{}'"),'snapshots immutable');await deny(()=>q('delete from private.domain_events'),'events immutable');await deny(()=>q("update private.dream_team_forms set definition='{}'"),'form version immutable');
await as(1);a=await admin('detail',{id:a.id});a=await admin('review',{id:a.id,revision:a.revision,status:'under_review',note:'PRIVATE review marker'});await deny(()=>admin('review',{id:a.id,revision:1,status:'declined'}),'stale decision rejected');a=await admin('review',{id:a.id,revision:a.revision,status:'more_info_requested',request:'Please clarify your availability.',note:'PRIVATE review marker'});await as(2);s=await rpc('get');check(s.request==='Please clarify your availability.'&&!JSON.stringify(s).includes('PRIVATE review marker'),'private reviewer notes excluded from applicant');await deny(()=>rpc('respond',{revision:s.application.revision}),'missing more-information response rejected');s=await rpc('respond',{revision:s.application.revision,response:'Synthetic clarification'});check(s.application.status==='submitted'&&s.submissions.length===2,'append-only information response');await as(1);a=await admin('detail',{id:a.id});a=await admin('review',{id:a.id,revision:a.revision,status:'approved_for_placement',note:'Synthetic human decision'});check(a.status==='approved_for_placement'&&a.placement_status==='unassigned','approval distinct from assignment');await deny(()=>admin('review',{id:a.id,revision:a.revision,status:'declined'}),'terminal decision cannot be casually overwritten');
await db.exec('reset role');const dep=(await q('select id from organization_departments where organization_id=$1 limit 1',[org])).rows[0].id;const authority=(await q('select count(*)::int n from organization_staff_permissions')).rows[0].n;
await as(2);await deny(()=>admin('place',{id:a.id,revision:a.revision,department_id:dep,team:'Test'}),'learner placement denied');await as(1);a=await admin('place',{id:a.id,revision:a.revision,department_id:dep,team:'Synthetic welcome',effective_at:'2026-10-02'});check(a.placement_status==='assigned','separate placement saved');await db.exec('reset role');check((await q('select count(*)::int n from organization_staff_permissions')).rows[0].n===authority,'placement grants no authority');check((await q('select count(*)::int n from person_department_affiliations where person_id=$1',[pid])).rows[0].n===1,'existing ministry affiliation reused');
// Independently test course trigger, idempotency, and no final-meeting dependency.
const eid=(await q('insert into course_enrollments(course_id,user_id) values($1,$2) returning id',[cid,id(3)])).rows[0].id;await q('insert into course_completions(enrollment_id,online_completed_at)values($1,now())',[eid]);await q('update course_completions set revision=revision+1 where enrollment_id=$1',[eid]);const auto=(await q('select * from private.dream_team_applications where user_id=$1',[id(3)])).rows[0];check(auto.status==='available','online completion before meeting creates availability');check((await q("select count(*)::int n from private.dream_team_jobs where application_id=$1 and kind='online_email'",[auto.id])).rows[0].n===1,'online email queued exactly once');check((await q('select badge_awarded_at from course_completions where enrollment_id=$1',[eid])).rows[0].badge_awarded_at===null,'availability does not award badge');
await as(4);const person=(await q('select dream_team_person($1,$2) v',[org,pid])).rows[0].v;check(person.application.status==='approved_for_placement'&&!JSON.stringify(person).includes('Synthetic response'),'ordinary Person summary contains no answers');await as(1);const alerts=(await q('select dream_team_alerts($1) v',[org])).rows[0].v;check(alerts.some(e=>e.event_type==='dream_team.application_submitted')&&alerts.some(e=>e.event_type==='dream_team.application_approved')&&alerts.some(e=>e.event_type==='dream_track.online_completed'),'authorized actionable alerts');
await as(2);await deny(()=>q("select dream_team_worker('claim','{}')"),'browser cannot claim worker job');await deny(()=>q('select * from private.dream_team_applications'),'direct private application access denied');await db.exec('reset role');await q("select set_config('request.jwt.claim.sub','',false)");await db.exec('set role service_role');let docId;for(let i=0;i<4;i++){const j=(await q("select dream_team_worker('claim','{}') v")).rows[0].v;if(!j)break;await q("select dream_team_worker('receipt',$1)",[JSON.stringify({id:j.id,lease:j.lease,status:'accepted',sha256:'a'.repeat(64)})]);}
await db.exec('reset role');docId=(await q('select id from private.protected_documents')).rows[0].id;await as(3);await deny(()=>q('select dream_team_document($1)',[docId]),'other applicant PDF denied');await as(5);await deny(()=>q('select dream_team_document($1)',[docId]),'summary-only staff PDF denied');await as(2);check((await q('select dream_team_document($1) v',[docId])).rows[0].v.path.endsWith('.pdf'),'own PDF path authorized and audited');await as(1);check((await q('select dream_team_document($1) v',[docId])).rows[0].v.path.endsWith('.pdf'),'restricted reviewer PDF authorized');await db.exec('reset role');check(!JSON.stringify((await q('select * from private.domain_events')).rows).includes('Synthetic response'),'events never contain restricted responses');
// Separate synthetic application proves the decline path and self-review guard.
await db.exec('reset role');await db.exec('alter table organization_people disable trigger user');const secondPerson=id(101);await q('insert into private.people(id)values($1)',[secondPerson]);await q("insert into organization_people(id,human_id,organization_id,first_name,last_name)values($1,$1,$2,'Synthetic','Second')",[secondPerson,org]);await db.exec('alter table organization_people enable trigger user');await q("insert into portal_account_links(organization_id,person_id,user_id,verification_note)values($1,$2,$3,'Reviewed synthetic association')",[org,secondPerson,id(3)]);
await as(3);let second=await rpc('get');second=await rpc('save',{revision:second.application.revision,answers});second=await rpc('submit',{revision:second.application.revision});await as(1);let declined=await admin('review',{id:second.application.id,revision:second.application.revision,status:'declined',note:'Private human decision'});check(declined.status==='declined'&&declined.declined_at,'decline records a durable decision');await as(3);check(!(JSON.stringify(await rpc('get')).includes('Private human decision')),'decline note stays private');await db.exec('reset role');
await q("insert into organization_staff_directory(organization_id,user_id,display_name)values($1,$2,'Synthetic dual-role learner')",[org,id(2)]);for(const key of ['dream_team.application.read','dream_team.application.manage','dream_team.application.restricted'])await q('insert into organization_staff_permissions(organization_id,user_id,permission)values($1,$2,$3)',[org,id(2),key]);await as(2);await assert.rejects(()=>admin('review',{id:a.id,revision:a.revision,status:'declined'}),/own application/);check(true,'reviewer privilege cannot approve or decline own application');await db.exec('reset role');
// Revocation takes effect on the next restricted read/download, without token refresh.
await q("delete from organization_staff_permissions where organization_id=$1 and user_id=$2 and permission='dream_team.application.restricted'",[org,id(1)]);await as(1);await deny(()=>admin('detail',{id:a.id}),'revoked reviewer cannot reopen restricted content');await deny(()=>q('select dream_team_document($1)',[docId]),'revoked reviewer cannot download');await db.exec('reset role');
// A learner who completed online coursework before this migration is eligible on next access.
await db.exec('alter table course_completions disable trigger dream_team_course_hook');const legacyE=(await q('insert into course_enrollments(course_id,user_id)values($1,$2)returning id',[cid,id(4)])).rows[0].id;await q('insert into course_completions(enrollment_id,online_completed_at)values($1,now())',[legacyE]);await db.exec('alter table course_completions enable trigger dream_team_course_hook');await as(4);let legacy=await rpc('get');check(legacy.available,'existing online completer receives eligibility on next access');await rpc('get');await db.exec('reset role');check((await q("select count(*)::int n from private.dream_team_jobs where application_id=$1",[legacy.application.id])).rows[0].n===1,'legacy eligibility email remains idempotent');await as(4);await rpc('withdraw');check((await rpc('get')).application.status==='withdrawn','explicit withdrawal retained');await deny(()=>rpc('save',{revision:99,answers}),'withdrawn application cannot be edited');await db.exec('reset role');
fs.writeFileSync(path.join(os.tmpdir(),'dream-team-synthetic-snapshot.json'),JSON.stringify((await q('select snapshot from private.dream_team_submissions where version=1 limit 1')).rows[0].snapshot));console.log(count+' Dream Team backend checks passed');await db.close();
