import os from 'node:os';import path from 'node:path';
import assert from 'node:assert/strict';import fs from 'node:fs';import {PDFDocument,rgb} from 'pdf-lib';import fontkit from '@pdf-lib/fontkit';import {applicationPdf} from '../../supabase/functions/_shared/dream-team-pdf.mjs';import {fontBytes,logoBytes} from '../../supabase/functions/_shared/dream-team-assets.mjs';import {createWorker} from '../../supabase/functions/dream-team-worker/handler.mjs';import {createDocuments} from '../../supabase/functions/dream-team-documents/handler.mjs';
const snapshot=JSON.parse(fs.readFileSync(path.join(os.tmpdir(),'dream-team-synthetic-snapshot.json')));const bytes=await applicationPdf(snapshot,{PDFDocument,rgb,fontkit,fontBytes,logoBytes});const doc=await PDFDocument.load(bytes);assert(doc.getPageCount()>=8);assert.equal(doc.getTitle(),'Champion Life Dream Team Application');fs.writeFileSync(path.join(os.tmpdir(),'dream-team-synthetic.pdf'),bytes);assert(!Buffer.from(bytes).includes(Buffer.from(snapshot.applicant_user_id)));console.log('PASS PDF generated from immutable 52-field snapshot with embedded signature and approved logo; '+doc.getPageCount()+' pages');
const url='https://bkbmjisprwmkptywtmih.supabase.co',workerSecret='synthetic-worker-secret-'.repeat(2),serviceKey='synthetic-service',anonKey='synthetic-public',origin='https://deploy-preview-2--championlifechurch.netlify.app';let count=0;
for(const kind of ['online_email','invite_email','pdf']){const calls=[];let claimed=false;const fetcher=async(u,o)=>{calls.push({u,o});if(u.endsWith('/dream_team_worker')){const b=JSON.parse(o.body);if(b.p_action==='claim'){if(claimed)return Response.json(null);claimed=true;return Response.json({id:'job',lease:'lease',kind,email:'synthetic@example.test',snapshot,object_path:'org/submission.pdf'});}return Response.json({recorded:true});}return Response.json({});};const worker=createWorker({url,serviceKey,anonKey,workerSecret,renderPdf:async()=>bytes,fetcher});const req=()=>new Request(url,{method:'POST',headers:{Authorization:'Bearer '+workerSecret}});assert.equal((await worker(new Request(url,{method:'POST'}))).status,403);assert.equal((await worker(req())).status,200);await worker(req());assert.equal(calls.filter(c=>c.u.includes('/auth/v1/otp')||c.u.includes('/storage/v1/object')).length,1);const receipt=calls.find(c=>JSON.parse(c.o.body instanceof Uint8Array?'{}':c.o.body).p_action==='receipt');assert.equal(JSON.parse(receipt.o.body).p_data.status,'accepted');if(kind!=='pdf'){const mail=calls.find(c=>c.u.includes('/auth/v1/otp'));assert.equal(JSON.parse(mail.o.body).create_user,false);assert.match(decodeURIComponent(mail.u),new RegExp('source='+ (kind==='online_email'?'online':'invitation')));}count++;}
let sent=false,unknown;const worker=createWorker({url,serviceKey,anonKey,workerSecret,renderPdf:async()=>bytes,fetcher:async(u,o)=>{if(u.includes('/otp')){sent=true;throw Error('Ambiguous transport failure')}const b=JSON.parse(o.body);if(b.p_action==='claim')return Response.json({id:'job',lease:'lease',kind:'online_email',email:'synthetic@example.test'});unknown=b.p_data.status;return Response.json({});}});assert.equal((await worker(new Request(url,{method:'POST',headers:{Authorization:'Bearer '+workerSecret}}))).status,502);assert(sent&&unknown==='unknown');count++;
for(const allowed of [false,true]){let storage=false;const handler=createDocuments({url,anonKey,serviceKey,fetcher:async(u)=>{if(u.endsWith('/auth/v1/user'))return Response.json({id:'synthetic'});if(u.endsWith('/dream_team_document'))return allowed?Response.json({path:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa/bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb.pdf'}):new Response('',{status:403});storage=true;return new Response(bytes);}});const result=await handler(new Request(url,{method:'POST',headers:{Origin:origin,Authorization:'Bearer synthetic','Content-Type':'application/json'},body:JSON.stringify({id:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'})}));assert.equal(result.status,allowed?200:403);assert.equal(storage,allowed);assert.match(result.headers.get('Cache-Control'),/no-store/);count++;}
assert.equal((await createWorker({url:'https://production.example',serviceKey,anonKey})(new Request(url,{method:'POST',headers:{Authorization:'Bearer '+workerSecret}}))).status,403);count++;
console.log('PASS '+count+' worker delivery, replay, ambiguous receipt, private download and acceptance-only scenarios');
