import os from 'node:os';import path from 'node:path';
import assert from 'node:assert/strict';import fs from 'node:fs';import {PDFDocument,rgb} from 'pdf-lib';import fontkit from '@pdf-lib/fontkit';import {applicationPdf,wrapPdfText} from '../../supabase/functions/_shared/dream-team-pdf.mjs';import {fontBytes,logoBytes} from '../../supabase/functions/_shared/dream-team-assets.mjs';import {createWorker} from '../../supabase/functions/dream-team-worker/handler.mjs';import {createDocuments} from '../../supabase/functions/dream-team-documents/handler.mjs';
const snapshot=JSON.parse(fs.readFileSync(path.join(os.tmpdir(),'dream-team-synthetic-snapshot.json')));const bytes=await applicationPdf(snapshot,{PDFDocument,rgb,fontkit,fontBytes,logoBytes});const doc=await PDFDocument.load(bytes);assert(doc.getPageCount()>=8);assert.equal(doc.getTitle(),'Champion Life Dream Team Application');fs.writeFileSync(path.join(os.tmpdir(),'dream-team-synthetic.pdf'),bytes);assert(!Buffer.from(bytes).includes(Buffer.from(snapshot.applicant_user_id)));console.log('PASS PDF generated from immutable 52-field snapshot with embedded signature and approved logo; '+doc.getPageCount()+' pages');
const url='https://bkbmjisprwmkptywtmih.supabase.co',workerSecret='synthetic-worker-secret-'.repeat(2),serviceKey='synthetic-service',anonKey='synthetic-public',origin='https://deploy-preview-2--championlifechurch.netlify.app';let count=0;
for(const kind of ['online_email','invite_email','pdf']){const calls=[];let claimed=false;const fetcher=async(u,o)=>{calls.push({u,o});if(u.endsWith('/dream_team_worker')){const b=JSON.parse(o.body);if(b.p_action==='claim'){if(claimed)return Response.json(null);claimed=true;return Response.json({id:'job',lease:'lease',kind,email:'synthetic@example.test',snapshot,object_path:'org/submission.pdf'});}return Response.json({recorded:true});}return Response.json({});};const worker=createWorker({url,serviceKey,anonKey,workerSecret,renderPdf:async()=>bytes,fetcher});const req=()=>new Request(url,{method:'POST',headers:{Authorization:'Bearer '+workerSecret}});assert.equal((await worker(new Request(url,{method:'POST'}))).status,403);assert.equal((await worker(req())).status,200);await worker(req());assert.equal(calls.filter(c=>c.u.includes('/auth/v1/otp')||c.u.includes('/storage/v1/object')).length,1);if(kind==='pdf'){const upload=calls.find(c=>c.u.includes('/storage/v1/object'));assert.equal(upload.o.headers['x-upsert'],'false');assert.equal(upload.o.headers['Content-Type'],'application/pdf');assert.deepEqual(upload.o.body,bytes);}
const receipt=calls.find(c=>JSON.parse(c.o.body instanceof Uint8Array?'{}':c.o.body).p_action==='receipt');assert.equal(JSON.parse(receipt.o.body).p_data.status,'accepted');if(kind==='pdf')assert.equal(JSON.parse(receipt.o.body).p_data.sha256,Buffer.from(await crypto.subtle.digest('SHA-256',bytes)).toString('hex'));if(kind!=='pdf'){const mail=calls.find(c=>c.u.includes('/auth/v1/otp'));assert.equal(JSON.parse(mail.o.body).create_user,false);assert.match(decodeURIComponent(mail.u),new RegExp('source='+ (kind==='online_email'?'online':'invitation')));}count++;}
let sent=false,unknown;const worker=createWorker({url,serviceKey,anonKey,workerSecret,renderPdf:async()=>bytes,fetcher:async(u,o)=>{if(u.includes('/otp')){sent=true;throw Error('Ambiguous transport failure')}const b=JSON.parse(o.body);if(b.p_action==='claim')return Response.json({id:'job',lease:'lease',kind:'online_email',email:'synthetic@example.test'});unknown=b.p_data.status;return Response.json({});}});assert.equal((await worker(new Request(url,{method:'POST',headers:{Authorization:'Bearer '+workerSecret}}))).status,502);assert(sent&&unknown==='unknown');count++;
for(const allowed of [false,true]){let storage=false;const handler=createDocuments({url,anonKey,serviceKey,fetcher:async(u)=>{if(u.endsWith('/auth/v1/user'))return Response.json({id:'synthetic'});if(u.endsWith('/dream_team_document'))return allowed?Response.json({path:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa/bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb.pdf'}):new Response('',{status:403});storage=true;return new Response(bytes);}});const result=await handler(new Request(url,{method:'POST',headers:{Origin:origin,Authorization:'Bearer synthetic','Content-Type':'application/json'},body:JSON.stringify({id:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'})}));assert.equal(result.status,allowed?200:403);assert.equal(storage,allowed);assert.match(result.headers.get('Cache-Control'),/no-store/);count++;}
assert.equal((await createWorker({url:'https://production.example',serviceKey,anonKey})(new Request(url,{method:'POST',headers:{Authorization:'Bearer '+workerSecret}}))).status,403);count++;
console.log('PASS '+count+' worker delivery, replay, ambiguous receipt, private download and acceptance-only scenarios');

// Layout regression: long unbroken text and astral Unicode must not disappear or overflow.
for(const text of ['A long answer '.repeat(800),'x'.repeat(10000),'🙂éΩ'.repeat(300)]){
 let calls=0;const measure=t=>{calls++;return Array.from(t).length;};
 const lines=wrapPdfText(text,measure,80);
 assert(lines.every(l=>Array.from(l).length<=80));
 assert.equal(lines.join('').replace(/\s/g,''),text.replace(/\s/g,''));
 assert(calls<text.length/2,'Avoid per-character growing-prefix measurements');
}
// Exercise all visible fields, multiline values, Unicode fallback, original UTF-8 attachment and signature.
const complex=structuredClone(snapshot);const field=complex.form.fields.find(f=>f.type==='textarea'&&f.controls.length);
complex.answers[field.id]={[field.controls[0].id]:'First line café Ω 🙂\nSecond line '+ 'unbroken'.repeat(180)};
const drawn=[],attached=[],stages=[];let signatureLines=0;
const fakeFont={getCharacterSet:()=>Array.from({length:256},(_,i)=>i),widthOfTextAtSize:(s,size)=>s.length*size*.5};
const fakePage=()=>({drawRectangle(){},drawImage(){},drawLine(){signatureLines++;},drawText(t){drawn.push(t)}});
const pages=[];const fakePDF={registerFontkit(){},embedFont:async()=>fakeFont,embedPng:async()=>({height:10,width:20}),addPage:()=>{const p=fakePage();pages.push(p);return p;},getPages:()=>pages,attach:async(b)=>attached.push(JSON.parse(new TextDecoder().decode(b))),setTitle(){},setAuthor(){},save:async()=>new Uint8Array([1])};
await applicationPdf(complex,{PDFDocument:{create:async()=>fakePDF},rgb:()=>0,fontkit,fontBytes,logoBytes,onStage:s=>stages.push(s)});
const printed=drawn.join(' ').replace(/\s/g,'');
for(const f of complex.form.fields.filter(f=>!f.hidden&&f.label))assert(printed.includes(f.label.replace(/\s/g,'')),f.id);
assert(printed.includes('[U+1F642]'));assert(printed.includes('[U+3A9]'));assert(signatureLines>0);assert(pages.length>=8);
assert.deepEqual(attached[0].fields.find(f=>f.prompt===field.label).answer,complex.answers[field.id]);
assert.equal(attached[0].fields.length,51);assert(!JSON.stringify(attached).includes(complex.applicant_user_id));
assert.deepEqual(stages,['pdf_start','assets_ready','content_ready','attachment_ready','pdf_saved']);
console.log('PASS bounded layout measurements, long/multiline/Unicode content, all visible prompts, exact attachment, signature and stage telemetry');
