import {PGlite} from '@electric-sql/pglite';
import {readFileSync,readdirSync,writeFileSync} from 'node:fs';
import {createHash,randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
const db=new PGlite(),q=(s,a=[])=>db.query(s,a);let count=0;
const check=(v,m)=>{assert.ok(v,m);count++;console.log('PASS '+m)},deny=async(f,m)=>{await assert.rejects(f);check(true,m)};
await db.exec(readFileSync(new URL('fixtures/supabase-test-bootstrap.sql',import.meta.url),'utf8'));
await db.exec(readFileSync(new URL('../../supabase/bootstrap/automatic-rls.sql',import.meta.url),'utf8'));
const files=readdirSync(new URL('../../supabase/migrations',import.meta.url)).sort();
for(const f of files)try{await db.exec(readFileSync(new URL('../../supabase/migrations/'+f,import.meta.url),'utf8'))}catch(e){console.error(f,e.message);process.exit(1)}
if(process.env.DREAM_BASELINE==='1'){
 const hash=s=>createHash('sha256').update(s).digest('hex');
 const baseline={migrations:files.map(file=>({file,sha256:hash(readFileSync(new URL('../../supabase/migrations/'+file,import.meta.url)))})),tables:(await q("select relname,relrowsecurity from pg_class where relnamespace='public'::regnamespace and relkind='r' order by relname")).rows,policies:(await q("select schemaname,tablename,policyname,roles,cmd,qual,with_check from pg_policies where schemaname in ('public','private')")).rows,functions:(await q("select n.nspname as schema,p.proname as name,pg_get_function_identity_arguments(p.oid) as args,pg_get_functiondef(p.oid) as definition from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private') and p.prokind='f'")).rows.map(({definition,...r})=>({...r,sha256:hash(definition.replace(/\s+/g,' ').trim())}))};
 writeFileSync(new URL('fixtures/migration-baseline.json',import.meta.url),JSON.stringify(baseline,null,2)+'\n');
}
const id=n=>`40000000-0000-4000-8000-${String(n).padStart(12,'0')}`,org=(await q("select id from organizations where slug='champion-life'")).rows[0].id,other=(await q("select id from organizations where slug='sowgo'")).rows[0].id,cid=(await q("select id from courses where slug='dream-track'")).rows[0].id;
for(let n=1;n<=5;n++)await q('insert into auth.users(id,email,email_confirmed_at)values($1,$2,$3)',[id(n),`dream-${n}@example.test`,n===5?null:new Date()]);
await q("insert into organization_staff_directory(organization_id,user_id,display_name)values($1,$2,'Synthetic manager')",[org,id(1)]);
await q("insert into organization_staff_permissions(organization_id,user_id,permission)values($1,$2,'courses.manage')",[org,id(1)]);
const as=async(n)=>{await db.exec('reset role');await q("select set_config('request.jwt.claim.sub',$1,false)",[n?id(n):'']);await db.exec('set role '+(n?'authenticated':'anon'))};
const learner=async(a,d={})=>(await q('select dream_track($1,$2) v',[a,JSON.stringify(d)])).rows[0].v;
const admin=async(a,d={},o=org)=>(await q('select dream_track_admin($1,$2,$3) v',[o,a,JSON.stringify(d)])).rows[0].v;
const bank=JSON.parse(readFileSync(new URL('fixtures/dream-track-bank.json',import.meta.url)));
const installed=(await q('select lesson_number,question_number,prompt,correct_answer,accepted_variants,review_start,review_end from course_questions order by lesson_number,question_number')).rows;
assert.deepEqual(installed,bank.map(x=>({lesson_number:x.lesson,question_number:x.number,prompt:x.prompt,correct_answer:x.answer,accepted_variants:x.variants,review_start:x.review_start,review_end:x.review_end})));check(installed.length===140,'exact 140 approved prompts, answers, variants and times');
check((await q('select count(*)::int n from course_lessons')).rows[0].n===7,'seven reused videos, no duplicates');
await as(0);await deny(()=>learner('dashboard'),'anonymous denied');await as(5);await deny(()=>learner('dashboard'),'unverified user denied');await as(2);await deny(()=>admin('list'),'non-manager denied');await deny(()=>q('select * from course_questions'),'direct answer keys denied');await deny(()=>q('select * from course_attempts'),'direct history denied');await deny(()=>q('insert into course_enrollments(user_id,course_id)values($1,$2)',[id(2),cid]),'direct gate bypass denied');await deny(()=>learner('lesson',{lesson:1}),'unenrolled denied');
await as(1);await deny(()=>admin('list',{},other),'cross-org manager denied');await admin('code',{code:'synthetic-dream-code',active:true});let cfg=await admin('list');check(cfg.code_exists&&cfg.code_active&&!JSON.stringify(cfg).includes('synthetic-dream-code'),'code exists without plaintext disclosure');
await as(2);check((await learner('claim_code',{code:'wrong'})).error,'invalid code rejected');let s=await learner('claim_code',{code:'synthetic-dream-code'});const eid=s.enrollment_id;check(s.enrolled&&s.lessons[0].unlocked&&!s.lessons[1].unlocked,'code enrolls and only lesson one unlocked');check((await learner('claim_code',{code:'synthetic-dream-code'})).enrollment_id===eid,'code repeat idempotent');await deny(()=>learner('lesson',{lesson:2}),'locked lesson server enforced');
await as(1);await admin('code',{code:'different-dream-code'});await as(2);check((await learner('dashboard')).enrolled,'code rotation retains enrollment');
await as(3);for(let i=0;i<11;i++)s=await learner('claim_code',{code:'bad'});check(s.error.includes('15 minutes'),'guess rate limit persists without exception rollback');
await as(2);const all=l=>Object.fromEntries(bank.filter(x=>x.lesson===l).map(x=>[x.number,x.answer]));
await learner('save',{lesson:1,answers:{1:'Champion'},notes:'Synthetic notes'});s=await learner('lesson',{lesson:1});check(s.notes==='Synthetic notes'&&s.questions[0].answer==='Champion','cloud draft and notes restore');
await deny(()=>learner('save',{lesson:1,answers:{1:{unexpected:'object'}}}),'non-text answer rejected');
let answers=all(1);for(let i=15;i<=20;i++)answers[i]='wrong';let req=randomUUID();s=await learner('submit',{lesson:1,answers,request_id:req});check(s.lessons[0].mastered===14,'14 correct preserved');check(s.questions[14].attempted&&!s.questions[14].mastered&&s.questions[14].review_start===942,'wrong answer has approved review time');check(!JSON.stringify(s).includes('correct_answer')&&!JSON.stringify(s).includes('accepted_variants'),'no canonical answer reveal');
await learner('submit',{lesson:1,answers,request_id:req});await db.exec('reset role');check((await q('select count(*)::int n from course_attempts')).rows[0].n===20,'submission replay no duplicate history');
async function watch(percent,lesson=1){await db.exec('reset role');await q("update lesson_progress set watched_ranges=nummultirange(numrange(0,((select duration_seconds from course_lessons where course_id=$1 and lesson_number=$3)*$4::numeric),'[)')) where course_id=$1 and user_id=$2 and lesson_number=$3",[cid,id(2),lesson,percent]);await as(2)}
await watch(.95);s=await learner('submit',{lesson:1,answers:{15:all(1)[15],1:'wrong'},request_id:randomUUID()});check(s.lessons[0].mastered===15&&!s.lessons[1].unlocked,'95% and 15 remains locked; mastered answer not overwritten');
await watch(.949);s=await learner('submit',{lesson:1,answers:all(1),request_id:randomUUID()});check(s.lessons[0].mastered===20&&!s.lessons[1].unlocked,'94.9% and 20 remains locked');
// Exact boundary evaluated directly with a divisible synthetic duration, then restore verified metadata.
await db.exec('reset role');await q('update course_lessons set duration_seconds=2000 where course_id=$1 and lesson_number=1',[cid]);await watch(.95);s=await learner('save',{lesson:1});check(s.lessons[1].unlocked,'95% with mastered score passes');await db.exec('reset role');await q('update course_lessons set duration_seconds=1925 where course_id=$1 and lesson_number=1',[cid]);await as(2);
check((await q('update lesson_progress set status=\'completed\' where course_id=$1 returning id',[cid])).rows.length===0,'direct progress bypass cannot match protected row');
// A seek-to-end never becomes a watched segment.
await learner('lesson',{lesson:2});let w=await learner('watch_start',{lesson:2,position:0});s=await learner('watch_tick',{lesson:2,position:4350,watch_token:w.watch_token});check(s.lessons[1].watched_percent===0,'seeking directly to end earns no watch credit');
await db.exec('reset role');await q("update lesson_progress set watch_at=clock_timestamp()-interval '5 seconds',watch_anchor=0 where user_id=$1 and course_id=$2 and lesson_number=2",[id(2),cid]);await as(2);s=await learner('watch_tick',{lesson:2,position:5,watch_token:w.watch_token});check(s.lessons[1].watched_percent>0&&s.lessons[1].resume_seconds===5,'bounded continuous playback saves segments and resume');
const old=w;w=await learner('watch_start',{lesson:2,position:5});await deny(()=>learner('watch_tick',{lesson:2,position:10,watch_token:old.watch_token}),'old playback session rejected');await deny(()=>learner('watch_tick',{lesson:2,position:-1,watch_token:w.watch_token}),'out-of-bounds watch denied');
for(let l=2;l<=7;l++){await learner('lesson',{lesson:l});await watch(1,l);const a=Object.fromEntries(Object.entries(all(l)).slice(0,16));for(let i=17;i<=20;i++)a[i]='miss';s=await learner('submit',{lesson:l,answers:a,request_id:randomUUID()});check(s.lessons[l-1].mastered===16&&s.lessons[l-1].status==='completed',`lesson ${l} passes at 16 with four misses retained`)}
check(s.status==='ONLINE COURSEWORK COMPLETE – FINAL MEETING REQUIRED'&&!s.completion.badge_awarded_at,'online complete has no badge');await deny(()=>admin('meeting',{enrollment_id:eid,revision:1,complete:true}),'learner cannot mark meeting');
await as(4);s=await learner('dashboard');check(!s.enrolled&&s.lessons.every(l=>l.mastered===0),'other user cannot inherit progress');await deny(()=>learner('lesson',{lesson:1,user_id:id(2)}),'spoofed user ignored and unenrolled refused');
await as(1);let d=await admin('detail',{enrollment_id:eid});check(d.attempts.length===146&&d.lessons[0].mastered===20,'immutable original plus missed-only retry history');d=await admin('meeting',{enrollment_id:eid,revision:d.completion.revision,complete:true,note:'Synthetic meeting'});check(d.status==='Dream Track Completed'&&d.completion.meeting_completed_by===id(1),'manager records meeting and durable badge');await as(2);const own=await learner('dashboard');check(!('meeting_note' in own.completion)&&!('meeting_completed_by' in own.completion)&&!('person_id' in own.completion),'learner completion excludes private staff note and identity fields');await as(1);const awarded=d.completion.badge_awarded_at;d=await admin('meeting',{enrollment_id:eid,revision:d.completion.revision,complete:true});check(d.completion.badge_awarded_at===awarded,'repeated meeting idempotent badge');await deny(()=>admin('meeting',{enrollment_id:eid,revision:1,complete:false}),'stale meeting revision rejected');d=await admin('meeting',{enrollment_id:eid,revision:d.completion.revision,complete:false,note:'Correction'});check(d.status.includes('FINAL MEETING')&&d.completion.badge_revoked_at&&d.history.some(x=>x.metadata.note==='Correction'),'reversal revokes badge and preserves audit');d=await admin('meeting',{enrollment_id:eid,revision:d.completion.revision,complete:true});check(d.status==='Dream Track Completed'&&d.completion.badge_awarded_at===awarded,'re-completion safely reactivates one badge');
let inv=await admin('invite',{name:'Existing synthetic',email:'dream-4@example.test'});check(inv.token.length===64&&inv.status==='pending','existing account invitation created without duplicate account');await as(2);await deny(()=>learner('claim_invite',{token:inv.token}),'wrong verified account cannot claim');await as(5);await deny(()=>learner('claim_invite',{token:inv.token}),'unverified email denied');await as(4);s=await learner('claim_invite',{token:inv.token});check(s.enrolled,'matching verified invitation recipient enrolls without code');check((await learner('claim_invite',{token:inv.token})).enrollment_id===s.enrollment_id,'same recipient acceptance idempotent');
await as(1);const make=()=>admin('invite',{email:'dream-3@example.test'});inv=await make();await admin('cancel',{invite_id:inv.id});await as(3);await deny(()=>learner('claim_invite',{token:inv.token}),'cancelled invitation rejected');await as(1);inv=await make();await db.exec('reset role');await q("update course_invites set expires_at=now()-interval '1 second' where id=$1",[inv.id]);await as(3);await deny(()=>learner('claim_invite',{token:inv.token}),'expired invitation rejected');await as(1);inv=await make();await deny(()=>admin('resend',{invite_id:inv.id}),'resend rate bounded');await db.exec('reset role');await q("update course_invites set invited_at=now()-interval '2 minutes' where id=$1",[inv.id]);await as(1);const replacement=await admin('resend',{invite_id:inv.id});await as(3);await deny(()=>learner('claim_invite',{token:inv.token}),'resend invalidates previous token');
await as(1);await admin('send_unavailable',{invite_id:replacement.id,token:replacement.token});check((await admin('list')).invites.find(x=>x.id===replacement.id).status==='failed','delivery unavailable never falsely sent');await deny(()=>q('select course_invite_delivery($1,$2,true)',[replacement.id,replacement.delivery_id]),'browser cannot forge provider sent receipt');await db.exec('reset role');await db.exec('set role service_role');await q('select course_invite_delivery($1,$2,true)',[replacement.id,replacement.delivery_id]);await as(3);s=await learner('claim_pending');check(s.enrolled,'Auth email verified recipient automatically resumes provider-accepted invite');
await as(1);inv=await admin('invite',{name:'New synthetic',email:'new-dream@example.test'});await db.exec('reset role');check((await q("select count(*)::int n from auth.users where email='new-dream@example.test'")).rows[0].n===0,'invitation does not create account or silently link contact');check(!(await q('select token_hash from course_invites where id=$1',[inv.id])).rows[0].token_hash.includes(inv.token),'raw token not stored');await q("insert into auth.users(id,email,email_confirmed_at)values($1,'new-dream@example.test',now())",[id(6)]);await as(6);check((await learner('claim_invite',{token:inv.token})).enrolled,'newly authenticated recipient claims');
await db.exec('reset role');await deny(()=>q("update course_attempts set correct=true"),'attempts immutable even privileged accidental update');await deny(()=>q('delete from course_audit'),'audit immutable');check((await q('select count(*)::int n from organization_staff_permissions')).rows[0].n===1,'course enrollment and badge confer no staff permissions');check((await q('select count(*)::int n from portal_account_links')).rows[0].n===0,'no portal/Person identity merge');
console.log(`${count} Dream Track backend checks passed`);await db.close();
