-- Isolated acceptance only. All synthetic identities, grants and events roll back.
begin;
do $test$
declare org uuid:=gen_random_uuid(); other_org uuid:=gen_random_uuid(); manager uuid:=gen_random_uuid(); scoped uuid:=gen_random_uuid(); member uuid:=gen_random_uuid();
 dept uuid; other_dept uuid; contact uuid; loc jsonb; label jsonb; series jsonb; recurring jsonb; payload jsonb; result jsonb; occurrence uuid; original_id uuid; passed integer:=0; n integer;
begin
 insert into public.organizations(id,slug,name,kind) values(org,'synthetic-events-'||org,'Synthetic events','church'),(other_org,'synthetic-events-'||other_org,'Synthetic other','ministry');
 insert into public.event_settings(organization_id,timezone) values(org,'America/Chicago'),(other_org,'UTC');
 insert into auth.users(id,email,email_confirmed_at,is_anonymous) select x,'events-'||x||'@example.test',now(),false from unnest(array[manager,scoped,member])x;
 insert into public.organization_staff_directory(organization_id,user_id,display_name) values(org,manager,'Synthetic manager'),(org,scoped,'Synthetic scoped manager');
 insert into public.organization_staff_permissions(organization_id,user_id,permission) select org,manager,k from unnest(array['events.manage','tags.manage','tags.read','people.read','people.create'])k;
 perform set_config('request.jwt.claim.sub',manager::text,true);perform set_config('request.jwt.claims',jsonb_build_object('sub',manager,'role','authenticated')::text,true);
 insert into public.organization_departments(organization_id,name) values(org,'Synthetic department') returning id into dept;
 insert into public.organization_departments(organization_id,name) values(org,'Other synthetic department') returning id into other_dept;
 insert into public.organization_staff_permissions(organization_id,user_id,permission,department_ids) values(org,scoped,'events.manage',array[dept]);
 insert into public.organization_people(organization_id,first_name,last_name,user_id) values(org,'Synthetic','Member',member) returning id into contact;
 insert into public.portal_account_links(organization_id,person_id,user_id,verification_note) values(org,contact,member,'Synthetic transaction only');
 insert into public.person_organization_relationships(organization_id,person_id,relationship) values(org,contact,'member');
 execute 'set local role authenticated';
 loc:=public.events_workspace(org,'location',jsonb_build_object('name','Synthetic hall','timezone','America/Chicago','internal_notes','PRIVATE_LOCATION'));
 label:=public.events_workspace(org,'label',jsonb_build_object('name','Synthetic audience','kind','audience'));
 payload:=jsonb_build_object('title','Synthetic event','local_start',(current_date+1)::text||'T10:00','local_end',(current_date+1)::text||'T11:00','visibility','public','department_id',dept,'location_id',loc->>'id','audience_ids',jsonb_build_array(label->>'id'),'internal_notes','PRIVATE_SERIES','contact_name','PRIVATE_CONTACT');
 series:=public.events_workspace(org,'save',payload);if series->>'status'<>'draft' then raise exception 'Draft failed';end if;passed:=passed+1;
 result:=public.events_workspace(org,'detail',jsonb_build_object('id',series->>'id'));original_id:=(result->'occurrences'->0->>'id')::uuid;
 if jsonb_array_length(result->'occurrences')<>1 then raise exception 'One-time failed';end if;passed:=passed+1;
 result:=public.events_workspace(org,'detail',jsonb_build_object('id',series->>'id'));if result->'occurrences'->0->>'id'<>original_id::text then raise exception 'Idempotence failed';end if;passed:=passed+1;
 recurring:=public.events_workspace(org,'save',payload||jsonb_build_object('frequency','daily','occurrence_count',3));
 result:=public.events_workspace(org,'detail',jsonb_build_object('id',recurring->>'id'));if jsonb_array_length(result->'occurrences')<>3 then raise exception 'Count failed';end if;passed:=passed+1;
 occurrence:=(result->'occurrences'->0->>'id')::uuid;
 perform public.events_workspace(org,'exception',jsonb_build_object('id',recurring->>'id','series_revision',1,'occurrence_id',occurrence,'cancelled',true));
 result:=public.events_workspace(org,'detail',jsonb_build_object('id',recurring->>'id'));if not (result->'occurrences'->0->'exception'->>'cancelled')::boolean then raise exception 'Cancellation failed';end if;passed:=passed+1;
 recurring:=public.events_workspace(org,'save',payload||jsonb_build_object('id',recurring->>'id','revision',2,'frequency','weekly'));
 result:=public.events_workspace(org,'detail',jsonb_build_object('id',recurring->>'id'));if not (result->'occurrences'->0->'exception'->>'cancelled')::boolean then raise exception 'Exception preservation failed';end if;passed:=passed+1;
 series:=public.events_workspace(org,'save',payload||jsonb_build_object('id',series->>'id','revision',1,'status','published'));
 execute 'reset role';perform set_config('request.jwt.claim.sub','',true);perform set_config('request.jwt.claims','{"role":"anon"}',true);execute 'set local role anon';
 result:=public.events_catalog('synthetic-events-'||org,current_date,current_date+60);
 if jsonb_array_length(result->'events')<>1 then raise exception 'Public lifecycle failed';end if;passed:=passed+1;
 if result::text like '%PRIVATE%' or result::text like '%internal_notes%' or result::text like '%revision%' then raise exception 'Private fields leaked';end if;passed:=passed+1;
 begin perform 1 from public.event_series;raise exception 'Raw table leaked';exception when insufficient_privilege then passed:=passed+1;end;
 begin perform public.events_workspace(org,'list');raise exception 'Anon admin allowed';exception when insufficient_privilege then passed:=passed+1;end;
 begin perform private.event_materialize((series->>'id')::uuid,current_date,current_date+10);raise exception 'Internal function allowed';exception when insufficient_privilege then passed:=passed+1;end;
 execute 'reset role';perform set_config('request.jwt.claim.sub',member::text,true);perform set_config('request.jwt.claims',jsonb_build_object('sub',member,'role','authenticated')::text,true);execute 'set local role authenticated';
 begin perform public.events_workspace(org,'save',payload);raise exception 'Member editing allowed';exception when insufficient_privilege then passed:=passed+1;end;
 execute 'reset role';perform set_config('request.jwt.claim.sub',scoped::text,true);perform set_config('request.jwt.claims',jsonb_build_object('sub',scoped,'role','authenticated')::text,true);execute 'set local role authenticated';
 perform public.events_workspace(org,'save',payload);passed:=passed+1;
 begin perform public.events_workspace(org,'save',payload||jsonb_build_object('department_id',other_dept));raise exception 'Cross department allowed';exception when insufficient_privilege then passed:=passed+1;end;
 begin perform public.events_workspace(org,'save',payload||jsonb_build_object('department_id',null));raise exception 'Organization-wide allowed';exception when insufficient_privilege then passed:=passed+1;end;
 begin perform public.events_workspace(other_org,'list');raise exception 'Cross org allowed';exception when insufficient_privilege then passed:=passed+1;end;
 begin perform public.events_workspace(org,'location',jsonb_build_object('name','Unauthorized room'));raise exception 'Scoped config allowed';exception when insufficient_privilege then passed:=passed+1;end;
 execute 'reset role';perform set_config('request.jwt.claim.sub',manager::text,true);perform set_config('request.jwt.claims',jsonb_build_object('sub',manager,'role','authenticated')::text,true);execute 'set local role authenticated';
 result:=public.events_workspace(org,'detail',jsonb_build_object('id',series->>'id'));if (result->>'conflicts')::int<1 then raise exception 'Conflict warning failed';end if;passed:=passed+1;
 -- A public projection of member visibility still requires reviewed member eligibility.
 series:=public.events_workspace(org,'save',payload||jsonb_build_object('id',series->>'id','revision',2,'status','published','visibility','member'));
 execute 'reset role';perform set_config('request.jwt.claim.sub',member::text,true);perform set_config('request.jwt.claims',jsonb_build_object('sub',member,'role','authenticated')::text,true);execute 'set local role authenticated';
 result:=public.events_catalog('synthetic-events-'||org,current_date,current_date+60);if jsonb_array_length(result->'events')<>1 then raise exception 'Member projection failed';end if;passed:=passed+1;
 execute 'reset role';perform set_config('request.jwt.claim.sub','',true);perform set_config('request.jwt.claims','{"role":"anon"}',true);execute 'set local role anon';
 result:=public.events_catalog('synthetic-events-'||org,current_date,current_date+60);if jsonb_array_length(result->'events')<>0 then raise exception 'Member event leaked';end if;passed:=passed+1;
 execute 'reset role';
 select count(*) into n from private.event_slots(jsonb_populate_record(null::public.event_series,jsonb_build_object('local_start','2026-03-07T10:00','local_end','2026-03-07T11:00','timezone','America/Chicago','frequency','daily','interval_n',1,'occurrence_count',3)),date '2026-03-07',date '2026-03-10')x where extract(hour from x.starts_at at time zone 'America/Chicago')=10;
 if n<>3 then raise exception 'DST local time failed';end if;passed:=passed+1;
 select count(*) into n from private.event_slots(jsonb_populate_record(null::public.event_series,jsonb_build_object('local_start','2026-01-01T10:00','local_end','2026-01-01T11:00','timezone','America/Chicago','frequency','monthly_weekday','interval_n',1,'ordinal',-1,'weekday',0)),date '2026-01-01',date '2026-02-01')x where x.slot_date=date '2026-01-25';
 if n<>1 then raise exception 'Last weekday failed';end if;passed:=passed+1;
 if passed<>22 then raise exception 'Expected 22 assertions, got %',passed;end if;
end $test$;
rollback;
select 'PASS: 22 rollback-only Events acceptance assertions; no synthetic data retained' as result;
