import {PGlite} from '@electric-sql/pglite';
import {readFileSync,readdirSync} from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite(),root=new URL('../../',import.meta.url);let count=0;
const q=(s,a=[])=>db.query(s,a),check=(v,m)=>{assert.ok(v,m);count++;console.log('PASS '+m);};
const deny=async(f,m)=>{await assert.rejects(f);check(true,m);};
await db.exec(readFileSync(new URL('fixtures/supabase-test-bootstrap.sql',import.meta.url),'utf8'));
await db.exec(readFileSync(new URL('supabase/bootstrap/automatic-rls.sql',root),'utf8'));
for(const f of readdirSync(new URL('supabase/migrations',root)).filter(f=>f.endsWith('.sql')).sort())await db.exec(readFileSync(new URL('supabase/migrations/'+f,root),'utf8'));
const id=n=>`20000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const org=(await q("select id from organizations where slug='champion-life'")).rows[0].id,other=(await q("select id from organizations where slug='sowgo'")).rows[0].id;
for(let n=1;n<=5;n++){await q('insert into auth.users(id,email,email_confirmed_at) values($1,$2,now())',[id(n),`event-${n}@example.test`]);await q("insert into organization_staff_directory(organization_id,user_id,display_name) values($1,$2,'Synthetic')",[org,id(n)]);}
await db.exec('alter table organization_departments disable trigger user');
for(let n=1;n<=2;n++)await q('insert into organization_departments(id,organization_id,name) values($1,$2,$3)',[id(10+n),org,'Synthetic '+n]);
await db.exec('alter table organization_departments enable trigger user');
for(const [n,key,scope] of [[1,'events.manage',null],[2,'events.manage',[id(11)]],[3,'events.view',null],[4,'finance.read',null]])await q('insert into organization_staff_permissions(organization_id,user_id,permission,department_ids) values($1,$2,$3,$4)',[org,id(n),key,scope]);
const as=async(n,role='authenticated')=>{await db.exec('reset role');await q("select set_config('request.jwt.claim.sub',$1,false)",[n?id(n):'']);await db.exec('set role '+role);};
const call=async(a,d={},o=org)=>(await q('select public.events_workspace($1,$2,$3) v',[o,a,JSON.stringify(d)])).rows[0].v;
const today=(await q('select current_date::text d')).rows[0].d;
const catalog=async(f={},from=today,to=addDays(today,90))=>(await q('select public.events_catalog($1,$2,$3,$4) v',['champion-life',from,to,JSON.stringify(f)])).rows[0].v;
function addDays(d,n){return new Date(Date.parse(d+'T12:00Z')+n*864e5).toISOString().slice(0,10);}
await as(1);let ctx=await call('context');check(ctx.timezone==='America/Chicago','tenant default timezone');
let location=await call('location',{name:'Synthetic Hall',room:'A',timezone:'America/Chicago',internal_notes:'PRIVATE LOCATION'});
let audience=await call('label',{kind:'audience',name:'Synthetic audience'}),type=await call('label',{kind:'type',name:'Synthetic type'});
const base={title:'Synthetic Event',local_start:today+'T10:00',local_end:today+'T11:00',department_id:null,location_id:location.id,visibility:'public',audience_ids:[audience.id],type_id:type.id,internal_notes:'PRIVATE SERIES',contact_name:'PRIVATE CONTACT'};
const save=(data={})=>{data={...data};if(data.id){delete data.organization_id;delete data.created_at;delete data.updated_at;}return call('save',{...base,...data});};
let e=await save();check(e.status==='draft','draft creation');
const detail=async(s,from,to)=>(await call('detail',{id:s.id,...(from?{from,to}: {})}));
let d=await detail(e);check(d.occurrences.filter(x=>x.scheduled).length===1,'one-time materialized');
let multi=await save({local_end:addDays(today,2)+'T11:00'});check((await detail(multi)).occurrences[0].ends_at.startsWith(addDays(today,2)),'multi-day');
// Pure generator exercises dates independently from the wall-clock public window.
async function slots(p,from='2026-01-01',to='2026-12-31'){
 await db.exec('reset role');const full={...base,timezone:'America/Chicago',frequency:'once',interval_n:1,weekdays:[],local_start:'2026-01-01T10:00',local_end:'2026-01-01T11:00',...p};
 const rows=(await q('select * from private.event_slots(jsonb_populate_record(null::public.event_series,$1),$2,$3)',[JSON.stringify(full),from,to])).rows;await as(1);return rows.map(x=>({...x,slot_date:typeof x.slot_date==='string'?x.slot_date:new Date(x.slot_date).toISOString().slice(0,10),starts_at:new Date(x.starts_at).toISOString(),ends_at:new Date(x.ends_at).toISOString()}));
}
check((await slots({frequency:'daily',occurrence_count:4})).length===4,'daily and count');
check((await slots({frequency:'weekly',weekdays:[4],occurrence_count:4})).length===4,'weekly');
let ss=await slots({frequency:'weekly',interval_n:2,weekdays:[4],occurrence_count:3});check(ss[1].slot_date==='2026-01-15','every two weeks');
check((await slots({frequency:'weekly',weekdays:[1,3,5],occurrence_count:6})).length===6,'selected weekdays');
check((await slots({frequency:'monthly_date',local_start:'2026-01-31T10:00',local_end:'2026-01-31T11:00'})).length===7,'monthly date skips nonexistent dates');
for(const [ordinal,weekday,expected] of [[1,1,'2026-01-05'],[2,6,'2026-01-10'],[3,4,'2026-01-15'],[4,5,'2026-01-23'],[-1,0,'2026-01-25']])check((await slots({frequency:'monthly_weekday',ordinal,weekday}))[0].slot_date===expected,`ordinal ${ordinal} weekday`);
check((await slots({frequency:'yearly'})).length===1,'yearly');
check((await slots({frequency:'yearly',local_start:'2024-02-29T10:00',local_end:'2024-02-29T11:00'},'2025-01-01','2025-12-31')).length===0,'leap yearly skips non-leap year');
check((await slots({frequency:'daily',until_date:'2026-01-03'})).length===3,'inclusive end date');
ss=await slots({frequency:'daily',local_start:'2026-03-07T10:00',local_end:'2026-03-07T11:00',occurrence_count:3});check(ss[0].starts_at.includes('16:00')&&ss[1].starts_at.includes('15:00'),'spring DST preserves local 10 AM');
ss=await slots({frequency:'daily',local_start:'2026-10-31T10:00',local_end:'2026-10-31T11:00',occurrence_count:3});check(ss[0].starts_at.includes('15:00')&&ss[1].starts_at.includes('16:00'),'fall DST preserves local 10 AM');
await deny(()=>slots({frequency:'daily'},'2026-01-01','2028-01-01'),'bounded generator');await as(1);
const oldId=d.occurrences[0].id;d=await detail(e);check(d.occurrences[0].id===oldId,'idempotent generation stable identity');
let recurring=await save({frequency:'daily',occurrence_count:3});let rd=await detail(recurring);
await call('exception',{id:recurring.id,series_revision:recurring.revision,occurrence_id:rd.occurrences[0].id,cancelled:true});
rd=await detail(recurring);recurring=rd.series;check(rd.occurrences[0].exception.cancelled,'cancel single occurrence');
await call('exception',{id:recurring.id,series_revision:recurring.revision,occurrence_id:rd.occurrences[1].id,starts_at:addDays(today,5)+'T19:00Z',ends_at:addDays(today,5)+'T20:00Z',location_override:true,custom_location:'Synthetic Outdoors',note:'PRIVATE EXCEPTION'});
rd=await detail(recurring);recurring=rd.series;check(new Date(rd.occurrences[1].exception.starts_at).toISOString().includes('19:00'),'move/time exception');check(rd.occurrences[1].exception.custom_location==='Synthetic Outdoors','custom location exception');
recurring=await save({...recurring,title:'Edited series'});rd=await detail(recurring);check(rd.occurrences[0].exception.cancelled&&rd.occurrences[1].exception.note==='PRIVATE EXCEPTION','series edit preserves exceptions');
recurring=await save({...recurring,frequency:'weekly',weekdays:[]});rd=await detail(recurring);check(rd.occurrences.some(x=>!x.scheduled&&x.exception),'removed slots retain explicit exceptions');
await deny(()=>save({...recurring,revision:1}),'stale editor denied');
await deny(()=>call('exception',{id:recurring.id,series_revision:1,occurrence_id:rd.occurrences[0].id}),'stale exception series denied');
await deny(()=>save({organization_id:other}),'org reassignment rejected');
await as(0,'anon');await deny(()=>call('list'),'anon admin denied');await deny(()=>q('select * from event_series'),'anon raw table denied');check((await catalog()).events.length===0,'drafts hidden publicly');
await as(5);await deny(()=>save(),'ordinary user denied');await as(3);await deny(()=>save(),'viewer cannot edit');check((await call('list')).length>=3,'viewer can view staff records');
await as(4);await deny(()=>call('list'),'finance unrelated to events');
await as(2);let scoped=await save({department_id:id(11)});check(scoped.department_id===id(11),'scoped manager creates owned event');
await deny(()=>save({department_id:id(12)}),'other department denied');await deny(()=>save(),'organization ownership denied to scoped manager');await deny(()=>call('detail',{id:e.id}),'out-of-scope detail denied');await deny(()=>call('list',{},other),'cross-org denied');await deny(()=>call('location',{name:'No'}),'scoped manager cannot edit shared locations');await deny(()=>save({...scoped,department_id:id(12)}),'cannot move into unauthorized department');
await as(1);e=await save({...e,status:'submitted'});check(e.status==='submitted','submit');e=await save({...e,status:'approved'});check(e.status==='approved','approve');e=await save({...e,status:'published'});check(e.status==='published','publish');
let staff=await save({visibility:'staff'});staff=await save({...staff,status:'published'});let hidden=await save({visibility:'hidden'});hidden=await save({...hidden,status:'published'});let member=await save({visibility:'member'});member=await save({...member,status:'published'});
await as(0,'anon');let c=await catalog();check(c.events.length===1&&c.events[0].id===e.id,'anon published public only');check(!JSON.stringify(c).includes('PRIVATE')&&!JSON.stringify(c).includes('internal_notes')&&!JSON.stringify(c).includes('revision'),'safe projection excludes internal fields');check((await catalog({id:hidden.id})).events.length===0,'guessed hidden UUID denied');check((await catalog({audience_id:audience.id,type_id:type.id})).events.length===1,'combined filters');check((await catalog({department_id:id(11)})).events.length===0,'department filter');
await deny(()=>q('select private.event_materialize($1,$2,$3)',[e.id,today,addDays(today,1)]),'internal materializer not callable');
await deny(()=>catalog({},today,addDays(today,100)),'public range bounded');
await as(5);check((await catalog()).events.length===1,'unlinked user cannot read member events');
await db.exec('reset role');await db.exec('alter table organization_people disable trigger user');await q('insert into private.people(id) values($1)',[id(50)]);await q("insert into organization_people(id,organization_id,human_id,first_name,last_name) values($1,$2,$1,'Synthetic','Member')",[id(50),org]);await db.exec('alter table organization_people enable trigger user');await q("insert into portal_account_links(organization_id,person_id,user_id,verification_note) values($1,$2,$3,'Synthetic verified fixture')",[org,id(50),id(5)]);await q("insert into person_organization_relationships(organization_id,person_id,relationship) values($1,$2,'member')",[org,id(50)]);await as(5);check((await catalog()).events.length===2,'reviewed active member reads member events');await deny(()=>save(),'member still cannot edit');
await as(1);check((await catalog()).events.some(x=>x.id===staff.id),'authorized staff safe read');check((await detail(e)).conflicts>0,'same-room overlap warning');
let external=await save({registration_mode:'external',registration_url:'https://example.test/register',registration_required:true,payment_required:true});external=await save({...external,status:'published'});check((await catalog({id:external.id})).events[0].registration.url==='https://example.test/register','external registration metadata');await deny(()=>save({registration_mode:'external',registration_url:'javascript:alert(1)'}),'unsafe registration URL denied');await deny(()=>save({timezone:'Not/AZone'}),'invalid timezone denied');
await db.exec('reset role');await q("insert into event_locations(id,organization_id,name) values($1,$2,'Other tenant room')",[id(888),other]);await as(1);
await deny(()=>save({location_id:id(888)}),'existing cross-org location denied');
await deny(()=>save({permission:'events.manage'}),'permission injection rejected');
await as(2);check(!(await catalog()).events.some(x=>x.id===staff.id),'scoped manager cannot read another scope staff event');await as(1);
location=await call('location',{...location,active:false});await deny(()=>save(),'inactive location cannot be selected');
e=await save({...e,location_id:null,status:'cancelled'});check(e.status==='cancelled','cancel series');check(!(await catalog()).events.some(x=>x.id===e.id),'cancelled series absent from public catalog');e=await save({...e,location_id:null,status:'archived'});check(e.status==='archived','archive');
await deny(()=>q('update event_series set title=\'Bypass\''),'direct DML denied');await deny(()=>q('select * from event_audit'),'raw audit denied');
await call('settings',{timezone:'America/Chicago',approval_required:true,revision:1});let ap=await save({location_id:null});await deny(()=>save({...ap,location_id:null,status:'published'}),'optional approval gate');ap=await save({...ap,location_id:null,status:'approved'});ap=await save({...ap,location_id:null,status:'published'});await deny(()=>save({...ap,location_id:null,title:'Changed'}),'approved content requires renewed review');
check((await detail(ap)).audit.length===3,'audit records creation and lifecycle');
await db.exec('reset role');check((await q("select count(*)::int n from pg_class where relnamespace='public'::regnamespace and relname in ('event_settings','event_labels','event_locations','event_series','event_occurrences','event_exceptions','event_audit') and relkind='r' and relrowsecurity")).rows[0].n===7,'all seven event tables have RLS');
await db.exec(readFileSync(new URL('events.acceptance.sql',import.meta.url),'utf8'));console.log(`${count} Events checks plus 22 rollback assertions passed`);await db.close();
