const {JSDOM}=require('jsdom'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const root=path.resolve(__dirname,'../..'),dom=new JSDOM(fs.readFileSync(path.join(root,'staff-people.html'),'utf8'),{runScripts:'outside-only',url:'https://workspace.test/staff-people.html'}),w=dom.window,d=w.document;
w.HTMLDialogElement.prototype.close=function(){this.open=false};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};let invalid=false,canManage=true,h=null,member=null,conflict=false;const calls=[];
const auth={getUser:async()=>({id:'staff'}),client:{from(table){let mode='select',values,single=false;const filters={},q={select(){return q},eq(k,v){filters[k]=v;return q},in(){return q},order(){return q},range(){return q},limit(){return q},ilike(){return q},maybeSingle(){single=true;return q},insert(v){mode='insert';values=v;return q},update(v){mode='update';values=v;return q},then(resolve){calls.push({table,mode,filters,values});let data=[];
if(table==='households'){if(mode==='insert'){h={...values,id:'house',status:'active',revision:1};data={id:'house'};}else if(mode==='update'){if(conflict)data=null;else{h={...h,...values,revision:h.revision+1};data={id:h.id};}}else data=single?h:h?[h]:[];}
if(table==='organization_people')data=[{id:'person',first_name:'Jane',last_name:'Example'}];
if(table==='household_members'){if(mode==='insert'){member={...values,id:'member',active:true,revision:1,person:{first_name:'Jane',last_name:'Example'}};data={id:'member'};}else if(mode==='update'){if(conflict)data=null;else{member={...member,...values,revision:member.revision+1};data={id:'member'};}}else data=member?[member]:[];}
return Promise.resolve({data,error:null}).then(resolve);}};return q;}}};
w.eval(fs.readFileSync(path.join(root,'assets/js/staff-households.js'),'utf8'));const householdModule=w.ChampionHouseholds({auth,getContext:()=>({user:{id:'staff'},organizationId:'church',invalid,can:p=>p==='households.manage'?canManage:true}),onAccountChange:()=>{invalid=true;householdModule.clear()}});const wait=()=>new Promise(r=>setTimeout(r,0)),click=s=>d.querySelector(s).click(),submit=id=>d.getElementById(id).dispatchEvent(new w.Event('submit',{cancelable:true}));
(async()=>{await householdModule.load();click('#house-add');d.getElementById('house-name').value='Example family';submit('house-form');await wait();await wait();assert.equal(h.organization_id,'church');click('#house-list button');await wait();d.getElementById('house-search').value='Example';click('#house-person-search');await wait();assert.equal(d.getElementById('house-person-options').value,'person');submit('house-member-form');await wait();await wait();assert.equal(member.household_id,'house');assert.match(d.getElementById('house-members').textContent,/Jane Example/);
click('#house-members button:last-child');await wait();await wait();assert.equal(member.active,false);click('#house-members button:last-child');await wait();await wait();assert.equal(member.active,true);
conflict=true;click('#house-members button:last-child');await wait();assert.match(d.getElementById('house-member-status').textContent,/not saved/);assert.equal(member.active,true);conflict=false;
click('#house-edit');d.getElementById('house-state').value='archived';submit('house-form');await wait();await wait();assert.equal(h.status,'archived');click('#house-list button');await wait();assert.equal(d.getElementById('house-member-form').hidden,true);
canManage=false;await householdModule.load();assert.equal(d.getElementById('house-add').hidden,true);click('#house-list button');await wait();assert.equal(d.querySelectorAll('#house-members button').length,0);
for(const call of calls.filter(c=>c.mode==='update'))assert.equal(call.filters.organization_id,'church');invalid=true;householdModule.clear();assert.equal(d.getElementById('house-list').textContent,'');assert.equal(d.getElementById('house-members').textContent,'');assert.equal(d.getElementById('house-name').value,'');
console.log('PASS household UI: create, contact search, add/remove/restore, stale conflict, archive, read-only controls and account clearing');dom.window.close();})().catch(e=>{console.error(e);process.exitCode=1;dom.window.close()});
