import {PGlite} from '@electric-sql/pglite';import {readFileSync,readdirSync} from 'node:fs';import assert from 'node:assert/strict';
const db=new PGlite();let count=0;const ok=(v,n)=>{assert.ok(v,n);count++;console.log('PASS '+n)};const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,is_anonymous boolean default false);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth,public to anon,authenticated,service_role;grant execute on function auth.uid() to anon,authenticated,service_role;`);
const dir=new URL('../../supabase/migrations/',import.meta.url);for(const suffix of ['_organization_foundation.sql','_followup_tasks.sql','_staff_access_and_people.sql','_household_records.sql'])await db.exec(readFileSync(new URL(readdirSync(dir).find(n=>n.endsWith(suffix)),dir),'utf8'));
const orgs=(await db.query('select id,slug from organizations')).rows,cl=orgs.find(x=>x.slug==='champion-life').id,sg=orgs.find(x=>x.slug==='sowgo').id;
for(let n=1;n<=4;n++)await db.query('insert into auth.users values($1,$2,now(),false)',[id(n),`staff${n}@example.test`]);
for(const [org,user,perms] of [[cl,id(1),['staff.manage','people.read','people.create','households.read','households.manage']],[cl,id(2),['people.read','households.read']],[sg,id(3),['people.read','people.create','households.read','households.manage']],[cl,id(4),['people.read']]])for(const permission of perms)await db.query('insert into organization_staff_permissions(organization_id,user_id,permission) values($1,$2,$3)',[org,user,permission]);
async function as(n,role='authenticated'){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[n?id(n):'']);await db.exec('set role '+role)}
async function no(sql,label){let failed=false;try{await db.exec(sql)}catch{failed=true}ok(failed,label)}
await as(1);const p=(await db.query(`insert into organization_people(organization_id,first_name,last_name) values($1,'Test','Person') returning id`,[cl])).rows[0].id;
const h=(await db.query(`insert into households(organization_id,name) values($1,' Test family ') returning *`,[cl])).rows[0];ok(h.name==='Test family'&&h.revision===1,'create trims name and sets server revision');
const m=(await db.query(`insert into household_members(organization_id,household_id,person_id,relationship) values($1,$2,$3,'adult') returning *`,[cl,h.id,p])).rows[0];ok(m.active,'add household member');
await no(`insert into household_members(organization_id,household_id,person_id,relationship) values('${cl}','${h.id}','${p}','child')`,'duplicate membership rejected');
await no(`update household_members set person_id='${id(4)}'`,'membership identity cannot be changed');await no(`update households set revision=99`,'revision cannot be forged');await no('delete from households','households cannot be deleted');
const changed=(await db.query(`update household_members set relationship='child',active=false where id=$1 and revision=1 returning *`,[m.id])).rows[0];ok(changed.revision===2&&!changed.active,'remove retains member history and advances revision');
ok((await db.query(`update household_members set active=true where id=$1 and revision=1 returning id`,[m.id])).rows.length===0,'stale member update rejected');
await db.query('update household_members set active=true where id=$1 and revision=2',[m.id]);ok(true,'removed member can be restored');
await db.query("update households set status='archived' where id=$1 and revision=1",[h.id]);await no("update household_members set active=false",'archived household blocks membership edits');await db.query("update households set status='active' where id=$1 and revision=2",[h.id]);ok(true,'household archive can be reversed');
await as(3);const other=(await db.query(`insert into organization_people(organization_id,first_name,last_name) values($1,'Other','Person') returning id`,[sg])).rows[0].id;
ok((await db.query('select * from households')).rows.length===0,'other organization cannot see household');ok((await db.query('select * from household_members')).rows.length===0,'other organization cannot see relationships');await no(`insert into household_members(organization_id,household_id,person_id,relationship) values('${sg}','${h.id}','${other}','adult')`,'cross-organization household rejected');
await as(1);await no(`insert into household_members(organization_id,household_id,person_id,relationship) values('${cl}','${h.id}','${other}','adult')`,'cross-organization person rejected');
const audit=(await db.query("select * from organization_admin_events where kind like 'household_%'")).rows;ok(audit.length>=6,'household and membership changes audited');
await as(2);ok((await db.query('select * from households')).rows.length===1,'read-only staff sees household');ok((await db.query("update households set name='No' returning id")).rows.length===0,'read-only staff cannot rename');await no(`insert into households(organization_id,name) values('${cl}','No')`,'read-only staff cannot create');
await as(4);ok((await db.query('select * from households')).rows.length===0,'people access alone does not expose relationships');ok((await db.query("select * from organization_admin_events where kind like 'household_%'")).rows.length===0,'people access alone does not expose household history');
await as(1);await no(`select public.set_staff_access('${cl}',null,'staff4@example.test','Staff',array['people.read','households.manage'],0)`,'delegation requires household read permission');await db.exec(`select public.set_staff_access('${cl}',null,'staff4@example.test','Staff',array['people.read','households.read'],0)`);ok(true,'household permissions can be delegated explicitly');
await db.exec('reset role');await db.exec(`update organization_staff_permissions set revoked_at=now() where user_id='${id(2)}' and permission='people.read'`);await as(2);ok((await db.query('select * from household_members')).rows.length===0,'revoking people access removes household access');
await as(0,'anon');await no('select * from households','anonymous household access denied');await db.close();console.log(`${count} household checks passed`);
