import assert from 'node:assert/strict';import {PGlite} from '@electric-sql/pglite';import {readFileSync} from 'node:fs';import {randomUUID as uuid} from 'node:crypto';import {migrationOrder} from './migration-order.mjs';
const db=new PGlite(),q=(s,a=[])=>db.query(s,a);let count=0;const ok=(v,label)=>{assert.ok(v,label);count++;console.log('PASS '+label)},deny=async(fn,label)=>{await assert.rejects(fn);ok(true,label)},users=Array.from({length:8},uuid),A=uuid(),B=uuid();
const role=async i=>{await db.exec('reset role');await q("select set_config('request.jwt.claim.sub',$1,false)",[i===null||i==='service'?'':users[i]]);await db.exec('set role '+(i===null?'anon':i==='service'?'service_role':'authenticated'))};
const staff=(action,p={},c=A)=>q('select outreach_registration_workspace($1,$2,$3) v',[action,c,p]).then(x=>x.rows[0].v),cfg=slug=>q('select outreach_registration_config($1) v',[slug]).then(x=>x.rows[0].v),submit=(p,slug='synthetic-phasec')=>q('select outreach_registration_gateway($1,$2,$3) v',[slug,p,'a'.repeat(64)]).then(x=>{const v=x.rows[0].v;if(v.accepted===false)throw Error('Invalid submission');return v});
const member=(name,age=35,extra={})=>({client_key:uuid(),first_name:name,last_name:'Fixture',age,relationship:age<18?'child':'self',guardian_relationship:age<18?'Parent':'',attending:true,prize_participation:true,bike_interest:false,tablet_only:false,prize_choice:'bike-small',answers:{},...extra});
let org,version;
const payload=(members=[member('Adult'),member('Child',9)])=>({request_key:uuid(),first_name:'Primary',last_name:'Fixture',email:'synthetic@example.test',phone:'+15555550100',attendees:members,consents:{ministry_followup:true,communications:false,marketing:false,media:false},waiver:{request_key:uuid(),version_id:version,signer_name:'Primary Fixture',signer_relationship:'parent',acknowledged:true,authority_acknowledged:true,covered_keys:members.map(a=>a.client_key)}});
try{
 await db.exec(readFileSync(new URL('fixtures/supabase-test-bootstrap.sql',import.meta.url),'utf8'));await db.exec(readFileSync(new URL('../../supabase/bootstrap/automatic-rls.sql',import.meta.url),'utf8'));for(const f of migrationOrder)await db.exec(readFileSync(new URL('../../supabase/migrations/'+f,import.meta.url),'utf8'));ok(true,'full migration replay');
 org=(await q("select organization_id from outreach_campaigns where code='bessemer_al_2026'")).rows[0].organization_id;const template=(await q('select id from outreach_workflow_templates limit 1')).rows[0].id;
 for(const[i,u]of users.entries())await q('insert into auth.users(id,email,email_confirmed_at)values($1,$2,now())',[u,`phasec-${i}@example.test`]);
 await q("insert into organization_staff_directory(organization_id,user_id,display_name)values($1,$2,'Synthetic admin')",[org,users[0]]);await q("insert into outreach_campaign_admins(organization_id,user_id,capability,reason)values($1,$2,'manage','Explicit synthetic admin')",[org,users[0]]);
 for(const[id,code]of[[A,'synthetic_phasec'],[B,'synthetic_phasec_b']])await q("insert into outreach_campaigns(id,organization_id,code,name,city,country,timezone,template_id,status)values($1,$2,$3,$3,'Test','US','UTC',$4,'approved')",[id,org,code,template]);
 for(const[i,caps,active]of[[1,['view','registration.view','registration.manage','registration.export','checkin.manage'],true],[2,['view','registration.view'],true],[3,['view','followup'],true],[4,['view','registration.view','checkin.manage'],true],[5,['view','registration.view','registration.manage'],false],[6,['view','team.view','travel.view'],true]])await q("insert into outreach_campaign_assignments(campaign_id,user_id,role_key,capabilities,active,reason)values($1,$2,'local_leader',$3,$4,'Explicit synthetic campaign access')",[A,users[i],caps,active]);
 await role(0);await staff('configure',{revision:0,public_slug:'synthetic-phasec',enabled:true,waiver_required:true,prize_choices:[{id:'bike-small',label:'Small bike',guidance:'Synthetic category'}]});
 await role(null);await deny(()=>cfg('synthetic-phasec'),'required waiver missing fails closed');await role(0);version=(await staff('waiver_publish',{template_key:'synthetic-only',version:1,effective_at:'2026-01-01T00:00:00Z',text:'SYNTHETIC TEST WAIVER ONLY. Not approved for a real event.'})).id;
 await role(null);ok((await cfg('synthetic-phasec')).waiver.id===version,'public config returns exact published text');await deny(()=>cfg('unknown'),'unknown campaign unavailable');await deny(()=>staff('list'),'anonymous cannot list');await deny(()=>submit(payload()),'anonymous cannot bypass server gateway');
 const tables=['outreach_registration_settings','outreach_waiver_versions','outreach_event_registrations','outreach_event_attendees','outreach_waiver_signatures','outreach_waiver_corrections'];for(const t of tables)await deny(()=>q(`select * from ${t}`),'anonymous raw table denied '+t);
 await role('service');const p=payload();const received=await submit(p);ok(received.accepted&&/^R-[A-F0-9]{16}$/.test(received.reference),'native guest submit safe reference');ok(Object.keys(received).sort().join(',')==='accepted,attendee_count,reference','public result contains no PII IDs or signature');ok((await submit(p)).reference===received.reference,'exact household retry idempotent');await deny(()=>submit({...p,first_name:'Changed'}),'changed retry rejected');await deny(()=>submit({...payload(),unmapped_secret:'synthetic'}),'unknown registration fields rejected for data minimization');await deny(()=>submit(payload([member('Adult',35,{person_id:uuid()})])),'public cannot supply canonical identity');
 const unack=payload();unack.waiver.acknowledged=false;await deny(()=>submit(unack),'waiver acknowledgment required');const noauthority=payload();noauthority.waiver.authority_acknowledged=false;await deny(()=>submit(noauthority),'signer authority required');const nosigner=payload();nosigner.waiver.signer_relationship='self';await deny(()=>submit(nosigner),'minor requires parent or legal guardian');const partial=payload();partial.waiver.covered_keys.pop();await deny(()=>submit(partial),'required waiver explicitly covers all attending attendees');await deny(()=>submit(payload([member('Minor',10,{guardian_relationship:''})])),'minor guardian relationship required');await deny(()=>submit(payload([member('Minor',10,{relationship:'other'})])),'minor cannot imply independent adult authority');await deny(()=>submit(payload([member('Choice',35,{prize_choice:'unconfigured'})])),'unconfigured prize choice rejected');await deny(()=>submit({...payload(),consents:{marketing:'true'}}),'consent boolean explicit');await deny(()=>submit(payload([member('Input',35,{answers:{secret:'unmapped'}})])),'unmapped extra answers rejected');
 await db.exec('reset role');const totalsBefore=(await q('select (select count(*) from organization_people) people,(select count(*) from portal_account_links) portals,(select count(*) from organization_staff_permissions) permissions')).rows[0];ok((await q('select count(*) n from outreach_event_registrations where campaign_id=$1',[A])).rows[0].n===1,'failed submissions atomic');
 await role(1);let rows=await staff('list'),id=rows.registrations[0].id,d=await staff('detail',{registration_id:id});ok(d.attendees.length===2,'each adult and child distinct');ok(d.attendees.every(a=>a.waiver_covered&&!a.present_to_win),'preregistered not present');ok(d.consents.marketing===false&&d.consents.ministry_followup===true,'separate consent choices preserved');ok(d.source==='public'&&d.organization_id===org,'source timestamp org campaign captured');ok(d.signatures[0].coverage_snapshot.length===2,'explicit signed household coverage snapshot');ok(!('request_snapshot'in d)&&!('request_key'in d),'staff detail omits idempotency secret');
 for(const i of[2,3,4,5,6,7]){await role(i);if(i===2||i===4){ok((await staff('list')).registrations.length===1,'explicit view can read '+i);await deny(()=>staff('walkup',payload()),'view/check-in does not grant registration manage '+i)}else await deny(()=>staff('list'),'pastor/travel/participant/inactive denied '+i);await deny(()=>staff('detail',{registration_id:id},B),'campaign A cannot access B '+i)}
 await role(1);await deny(()=>staff('detail',{registration_id:uuid()}),'guessed household UUID denied');await deny(()=>staff('checkin',{registration_id:id,attendee_id:uuid()}),'guessed attendee UUID denied');const adult=d.attendees.find(a=>a.age>=18),child=d.attendees.find(a=>a.age<18);
 await deny(()=>staff('update',{registration_id:id,revision:d.revision,status:'checked_in'}),'household status cannot fabricate individual attendance');
 await staff('checkin',{registration_id:id,attendee_id:child.id,wristband:'SYNTHETIC-1'});ok((await staff('checkin',{registration_id:id,attendee_id:child.id})).already_checked_in,'double check-in returns canonical state');d=await staff('detail',{registration_id:id});ok(d.attendees.find(a=>a.id===child.id).present_to_win,'check-in activates eligible hook');ok(d.attendees.find(a=>a.id===child.id).wristband==='SYNTHETIC-1','wristband supported');await deny(()=>staff('attendee_update',{registration_id:id,attendee_id:child.id,revision:2,first_name:'Different'}),'checked-in identity cannot change');await deny(()=>staff('update',{registration_id:id,revision:d.revision,status:'cancelled'}),'cannot cancel beneath active check-in');await deny(()=>staff('waiver_correct',{registration_id:id,signature_id:d.signatures[0].id,reason:'Synthetic correction reason'}),'must reverse before invalidating waiver');
 await staff('reverse',{registration_id:id,attendee_id:child.id,reason:'Synthetic mistaken check-in correction'});d=await staff('detail',{registration_id:id});ok(!d.attendees.find(a=>a.id===child.id).present_to_win,'reversal clears present hook');await staff('attendee_update',{registration_id:id,attendee_id:child.id,revision:d.attendees.find(a=>a.id===child.id).revision,first_name:'Renamed'});d=await staff('detail',{registration_id:id});ok(!d.attendees.find(a=>a.id===child.id).waiver_covered,'identity change invalidates coverage without rewriting snapshot');await deny(()=>staff('checkin',{registration_id:id,attendee_id:child.id}),'missing current coverage blocks check-in');ok(d.signatures[0].coverage_snapshot.some(a=>a.first_name==='Child'),'signed historical name unchanged');
 const signature={registration_id:id,request_key:uuid(),version_id:version,signer_name:'Primary Fixture',signer_relationship:'parent',acknowledged:true,authority_acknowledged:true,covered_keys:d.attendees.map(a=>a.client_key)};await deny(()=>staff('attendee_update',{registration_id:id,attendee_id:adult.id,revision:adult.revision,prize_choice:'unconfigured'}),'staff cannot invent prize category');await staff('attendee_update',{registration_id:id,attendee_id:adult.id,revision:adult.revision,prize_participation:false,prize_choice:null,answers:{}});const edited=(await staff('detail',{registration_id:id})).attendees.find(a=>a.id===adult.id);ok(!edited.prize_participation&&edited.prize_choice===null&&edited.waiver_covered,'staff preference edit preserves valid identity coverage');const sig=await staff('sign',signature);ok((await staff('sign',signature)).id===sig.id,'signature retry one canonical record');await deny(()=>staff('sign',{...signature,signer_name:'Other Adult'}),'signature retry content cannot change');
 await role(0);await deny(()=>staff('configure',{revision:1,public_slug:'synthetic-phasec',prize_choices:[{label:'Missing ID'}]}),'configured prize requires stable ID');await deny(()=>staff('configure',{revision:1,public_slug:'synthetic-phasec',prize_choices:[{id:'same',label:'A'},{id:'same',label:'B'}]}),'configured prize IDs unique');const v2=(await staff('waiver_publish',{template_key:'synthetic-only',version:2,effective_at:'2026-02-01T00:00:00Z',text:'SYNTHETIC UPDATED WAIVER ONLY. Never publish real wording from this fixture.'})).id;ok((await staff('sign',signature)).id===sig.id,'old exact signature retry remains idempotent after new version');d=await staff('detail',{registration_id:id});ok(d.signatures.every(w=>w.version===1&&w.text_snapshot.includes('TEST WAIVER')),'future template publication preserves signed exact version/text');await db.exec('reset role');await deny(()=>q("update outreach_waiver_signatures set signer_name='Tampered' where id=$1",[sig.id]),'signed snapshot immutable even privileged update');await deny(()=>q('delete from outreach_waiver_versions where id=$1',[v2]),'published version immutable');
 await role(1);await staff('waiver_correct',{registration_id:id,signature_id:sig.id,reason:'Synthetic explicit version correction'});d=await staff('detail',{registration_id:id});ok(d.signatures.find(w=>w.id===sig.id).corrected,'append-only correction marks historical invalidation');
 const newAttendee=member('New child',6);const added=await staff('attendee_add',{registration_id:id,...newAttendee});ok((await staff('attendee_add',{registration_id:id,...newAttendee})).id===added.id,'attendee add retry no duplicates');await deny(()=>staff('attendee_add',{registration_id:id,...newAttendee,age:7}),'same attendee key different identity rejected');
 await deny(()=>staff('attendee_add',{registration_id:id,...newAttendee,guardian_relationship:'Changed guardian'}),'attendee retry cannot silently change guardian authority');
 const walk=payload([member('Walkup',28)]);walk.waiver.version_id=v2;const wr=await staff('walkup',walk);ok((await staff('list')).registrations.find(r=>r.reference===wr.reference).source==='walkup','walk-up reuses registration schema');ok((await staff('walkup',walk)).reference===wr.reference,'walk-up retry idempotent');
 const formula=payload([member('=DANGEROUS',22)]);formula.waiver.version_id=v2;await role('service');await submit(formula);await role(1);const csv=(await staff('csv')).csv;ok(csv.includes("'=DANGEROUS"),'roster formula neutralization');ok(!csv.includes(id)&&!csv.includes('signature')&&!csv.includes('SYNTHETIC TEST WAIVER'),'export excludes internal identifiers/signature');await role(2);await deny(()=>staff('csv'),'view does not imply export');
 await db.exec('reset role');ok((await q("select count(*) n from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='private' and has_function_privilege('anon',p.oid,'execute')")).rows[0].n===0,'no anonymous private helper execution');ok(JSON.stringify((await q('select (select count(*) from organization_people) people,(select count(*) from portal_account_links) portals,(select count(*) from organization_staff_permissions) permissions')).rows[0])===JSON.stringify(totalsBefore),'no canonical People/portal/staff authority created');ok((await q('select count(*) n from outreach_drawing_numbers')).rows[0].n===0,'Phase D numbers not activated');ok((await q('select count(*) n from outreach_prize_participants where attendee_id=$1',[child.id])).rows[0].n===1,'reuse one dormant prize identity per attendee');ok((await q("select count(*) n from outreach_campaign_events where kind like 'outreach.%' and delivery_state<>'held'")).rows[0].n===0,'domain events held no notifications');
 await role(0);await staff('configure',{revision:0,public_slug:'synthetic-phasec-b',enabled:true,waiver_required:false},B);await role('service');const optional=payload([member('Optional',35,{prize_choice:null})]);optional.waiver=null;ok((await submit(optional,'synthetic-phasec-b')).accepted,'optional waiver campaign supports unsigned adult registration');await role(0);await staff('configure',{revision:1,public_slug:'synthetic-phasec-b',enabled:true,waiver_required:false,opens_at:'2099-01-01T00:00:00Z'},B);await role(null);await deny(()=>cfg('synthetic-phasec-b'),'future registration window fails closed');await role(1);await deny(()=>q('select * from outreach_event_attendees'),'authenticated raw attendee read denied');await deny(()=>q('update outreach_waiver_signatures set signer_name=signer_name'),'authenticated signature mutation denied');await db.exec('reset role');
 await q('update outreach_campaign_assignments set active=false where campaign_id=$1 and user_id=$2',[A,users[1]]);await role(1);await deny(()=>staff('list'),'same-session revocation immediate');await deny(()=>staff('checkin',{registration_id:id,attendee_id:adult.id}),'revoked check-in denied');await db.exec('reset role');await q("update outreach_campaign_assignments set active=true,effective_at=now()-interval '2 days',expires_at=now()-interval '1 day' where campaign_id=$1 and user_id=$2",[A,users[1]]);await role(1);await deny(()=>staff('list'),'expired campaign registration assignment denied');
 console.log(`${count} Phase C database/security checks passed`);
}finally{await db.close()}
