import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {migrationOrder} from './migration-order.mjs';
const db=new PGlite(),q=(sql,args=[])=>db.query(sql,args),ids=Array.from({length:12},()=>randomUUID());let count=0;
const check=(yes,label)=>{assert.ok(yes,label);count++;console.log('PASS '+label)},deny=async(fn,label,fragment)=>{await assert.rejects(fn,fragment?e=>e.message.includes(fragment):undefined);check(true,label)};
const as=async(i,role)=>{await db.exec('reset role');await q("select set_config('request.jwt.claim.sub',$1,false)",[i===null?'':ids[i]]);await db.exec('set role '+(role||(i===null?'anon':'authenticated')))};
let A,B,F,org,foreign;
const staff=(action,p={},campaign=A)=>q('select outreach_team_workspace($1,$2,$3) v',[action,campaign,p]).then(x=>x.rows[0].v),portal=(action,p={},campaign=A)=>q('select outreach_team_portal($1,$2,$3) v',[action,campaign,p]).then(x=>x.rows[0].v);
const member=(name,extra={})=>({first_name:name,last_name:'Fixture',age:35,attending:true,volunteering:true,transport_preference:'needs_ride',lodging_preference:'needs_lodging',travel_mode:'independent',...extra});
const current=async id=>(await staff('member',{member_id:id})).member;
const act=async(action,id,p={})=>staff(action,{member_id:id,revision:(await current(id)).revision,...p});
try{
 await db.exec(readFileSync(new URL('fixtures/supabase-test-bootstrap.sql',import.meta.url),'utf8'));await db.exec(readFileSync(new URL('../../supabase/bootstrap/automatic-rls.sql',import.meta.url),'utf8'));
 for(const f of migrationOrder)await db.exec(readFileSync(new URL('../../supabase/migrations/'+f,import.meta.url),'utf8'));
 console.log('PASS migration replay');count++;
 org=(await q("select organization_id from outreach_campaigns where code='bessemer_al_2026'")).rows[0].organization_id;foreign=(await q('select id from organizations where id<>$1 limit 1',[org])).rows[0].id;
 for(let i=0;i<ids.length;i++)await q('insert into auth.users(id,email,email_confirmed_at)values($1,$2,$3)',[ids[i],`phaseb-${i}@example.test`,i===11?null:new Date()]);
 for(const [i,o] of [[0,org],[8,foreign]]){await q("insert into organization_staff_directory(organization_id,user_id,display_name)values($1,$2,'Synthetic operator')",[o,ids[i]]);await q("insert into outreach_campaign_admins(organization_id,user_id,capability,reason)values($1,$2,'manage','Explicit synthetic admin')",[o,ids[i]]);}
 await q("insert into organization_staff_permissions(organization_id,user_id,permission) select $1,$2,k from unnest(array['people.read','people.create','people.update','households.read','households.manage']) k",[org,ids[0]]);
 const template=(await q('select id from outreach_workflow_templates limit 1')).rows[0].id;
 for(const [code,o] of [['synthetic_phaseb_a',org],['synthetic_phaseb_b',org],['synthetic_phaseb_foreign',foreign]]){const id=randomUUID();await q("insert into outreach_campaigns(id,organization_id,code,name,city,country,timezone,template_id,status,venue)values($1,$2,$3,$4,'Testville','US','America/Chicago',$5,'approved',$6)",[id,o,code,code,template,{name:'Synthetic venue',address:'100 Test Avenue',secret:'MUST NOT LEAK'}]);if(code.endsWith('_a'))A=id;else if(code.endsWith('_b'))B=id;else F=id;}
 for(const [i,caps,expiry,active]of [[4,['view','followup'],null,true],[5,['view','team.view','team.manage','travel.view','travel.manage'],null,true],[6,['view','team.view','travel.view'],new Date(Date.now()-100000),true],[7,['view','team.view','travel.view'],null,false],[9,['view','team.view'],null,true],[10,['view','travel.view','travel.manage'],null,true]])await q("insert into outreach_campaign_assignments(campaign_id,user_id,role_key,capabilities,effective_at,expires_at,active,reason)values($1,$2,'local_leader',$3,now()-interval '3 days',$4,$5,'Synthetic explicit assignment')",[A,ids[i],caps,expiry,active]);
 await as(0);for(const c of [A,B])await staff('settings',{revision:0,enabled:true,window_override:'open',official_capacity:2,multiple_roles:true,participant_notes:'Wear comfortable shoes',coordination_name:'Coordinator',coordination_phone:'+15555550100'},c);
 const role=(await staff('role_save',{name:'Registration'})).id,role2=(await staff('role_save',{name:'Setup'})).id;
 const people=[];for(let i=0;i<8;i++){await db.exec('reset role');await q("select set_config('request.jwt.claim.sub',$1,false)",[ids[0]]);people.push((await q("insert into organization_people(organization_id,first_name,last_name,email,phone)values($1,$2,'Fixture',$3,$4) returning id",[org,['Primary','Spouse','Volunteer child','Attendee child','Needs ride','Self traveler','Extra','Driver'][i],`canonical-${i}@example.test`,`+1555555010${i}`])).rows[0].id);}
 await q("insert into portal_account_links(organization_id,person_id,user_id,verification_note) values($1,$2,$3,'Reviewed synthetic portal identity')",[org,people[0],ids[1]]);
 const household=(await q("insert into households(organization_id,name)values($1,'Fixture Family') returning id",[org])).rows[0].id;for(let i=0;i<4;i++)await q('insert into household_members(organization_id,household_id,person_id,relationship)values($1,$2,$3,$4)',[org,household,people[i],i<2?'adult':'child']);
 await as(1);check((await portal('form')).known_members.length===0,'household label grants no dependent lookup');
 await as(0);for(const person of people.slice(1,4))await staff('guardian_link',{primary_person_id:people[0],dependent_person_id:person,reason:'Reviewed synthetic party authority'});
 await as(1);check((await portal('form')).known_members.length===3,'explicit reviewed family authority reuses canonical members');
 const payload={party_label:'Fixture Family',members:[member('Primary',{preferred_roles:[role],secondary_roles:[role2],available_vehicle:{type:'car',seats:4,make_model:'Synthetic car'}}),member('Spouse',{relationship:'spouse',person_id:people[1]}),member('Volunteer child',{relationship:'child',age:15,person_id:people[2],preferred_roles:[role]}),member('Attendee child',{relationship:'child',age:7,person_id:people[3],volunteering:false})]};
 const first=await portal('submit',payload);check((await portal('submit',payload)).id===first.id,'signup retry idempotent');let own=await portal('own');check(own.members.length===4&&own.members.every(m=>m.status==='applied'),'primary/spouse/children signup does not approve');check(own.members.filter(m=>m.age<18).every(m=>m.consent_state==='phase_c_pending'),'minor consent hook stays pending');check(!own.members.find(m=>m.name.startsWith('Attendee child')).volunteering&&own.members.find(m=>m.name.startsWith('Volunteer child')).volunteering,'attendee and volunteer children distinct');
 await as(2);await portal('submit',{party_label:'Ride & Lodging',members:[member('Needs ride',{phone:'+15555550104'})]});await as(3);await portal('submit',{party_label:'Independent',members:[member('Self traveler',{transport_preference:'own_transport',lodging_preference:'own_lodging',travel_mode:'self_driving'})]});
 await as(0);let list=await staff('list'),primary=list.members.find(m=>m.first_name==='Primary').id,spouse=list.members.find(m=>m.first_name==='Spouse').id,child=list.members.find(m=>m.first_name==='Volunteer child').id,small=list.members.find(m=>m.first_name==='Attendee child').id,ride=list.members.find(m=>m.first_name==='Needs ride').id,self=list.members.find(m=>m.first_name==='Self traveler').id;
 check((await current(primary)).person_id===people[0],'only reviewed portal identity auto-links primary');check((await current(ride)).person_id===null,'email/phone never silently merge Person');check((await staff('matches',{member_id:ride})).some(x=>x.id===people[4]),'possible existing phone/name surfaced for review');await deny(()=>act('create_person',ride,{reason:'Reviewed synthetic identity'}),'possible duplicate blocks new canonical Person','Possible existing Person');await act('link_person',ride,{person_id:people[4],reason:'Reviewed synthetic existing identity'});await act('link_person',self,{person_id:people[5],reason:'Reviewed synthetic existing identity'});
 await staff('household_link',{signup_id:first.id,household_id:household,revision:1,reason:'Reviewed canonical family membership'});check((await staff('manifest',{household_id:household})).length===4,'manifest reuses canonical Household grouping');
 await deny(()=>act('status',child,{status:'approved',reason:'Synthetic approval review'}),'minor cannot approve without guardian review');await act('status',primary,{status:'under_review',reason:'Synthetic review started'});await act('status',primary,{status:'approved',reason:'Synthetic official approval'});await act('status',spouse,{status:'approved',reason:'Synthetic official approval'});
 for(const id of [child,small]){await act('member_review',id,{guardian_reviewed:true,party_access_reviewed:true,reason:'Explicit synthetic guardian travel review'});await act('status',id,{status:'approved',reason:'Synthetic official approval'});}
 check((await staff('list')).summary.remaining_official_slots===0,'capacity summary clamps remaining; leadership approval never auto-rejects applicants');
 await act('status',ride,{status:'waitlisted',reason:'Synthetic waitlist decision'});await act('status',ride,{status:'not_selected',reason:'Synthetic independent travel choice'});await act('status',ride,{status:'self_traveling',reason:'Synthetic independent travel approval'});await act('status',ride,{status:'cancelled',reason:'Synthetic cancellation'});await deny(()=>act('status',ride,{status:'approved',reason:'Synthetic bypass reopening'}),'cancelled must reopen first');await act('status',ride,{status:'applied',reason:'Synthetic reopening review'});await act('status',ride,{status:'approved',reason:'Synthetic official approval'});await act('status',self,{status:'self_traveling',reason:'Synthetic independent travel approval'});
 const vehicle=async(label,type,total,passenger,extra={})=>(await staff('vehicle_save',{label,vehicle_type:type,total_capacity:total,passenger_capacity:passenger,departure_location:'Synthetic departure',destination:'Testville',internal_notes:'PRIVATE VEHICLE NOTE',participant_notes:'Bring water',...extra})).id;
 const bus=await vehicle('Church Bus','bus',5,4),rv=await vehicle('RV','rv',2,1),car=await vehicle('Car 1','car',2,1),box=await vehicle('Box Truck','box truck',2,0,{passenger_carrying:false}),inactive=await vehicle('Inactive','car',2,1,{active:false});
 await deny(()=>act('vehicle_assign',self,{vehicle_id:bus,seat_role:'passenger'}),'independent participant cannot take official transport');await deny(()=>act('vehicle_assign',primary,{vehicle_id:inactive,seat_role:'driver',driver_reviewed:true}),'inactive vehicle denies assignment');await deny(()=>act('vehicle_assign',primary,{vehicle_id:box,seat_role:'passenger'}),'equipment-only denies passengers');await deny(()=>act('vehicle_assign',primary,{vehicle_id:bus,seat_role:'driver'}),'driver requires qualification acknowledgement');
 await act('vehicle_assign',primary,{vehicle_id:bus,seat_role:'driver',driver_reviewed:true});await act('vehicle_assign',spouse,{vehicle_id:bus,seat_role:'co_driver',driver_reviewed:true});for(const id of [child,small])await act('vehicle_assign',id,{vehicle_id:bus,seat_role:'passenger'});
 await deny(()=>act('vehicle_assign',child,{vehicle_id:car,seat_role:'passenger'}),'one primary vehicle per traveler');await deny(()=>act('vehicle_assign',ride,{vehicle_id:B,seat_role:'passenger'}),'foreign/guessed vehicle ID denied');await act('vehicle_assign',ride,{vehicle_id:car,seat_role:'passenger'});check((await staff('list')).vehicles.find(v=>v.id===bus).assigned===4,'driver/co-driver/passenger counts');
 await deny(()=>staff('vehicle_save',{id:bus,revision:1,label:'Bus',vehicle_type:'bus',total_capacity:2,passenger_capacity:1}),'capacity cannot shrink below assignments');await deny(()=>act('status',primary,{status:'cancelled',reason:'Synthetic invalid cancellation'}),'approval cannot revoke beneath assigned family');
 const hotel=(await staff('lodging_save',{name:'Hotel A',address:'100 Test Hotel Way',check_in:'2026-11-01T15:00:00Z',check_out:'2026-11-03T11:00:00Z',map_url:'https://maps.google.com/maps?q=test',internal_notes:'PRIVATE BOOKING CONFIRMATION'})).id;
 const room=(await staff('room_save',{lodging_id:hotel,label:'Family 101',capacity:4,internal_notes:'PRIVATE ROOM NOTES'})).id,room2=(await staff('room_save',{lodging_id:hotel,label:'Room 102',capacity:1})).id;
 await act('lodging_assign',primary,{room_id:room});await act('lodging_assign',spouse,{room_id:room});for(const id of [child,small])await act('lodging_assign',id,{room_id:room});await deny(()=>act('lodging_assign',ride,{room_id:room}),'room capacity enforced');await deny(()=>act('lodging_assign',primary,{room_id:room2}),'overlapping room stay denied');await act('lodging_assign',ride,{room_id:room2});await deny(()=>act('lodging_assign',self,{room_id:room2}),'self lodging gets no official room assignment');
 await deny(()=>staff('lodging_save',{id:hotel,revision:1,name:'Hotel A',check_in:'2026-11-02T15:00:00Z',check_out:'2026-11-04T11:00:00Z'}),'occupied stay window cannot bypass conflict checks');
 await act('role_assign',primary,{role_id:role});await act('role_assign',primary,{role_id:role2});await act('role_assign',self,{role_id:role2});await deny(()=>act('role_assign',small,{role_id:role}),'attendee-only child cannot receive volunteer role');check((await staff('manifest',{role_id:role2})).length===2,'final roles separate from preferences; independent helper supported');check((await staff('manifest',{vehicle_id:bus})).length===4&&(await staff('manifest',{lodging_id:hotel})).length===5,'manifest vehicle/lodging filters scoped');
 await staff('meeting_save',{label:'Public meetup',kind:'team_meetup',address:'Test park',visibility:'participants',map_url:'https://maps.google.com/maps?q=test'});await staff('meeting_save',{label:'Official departure',kind:'departure',visibility:'official'});await staff('meeting_save',{label:'PRIVATE STAGING',kind:'staging',visibility:'staff'});await deny(()=>staff('meeting_save',{label:'Unsafe',kind:'venue',map_url:'javascript:alert(1)'}),'unsafe direction link denied');
 await as(1);own=await portal('own');check(own.members.find(m=>m.id===child).vehicle.label==='Church Bus','reviewed guardian sees authorized child trip');check(!own.members.find(m=>m.id===spouse).trip_shared,'household adult relationship alone does not share trip');check(!JSON.stringify(own).includes('PRIVATE')&&!JSON.stringify(own).includes('MUST NOT LEAK'),'participant projection omits internal notes/booking/private venue keys');await deny(()=>portal('own',{},B),'participant cannot guess another campaign');
 await db.exec('reset role');await q("insert into portal_account_links(organization_id,person_id,user_id,verification_note)values($1,$2,$3,'Reviewed secondary applicant account')",[org,people[1],ids[9]]);await as(9);check((await portal('form')).existing_signup_id===first.id,'reviewed spouse account opens own existing trip');own=await portal('own');check(own.members.length===1&&own.members[0].id===spouse&&own.members[0].vehicle.label==='Church Bus','secondary participant sees only own trip, no family roster');
 await as(0);await act('status',self,{status:'guest',reason:'Synthetic guest review'});check((await current(self)).status==='guest','guest participation distinct from official travel');await act('status',self,{status:'self_traveling',reason:'Synthetic independent travel review'});
 await deny(()=>act('vehicle_remove',primary),'cannot leave minors unsupervised by removing guardian vehicle');await deny(()=>act('lodging_remove',primary,{room_id:room}),'cannot leave minors unsupervised by removing guardian room');
 const familyContext=await staff('family_context',{signup_id:first.id});check(familyContext.households.some(h=>h.id===household)&&familyContext.guardian_links.length===3,'scoped canonical family review context');await deny(()=>staff('family_context',{signup_id:randomUUID()}),'guessed family context denied');
 await act('vehicle_remove',spouse);await deny(()=>act('vehicle_assign',spouse,{vehicle_id:rv,seat_role:'driver',driver_reviewed:true}),'intentional family split required');await act('vehicle_assign',spouse,{vehicle_id:rv,seat_role:'driver',driver_reviewed:true,family_split_reviewed:true});check((await staff('manifest',{vehicle_id:rv})).length===1,'explicit family split supported');await act('vehicle_remove',spouse);await act('vehicle_assign',spouse,{vehicle_id:bus,seat_role:'co_driver',driver_reviewed:true});
 const settings=(await staff('list')).settings;await staff('settings',{...settings,revision:settings.revision,enabled:true,window_override:'closed'});await as(2);check((await portal('form')).existing_signup_id!==null,'closed signup retains existing participant trip');check((await portal('available')).some(c=>c.id===A),'existing participants find their trip after signup closes');await as(4);await deny(()=>portal('submit',{party_label:'Closed',members:[member('Closed applicant')]}),'closed signup denies new application');await as(0);await staff('settings',{...settings,revision:settings.revision+1,enabled:true,window_override:'scheduled',opens_at:new Date(Date.now()+86400000).toISOString()});await as(4);check((await portal('available')).every(c=>c.id!==A),'future signup date does not open early');await as(0);await staff('settings',{...settings,revision:settings.revision+2,enabled:true,window_override:'open'});
 await as(3);own=await portal('own');check(own.meetings.length===1&&own.meetings[0].label==='Public meetup','self traveler receives shared directions, no official/private meetup');check(own.members[0].vehicle===null&&own.members[0].lodging.length===0,'self traveler no other assignments leak');
 for(const i of [null,4,6,7,8,11]){await as(i);await deny(()=>staff('list'),`${i===4?'local pastor':i===null?'anonymous':'unassigned/expired/revoked/unverified'} team travel denied`);}
 await as(5);await deny(()=>staff('list',{},B),'Campaign A manager denied B');await deny(()=>staff('export',{kind:'travel'},F),'cross organization export denied');await deny(()=>staff('matches',{member_id:ride}),'team manager gains no People read');await deny(()=>act('create_person',ride,{reason:'Attempting broad People creation'}),'team manager gains no People create');
 await as(9);list=await staff('list');check(list.members.every(m=>m.travel===null)&&!list.vehicles&&!list.rooms&&!('participant_notes' in list.settings),'team-only capability does not leak travel');await deny(()=>staff('export',{kind:'travel'}),'team-only cannot export travel');
 await db.exec('reset role');await q("update outreach_campaign_assignments set capabilities=array['view','team.view','team.manage'] where user_id=$1",[ids[9]]);await as(9);await deny(()=>staff('settings',{revision:1,participant_notes:'Unauthorized trip edit'}),'team manager cannot change trip configuration');
 await as(10);list=await staff('list');check(list.members.every(m=>m.email===null),'travel-only projection omits unnecessary email');await deny(()=>staff('member',{member_id:primary}),'travel-only cannot read private applicant detail');const traveler=await staff('traveler',{member_id:primary});check(!('email' in traveler.member)&&!('notes' in traveler.member)&&traveler.member.id===primary,'travel manager can assign without private applicant detail');await deny(()=>staff('status',{member_id:primary,revision:1,status:'cancelled'}),'travel manager cannot approve or cancel');
 await as(0);await staff('reminders');const before=await staff('reminders');check(before.state==='held','reminders never report sent');check((await staff('reminders')).events.length===before.events.length,'manual reminder cadence idempotent');check((await staff('export',{kind:'travel'})).csv.includes('Family 101'),'travel CSV explicit scoped assignment fields');await db.exec('reset role');await q("update outreach_team_members set first_name='=FORMULA' where id=$1",[primary]);await as(0);check((await staff('export',{kind:'team'})).csv.includes("'=FORMULA"),'CSV spreadsheet formulas neutralized');
 await db.exec('reset role');await q('update outreach_team_guardian_links set active=false where dependent_person_id=$1',[people[2]]);await as(1);check(!(await portal('own')).members.find(m=>m.id===child).vehicle,'guardian revocation immediately removes linked child travel');
 await as(0);await staff('access',{user_id:ids[5],revision:1,capabilities:[],reason:'Synthetic Phase B permission revocation'});await as(5);await deny(()=>staff('list'),'Phase B revocation immediate for same session');
 for(const i of [null,1,4]){await as(i);await deny(()=>q('select * from outreach_team_members'),'raw members unavailable');await deny(()=>q('select private.outreach_team_manifest($1)',[A]),'internal helper execution unavailable');}
 await db.exec('reset role');check((await q("select count(*)::int n from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname like 'outreach_team_%' and c.relkind='r' and not c.relrowsecurity")).rows[0].n===0,'all Phase B tables RLS');check((await q("select count(*)::int n from outreach_campaign_events where delivery_state<>'held'")).rows[0].n===0,'all domain events held');check((await q("select count(*)::int n from organization_people")).rows[0].n===8,'no duplicate canonical People from signup');
 await as(4);await deny(()=>portal('submit',{party_label:'Spoofed official',members:[member('Spoofed',{travel_mode:'official_vehicle'})]}),'applicant cannot spoof official vehicle mode');await portal('submit',{party_label:'Reviewed new applicant',members:[member('Fresh unmatched')]});await as(0);const fresh=(await staff('list')).members.find(m=>m.first_name==='Fresh unmatched').id;await act('create_person',fresh,{reason:'Reviewed unmatched synthetic identity'});check((await current(fresh)).person_id!==null,'reviewed new canonical Person creation succeeds');await db.exec('reset role');check((await q('select count(*)::int n from organization_people')).rows[0].n===9,'one reviewed creation, no duplicate People');check((await q('select count(*)::int n from portal_account_links where user_id=$1',[ids[4]])).rows[0].n===0,'Person creation never grants portal access');
 await as(0);await act('vehicle_remove',spouse);await act('lodging_remove',spouse,{room_id:room});await act('status',spouse,{status:'waitlisted',reason:'Synthetic secondary applicant waitlist'});await as(9);own=await portal('own');check(own.meetings.length===0&&own.trip===null,'secondary waitlisted account cannot inherit approved party trip access');
 console.log(`${count} Phase B checks passed`);
}catch(e){console.error({message:e.message,where:e.where,detail:e.detail,stack:e.stack});process.exitCode=1;}finally{await db.close();}
