import assert from 'node:assert/strict';import {PGlite} from '@electric-sql/pglite';import {readFileSync} from 'node:fs';import {randomUUID} from 'node:crypto';import {migrationOrder} from './migration-order.mjs';
const db=new PGlite(),q=(s,a=[])=>db.query(s,a),users=Array.from({length:8},()=>randomUUID());let count=0;
const check=(v,m)=>{assert.ok(v,m);count++;console.log('PASS '+m)},deny=async(f,m)=>{await assert.rejects(f);check(true,m)};
const as=async(n,role)=>{await db.exec('reset role');await q("select set_config('request.jwt.claim.sub',$1,false)",[n==null?'':users[n]]);await db.exec('set role '+(role||(n==null?'anon':'authenticated')))};
const core=(a,c=null,p={})=>q('select outreach_campaign_workspace($1,$2,$3) v',[a,c,p]).then(x=>x.rows[0].v),work=(a,c=null,p={})=>q('select outreach_campaign_workflow($1,$2,$3) v',[a,c,p]).then(x=>x.rows[0].v);
try{
 await db.exec(readFileSync(new URL('fixtures/supabase-test-bootstrap.sql',import.meta.url),'utf8'));await db.exec(readFileSync(new URL('../../supabase/bootstrap/automatic-rls.sql',import.meta.url),'utf8'));
 for(const f of migrationOrder.slice(0,migrationOrder.indexOf('20261006113255_outreach_campaign_core_v1.sql')))await db.exec(readFileSync(new URL('../../supabase/migrations/'+f,import.meta.url),'utf8'));
 for(let i=0;i<8;i++)await q('insert into auth.users(id,email,email_confirmed_at)values($1,$2,$3)',[users[i],`campaign-${i}@example.test`,i===7?null:new Date()]);
 const legacy=randomUUID();await q("insert into outreach_registrations(id,source,first_name,last_name,email,phone,decision,prayer_request,user_id)values($1,'bessemer_al_2026','Synthetic','Historic','synthetic@example.test','+15555551234','salvation','Approved prayer context',$2)",[legacy,users[6]]);
 const before=(await q('select row_to_json(r) v from outreach_registrations r where id=$1',[legacy])).rows[0].v;
 for(const f of migrationOrder.slice(migrationOrder.indexOf('20261006113255_outreach_campaign_core_v1.sql')))await db.exec(readFileSync(new URL('../../supabase/migrations/'+f,import.meta.url),'utf8'));
 const campaigns=(await q('select * from outreach_campaigns')).rows,A=campaigns.find(x=>x.code==='bessemer_al_2026').id,B=campaigns.find(x=>x.code==='huntsville_al_2026').id,org=campaigns[0].organization_id,other=(await q("select id from organizations where slug='champion-life'")).rows[0].id;
 for(const i of [0,2]){await q("insert into organization_staff_directory(organization_id,user_id,display_name)values($1,$2,'Synthetic admin')",[i===0?org:other,users[i]]);await q("insert into outreach_campaign_admins(organization_id,user_id,capability,reason)values($1,$2,'manage','Synthetic explicit assignment')",[i===0?org:other,users[i]]);}
 for(const i of [1,4,5,7])await q("insert into outreach_campaign_assignments(campaign_id,user_id,role_key,capabilities,effective_at,expires_at,reason)values($1,$2,'local_leader',array['view','export','followup','decisions','workflow','documents'],now()-interval '3 days',$3,'Synthetic campaign assignment')",[A,users[i],i===4?new Date(Date.now()-86400000):null]);await q('update outreach_campaign_assignments set active=false where user_id=$1',[users[5]]);
 const course=(await q("select id from courses where slug='getting-a-grip-on-the-basics'")).rows[0].id;await q('insert into course_enrollments(user_id,course_id)values($1,$2)',[users[6],course]);await q("insert into lesson_progress(user_id,course_id,lesson_number,status)values($1,$2,1,'completed'),($1,$2,2,'in_progress')",[users[6],course]);await q("insert into lesson_answers(user_id,course_id,lesson_number,question_number,answer)values($1,$2,1,1,'SECRET ANSWER')",[users[6],course]);
 assert.deepEqual((await q('select row_to_json(r) v from outreach_registrations r where id=$1',[legacy])).rows[0].v,before);check(true,'historical Bessemer content and ownership unchanged');
 await q("insert into outreach_registrations(source,first_name,last_name,email,phone,decision)values('bessemer_al_2026','=FORMULA','New','new@example.test','+15555554321','rededication')");check((await q('select count(*)::int n from outreach_campaign_registrants where campaign_id=$1',[A])).rows[0].n===2,'existing and future Bessemer rows bridged exactly once');
 for(const n of [null,3]){await as(n);for(const table of ['outreach_campaigns','outreach_campaign_registrants','outreach_campaign_decisions','outreach_campaign_assignments','outreach_campaign_admins','outreach_campaign_audit','outreach_prize_wins'])await deny(()=>q('select * from '+table),(n==null?'anon':'member')+' direct '+table+' denied');await deny(()=>core('detail',A),'no unauthorized campaign/progress read');}
 await as(1);check((await core('list')).length===1,'leader sees assigned campaign only');for(const id of [B,randomUUID()])await deny(()=>core('detail',id),'unassigned/guessed campaign denied');await deny(()=>core('csv',B,{campaign_id:A}),'CSV filter/UUID scope enforced');check((await q('select count(*)::int n from organization_people')).rows[0].n===0,'leader has no organization People access');check((await q('select * from lesson_answers where user_id=$1',[users[6]])).rows.length===0,'leader cannot read course answers');
 let d=await core('detail',A),r=d.registrants.find(x=>x.first_name==='Synthetic');check(r.decision==='salvation'&&r.notes==='Approved prayer context','legacy decisions projected');check(r.discipleship_status==='active'&&r.current_lesson===2&&r.completed_lessons===1,'verified claimed account Grip progress projects');check(!JSON.stringify(d).includes('SECRET ANSWER'),'projection omits answers');
 const csv=await core('csv',A);check(csv.csv.startsWith('First Name,Last Name,Phone,Email,Decision,Registration Date,Discipleship Status,Current Lesson,Last Activity,Follow-Up Status\r\n'),'exact CSV fields');check(csv.csv.includes("'=FORMULA")&&csv.csv.includes("'+155"),'CSV injection neutralized');check(!csv.csv.includes(r.id)&&!csv.csv.includes(users[6]),'CSV omits IDs');await deny(()=>core('assignment',A,{user_id:users[3]}),'leader cannot grant authority');
 let task=await core('followup',A,{registrant_id:r.id,title:'Synthetic call',note:'Follow up',due_on:'2026-11-01',assigned_user_id:users[1]});check((await core('detail',A)).registrants.find(x=>x.id===r.id).followup_status==='open','campaign follow-up reflected');await deny(()=>core('followup',B,{registrant_id:r.id,title:'Cross scope'}),'cross-campaign follow-up denied');await deny(()=>core('followup',A,{registrant_id:r.id,id:task.id,revision:0,status:'completed'}),'stale follow-up denied');await core('followup',A,{registrant_id:r.id,id:task.id,revision:1,status:'completed'});check((await core('detail',A)).registrants.find(x=>x.id===r.id).followup_status==='completed','follow-up completion');await core('decision',A,{registrant_id:r.id,decision:'healing',notes:'Synthetic testimony'});check((await core('detail',A)).registrants.find(x=>x.id===r.id).decision==='healing','configurable native decision');await deny(()=>core('decision',A,{registrant_id:r.id,decision:'invented'}),'unknown decision denied');
 for(const n of [4,5,7]){await as(n);await deny(()=>core('detail',A),'expired/revoked/unverified assignment denied');}await as(6);check((await core('list')).length===0,'registration/enrollment grants no staff authority');await as(2);check((await core('list')).length===0,'Champion Life admin cannot infer SowGo scope');await deny(()=>core('opportunities',null,{organization_id:org}),'cross-org opportunity denied');
 await as(0);const templates=await work('templates',null,{organization_id:org}),o=await core('opportunity_save',null,{organization_id:org,details:{church_name:'Synthetic Host',city:'Test',country:'CA',preferred_months:'Spring'}});check((await core('list')).length===2,'interest does not create campaign');await deny(()=>core('opportunity_save',null,{organization_id:org,id:o.id,revision:1,stage:'approved',details:o.details}),'stage edit cannot bypass approval');
 const C=await core('approve',null,{organization_id:org,id:o.id,revision:1,code:'test_2027',name:'Test 2027',timezone:'America/Toronto',template_id:templates[0].id});check((await work('list',C.id)).steps.length===8,'explicit approval snapshots source workflow');check((await core('approve',null,{organization_id:org,id:o.id,revision:1})).id===C.id,'approval retry idempotent');
 const defs=[{key:'prepare',title:'Prepare',order:10,role:'outreach_coordinator',due_days:-30,reminder_days:7},{key:'flyer',title:'Flyer',order:20,depends_on:['prepare'],condition:{field:'flyers',equals:true}},{key:'final',title:'Final',order:30,depends_on:['prepare','flyer'],due_days:-14}];const t=await work('template_publish',null,{organization_id:org,template_key:'test_configurable',version:1,title:'Test',steps:defs});await deny(()=>work('template_publish',null,{organization_id:org,template_key:'cycle',version:1,title:'Cycle',steps:[{key:'a',title:'A',order:1,depends_on:['b']},{key:'b',title:'B',order:2,depends_on:['a']}]}),'cycles/unknown dependencies rejected');
 const o2=await core('opportunity_save',null,{organization_id:org,details:{church_name:'Test 2',city:'Other',country:'US'}}),D=await core('approve',null,{organization_id:org,id:o2.id,revision:1,code:'test_workflow',name:'Workflow',timezone:'America/Chicago',template_id:t.id});await core('configure',D.id,{revision:1,event_start:'2026-10-20T17:00:00Z',settings:{decision_types:['salvation'],workflow_inputs:{flyers:false}}});let steps=(await work('list',D.id)).steps;check(new Date(steps[0].due_at).toISOString()==='2026-09-20T17:00:00.000Z'&&new Date(steps[2].due_at).toISOString()==='2026-10-06T17:00:00.000Z','30/14-day due rules');check(steps[1].state==='not_applicable','flyers no skips action');await deny(()=>work('complete',D.id,{id:steps[2].id,revision:steps[2].revision}),'prerequisite gate');
 await work('assign',D.id,{id:steps[0].id,revision:steps[0].revision,role:'logistics_lead'});steps=(await work('list',D.id)).steps;check(steps[0].assigned_role==='logistics_lead','reassignment');await work('comment',D.id,{id:steps[0].id,revision:steps[0].revision,body:'Synthetic preparation'});check((await work('reminders',D.id)).state==='held','reminders held no fake sends');let events=(await work('list',D.id)).events;await work('reminders',D.id);check(events.length===(await work('list',D.id)).events.length,'cadence deduplication');await work('complete',D.id,{id:steps[0].id,revision:steps[0].revision});steps=(await work('list',D.id)).steps;check(steps[2].state!=='blocked','conditional skipped dependency allowed');await work('complete',D.id,{id:steps[2].id,revision:steps[2].revision});await work('reopen',D.id,{id:steps[0].id,revision:steps[0].revision,note:'Reviewed timing changed'});check((await work('list',D.id)).steps[0].status==='reopened','reopen');await work('template_publish',null,{organization_id:org,template_key:'test_configurable',version:2,title:'Next',steps:[{key:'new',title:'New',order:1}]});check((await work('list',D.id)).steps.length===3,'template edits do not rewrite snapshots');
 await db.exec('reset role');await deny(()=>q('update outreach_workflow_templates set title=$1 where id=$2',['Changed',t.id]),'published template immutable');await deny(()=>q('update outreach_campaign_steps set definition=$1 where id=$2',[{},steps[0].id]),'step definition immutable');await deny(()=>q('delete from outreach_campaign_audit'),'audit immutable');await as(0);
 const doc=await work('document_request',A,{category:'agreements',title:'Synthetic signed agreement',visibility:'restricted'});await deny(()=>work('document_uploaded',A,{id:doc.id}),'client cannot fake upload metadata');await q("insert into storage.objects(bucket_id,name,metadata)values('outreach-campaign-documents',$1,$2)",[doc.object_path,{size:40,mimetype:'application/pdf'}]);await work('document_uploaded',A,{id:doc.id});check((await work('list',A)).documents[0].status==='uploaded','real storage metadata finalizes');await as(1);check((await work('list',A)).documents.length===0,'leader cannot see restricted document');check((await q('select * from storage.objects')).rows.length===0,'private storage read denied');await deny(()=>q("insert into storage.objects(bucket_id,name)values('outreach-campaign-documents',$1)",[doc.object_path+'-bad']),'arbitrary upload path denied');
 await as(0);const internal=await work('document_request',A,{category:'flyers',title:'Flyer',visibility:'internal'});await as(1);await q("insert into storage.objects(bucket_id,name,metadata)values('outreach-campaign-documents',$1,$2)",[internal.object_path,{size:55,mimetype:'image/png'}]);await work('document_uploaded',A,{id:internal.id});check((await q('select * from storage.objects')).rows.length===1,'document capability scoped');await as(0);const v2=await work('document_request',A,{category:'flyers',title:'Replacement',visibility:'public',replaces_id:internal.id});check(v2.version===2&&v2.visibility==='internal'&&v2.object_path!==internal.object_path,'version retains visibility/history');
 let init=(await work('list',A)).steps;for(const i of [0,1])await work('complete',A,{id:init[i].id,revision:init[i].revision});await as(1);await deny(()=>work('complete',A,{id:init[2].id,revision:init[2].revision,note:'Attempted signature approval'}),'agreement approval administrator only');await as(0);await work('complete',A,{id:init[2].id,revision:init[2].revision,note:'Reviewed signed external agreement'});check((await work('list',A)).steps[2].status==='completed','signed external agreement reviewed');const resource=(await work('list',A)).resources.find(x=>x.resource_type==='training');await work('training_assign',A,{resource_id:resource.id,user_id:users[1]});await as(1);const training=(await work('list',A)).training[0];await work('training_status',A,{id:training.id,state:'completed'});check((await work('list',A)).training[0].completed_at,'training acknowledgement tracked');
 await as(0);await core('assignment',A,{user_id:users[1],role_key:'local_leader',capabilities:['view'],active:false,reason:'Synthetic immediate revocation'});await as(1);await deny(()=>core('detail',A),'revocation immediate for existing session');await deny(()=>work('list',A),'revocation clears workflow/doc access');await db.exec('reset role');check((await q('select count(*)::int n from organization_people')).rows[0].n===0,'no People duplication from bridge/workflow/decision');check((await q("select public from storage.buckets where id='outreach-campaign-documents'")).rows[0].public===false,'bucket always private');check((await q("select count(*)::int n from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname like 'outreach_%' and c.relkind='r' and not c.relrowsecurity")).rows[0].n===0,'all outreach tables RLS');check((await q("select count(*)::int n from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='private' and p.proname like 'outreach_%' and has_function_privilege('anon',p.oid,'EXECUTE')")).rows[0].n===0,'no anonymous privileged function execution');

 // Reviewed canonical identity must supersede the legacy claim and honor link revocation.
 await as(0);await deny(()=>core('configure',D.id,{status:'ready'}),'missing campaign revision fails closed');
 let state=await core('detail',D.id);await deny(()=>core('configure',D.id,{revision:state.campaign.revision,settings:{workflow_inputs:{bikes_quantity:-1}}}),'negative prize purchase quantity rejected');await deny(()=>core('configure',D.id,{revision:state.campaign.revision,settings:{workflow_inputs:{flyers:'yes'}}}),'malformed flyer condition rejected');await deny(()=>core('configure',D.id,{revision:state.campaign.revision,status:'ready'}),'reopened required step blocks event ready');
 await deny(()=>work('document_request',A,{title:'Expired request',category:'other',visibility:'internal',requested_from:users[4]}),'expired document recipient rejected');
 await deny(()=>work('document_request',A,{title:'Duplicate version',category:'flyers',visibility:'internal',replaces_id:internal.id}),'replacement history cannot fork duplicate versions');
 await deny(()=>work('document_uploaded',B,{id:doc.id}),'cross-campaign document identifier denied');
 check((await work('list',C.id)).resources.length===5,'new campaigns receive campaign-scoped source resources');
 check((await core('list',null,{country:'CA',city:'Test'})).length===1&&(await core('list',null,{city:'Unknown'})).length===0,'dashboard country/city filters enforced server-side');
 check((await core('detail',A)).summary.registrations===2&&(await core('detail',A)).summary.rededications===1,'dashboard campaign summaries');
 await db.exec('reset role');await q("insert into organization_staff_permissions(organization_id,user_id,permission) values($1,$2,'people.read'),($1,$2,'people.create')",[org,users[0]]);
 const person=(await q("insert into organization_people(organization_id,first_name,last_name,email) values($1,'Reviewed','Canonical','reviewed@example.test') returning id",[org])).rows[0].id;
 await as(0);await core('link_person',A,{registrant_id:r.id,person_id:person,revision:1,reason:'Explicit synthetic identity review'});await as(3);await deny(()=>core('detail',A),'ordinary member still denied after canonical linking');
 await as(0);let projection=(await core('detail',A)).registrants.find(x=>x.id===r.id);check(projection.first_name==='Reviewed'&&projection.discipleship_status==='not_enrolled','reviewed person requires verified portal link; legacy account not silently reused');
 await db.exec('reset role');await q("insert into portal_account_links(organization_id,person_id,user_id,verification_note)values($1,$2,$3,'Synthetic verified portal identity')",[org,person,users[6]]);await q("insert into lesson_progress(user_id,course_id,lesson_number,status)values($1,$2,3,'completed')",[users[6],course]);await as(0);
 projection=(await core('detail',A)).registrants.find(x=>x.id===r.id);check(projection.current_lesson===2&&projection.completed_lessons===2,'current lesson is earliest incomplete even with progress gaps');
 await core('contact_set',A,{person_id:person,role_key:'host_pastor'});check((await core('contacts',A))[0].name==='Reviewed Canonical','host contact reuses reviewed canonical People');
 await deny(()=>core('register_person',A,{person_id:person,reason:'Reviewed existing contact'}),'same person cannot duplicate campaign registration');
 await db.exec('reset role');await q('update portal_account_links set active=false where person_id=$1',[person]);await as(0);check((await core('detail',A)).registrants.find(x=>x.id===r.id).discipleship_status==='not_enrolled','portal revocation removes projected progress');
 await db.exec('reset role');await q('update portal_account_links set active=true where person_id=$1',[person]);await q('update course_enrollments set completed_at=now() where user_id=$1 and course_id=$2',[users[6],course]);await as(0);projection=(await core('detail',A)).registrants.find(x=>x.id===r.id);check(projection.discipleship_status==='completed'&&projection.current_lesson===null,'existing completed course state projected');
 await core('assignment',A,{email:'campaign-3@example.test',role_key:'local_leader',capabilities:['view'],reason:'Explicit synthetic view-only assignment'});await as(3);check((await core('list')).length===1,'verified exact email assignment remains campaign-only');await deny(()=>core('csv',A),'view-only assignment cannot export');await deny(()=>work('document_request',A,{title:'Forbidden',category:'other',visibility:'internal'}),'view-only assignment cannot write documents');check((await q('select count(*)::int n from organization_people')).rows[0].n===0,'new campaign-only leader still lacks org-wide People');
 await as(2);await work('template_publish',null,{organization_id:other,template_key:'test_configurable',version:1,title:'Separate organization',steps:[{key:'prepare',title:'Separate',order:1}]});check((await work('templates',null,{organization_id:other})).every(x=>x.organization_id===null||x.organization_id===other),'workflow version names independent with no cross-org template leakage');
 const foreignOpportunity=await core('opportunity_save',null,{organization_id:other,details:{church_name:'Separate Host',city:'Toronto',country:'CA'}});await deny(()=>core('approve',null,{organization_id:other,id:foreignOpportunity.id,revision:1,code:'foreign_2027',name:'Separate',timezone:'America/Toronto',template_id:t.id}),'cross-org workflow UUID cannot create campaign');
 await db.exec('reset role');await q("insert into organization_staff_directory(organization_id,user_id,display_name)values($1,$2,'Synthetic cross-brand admin')",[org,users[2]]);await q("insert into outreach_campaign_admins(organization_id,user_id,capability,reason)values($1,$2,'view','Explicit synthetic second-brand view')",[org,users[2]]);await as(2);check((await core('list')).length===4,'explicit Champion Life/SowGo administrator sees permitted campaigns');await deny(()=>core('configure',A,{revision:1,status:'closed'}),'view administrator cannot manage campaign');
 await db.exec('reset role');check((await q('select count(*)::int n from organization_people')).rows[0].n===1,'only explicitly reviewed synthetic Person created; no implicit People merges');

 console.log(`${count} campaign checks passed`);
}catch(e){console.error({message:e.message,detail:e.detail,where:e.where,stack:e.stack?.split('\n').slice(0,3).join('\n')});process.exitCode=1;}finally{await db.close();}
