// Local synthetic rendering only: every browser request is intercepted, no hosted backend/session.
import assert from'node:assert/strict';import{readFileSync,mkdirSync,writeFileSync}from'node:fs';import{resolve,join}from'node:path';import{pathToFileURL,fileURLToPath}from'node:url';import{context,hostContext,packet,campaign,user,opportunities}from'./fixtures/pre-event-context.mjs';
const{chromium}=await import(pathToFileURL(process.env.TEST_PLAYWRIGHT_MODULE||'/Users/davesmacbookpro/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs'));const root=resolve(fileURLToPath(new URL('../..',import.meta.url))),out=process.env.PHASE_F_SCREENSHOTS||'/private/tmp/phase-f-browser';mkdirSync(out,{recursive:true});const browser=await chromium.launch({executablePath:process.env.TEST_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});let count=0;const report=[];
try{for(const width of[390,768,1440]){const p=await browser.newPage({viewport:{width,height:1050}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',async route=>{const url=new URL(route.request().url()),path=url.pathname.replace(/^\//,'');if(path==='assets/js/champion-life-auth.js'){await route.fulfill({contentType:'text/javascript',body:'/* synthetic auth installed before page scripts */'});return}if(url.hostname!=='preview.example.test'||path==='assets/js/supabase-config.js'){await route.fulfill({contentType:'text/javascript',body:url.hostname==='challenges.cloudflare.com'?"window.turnstile={render:(node,o)=>{o.callback('synthetic');return 1},reset:()=>{}}":'/* isolated */'});return}try{const file=resolve(root,path);if(!file.startsWith(root+'/'))throw Error('path');await route.fulfill({body:readFileSync(file),contentType:path.endsWith('.js')?'text/javascript':path.endsWith('.css')?'text/css':path.endsWith('.png')?'image/png':'text/html'})}catch{await route.fulfill({status:404,body:'Not found'})}});
 await p.addInitScript(({ctx,hctx,pkt,uid,opps})=>{window.CHAMPION_LIFE_SUPABASE={url:'https://preview.example.test',outreachSiteKey:'synthetic'};window.ChampionLifeAuth={getUser:async()=>({id:uid}),client:{auth:{onAuthStateChange:()=>{}},rpc:async(name,p)=>{const host=location.pathname.endsWith('outreach-host.html');const data=p.p_action==='context'?(host?hctx:ctx):p.p_action==='packet_preview'?{snapshot:host?Object.fromEntries(Object.entries(pkt).filter(([k])=>!['personnel','inventory','meetups','lodging'].includes(k))):pkt,blockers:ctx.blockers}:p.p_action==='organizations'?{organizations:[{id:ctx.campaign.organization_id,name:'SowGo',manage:true}]}:p.p_action==='opportunities'?opps:p.p_action==='campaigns'?[{...ctx.campaign,workflow_percent:45,overdue:1,ready:false}]:p.p_action==='templates'?[{id:'w1',title:'Pre-Event Workflow',version:2}]:p.p_action==='hosts'?[]:p.p_action==='agreement_templates'?[ctx.agreement_version]:[];return{data}}}}},{ctx:context,hctx:hostContext(),pkt:packet,uid:user,opps:opportunities});
 async function capture(name){await p.waitForTimeout(80);const sizes=await p.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert(sizes.scroll<=width,`${name} overflow ${JSON.stringify(sizes)}`);assert.equal(errors.length,0,errors.join('; '));await p.screenshot({path:join(out,`${width}-${name}.png`),fullPage:true});report.push({width,screen:name,overflow:false,errors:0});count++}
 await p.goto('https://preview.example.test/outreach-interest.html');await p.getByText('Submit outreach interest',{exact:true}).waitFor();await capture('interest');await p.goto('https://preview.example.test/staff-outreach-pre-event.html');await p.getByText('Pre-event campaign board',{exact:true}).waitFor();await capture('multi-campaign');await p.getByText('Opportunity pipeline',{exact:true}).click();await p.getByText('Outreach opportunities',{exact:true}).waitFor();await capture('opportunities');await p.getByText('Review / update',{exact:true}).click();await capture('manual-opportunity');await p.goto('https://preview.example.test/staff-outreach-pre-event.html?campaign='+campaign);await p.getByText('Readiness',{exact:true}).waitFor();await capture('readiness');for(const[tab,key]of[['Your tasks','workflow'],['Agreement','agreement'],['Documents','documents'],['Training','training'],['Event information','event'],['Onboarding','onboarding'],['Event packet','packet']]){await p.getByRole('button',{name:tab,exact:true}).click();await capture(key)}await p.goto('https://preview.example.test/outreach-host.html?campaign='+campaign);await p.getByText('HOST CHURCH PORTAL',{exact:true}).waitFor();await capture('host');await p.close()}
writeFileSync(join(out,'report.json'),JSON.stringify({checks:count,results:report},null,2));console.log(`${count} local browser screens PASS; 390 / 768 / 1440; no overflow or page errors; ${out}`);
}finally{await browser.close()}
