// Disposable socket-only local PostgreSQL. No remote DSN is accepted.
import assert from 'node:assert/strict';import {mkdtempSync,mkdirSync,readFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {execFileSync,execFile} from 'node:child_process';import {promisify} from 'node:util';import {randomUUID} from 'node:crypto';import {migrationOrder} from './migration-order.mjs';
const bin=process.env.TEST_POSTGRES_BIN||'',path=n=>bin?join(bin,n):n,root=mkdtempSync(join(tmpdir(),'campaign-pg-')),data=join(root,'data'),socket=join(root,'socket');mkdirSync(socket,{mode:0o700});const args=['-h',socket,'-p','55483','-U','postgres','-d','postgres','-X','-qAt','-v','ON_ERROR_STOP=1'],sql=s=>execFileSync(path('psql'),args,{input:s,encoding:'utf8',maxBuffer:8e6}),run=promisify(execFile);let started=false;
try{
 execFileSync(path('initdb'),['-D',data,'-U','postgres','--auth=trust','--no-locale','--encoding=UTF8'],{stdio:'inherit'});execFileSync(path('pg_ctl'),['-D',data,'-l',join(root,'server.log'),'-o',`-k ${socket} -p 55483 -c listen_addresses=''`,'-w','start'],{stdio:'ignore'});started=true;
 sql(readFileSync(new URL('fixtures/supabase-test-bootstrap.sql',import.meta.url),'utf8'));sql(readFileSync(new URL('../../supabase/bootstrap/automatic-rls.sql',import.meta.url),'utf8'));for(const f of migrationOrder)sql(readFileSync(new URL('../../supabase/migrations/'+f,import.meta.url),'utf8'));
 const campaign=sql("select id from outreach_campaigns where code='bessemer_al_2026'").trim(),user=randomUUID(),p=randomUUID(),pool=randomUUID(),otherPool=randomUUID();
 sql(`insert into auth.users(id,email,email_confirmed_at)values('${user}','synthetic-concurrency@example.test',now());insert into outreach_campaign_assignments(campaign_id,user_id,role_key,capabilities,reason)values('${campaign}','${user}','internal_team',array['view','draw'],'Synthetic concurrent operator');insert into outreach_prize_participants(id,campaign_id,checked_in_at)values('${p}','${campaign}',now());insert into outreach_prize_pools(id,campaign_id,name,unclaimed_policy)values('${pool}','${campaign}','Bike','remain_eligible'),('${otherPool}','${campaign}','Tablet','remain_eligible');insert into outreach_prize_pool_entries(campaign_id,pool_id,participant_id)values('${campaign}','${pool}','${p}'),('${campaign}','${otherPool}','${p}');`);
 const send=statement=>run(path('psql'),[...args,'-c',`set request.jwt.claim.sub='${user}';${statement}`],{maxBuffer:1e6}).then(x=>x.stdout.trim());
 const numbers=await Promise.all(Array.from({length:16},()=>send(`select private.outreach_drawing_number('${campaign}','${p}');`)));assert.equal(new Set(numbers).size,1);assert.equal(Number(sql('select count(*) from outreach_drawing_numbers')),1);console.log('PASS 16 concurrent number requests return one immutable number');
 const results=await Promise.allSettled(Array.from({length:16},(_,i)=>send(`select private.outreach_prize_select('${campaign}','${i%2?pool:otherPool}','Synthetic prize');`)));const accepted=results.filter(x=>x.status==='fulfilled');assert.equal(accepted.length,1);assert(results.filter(x=>x.status==='rejected').every(x=>x.reason.stderr.includes('No eligible checked-in participant')));const draw=JSON.parse(accepted[0].value).draw_id;console.log('PASS 16 concurrent cross-pool draws: one reservation, no double selection');
 const claims=await Promise.allSettled(Array.from({length:12},()=>send(`select private.outreach_prize_resolve('${campaign}','${draw}','claimed');`)));assert.equal(claims.filter(x=>x.status==='fulfilled').length,1);assert.equal(Number(sql('select count(*) from outreach_prize_wins')),1);assert.equal(Number(sql("select count(*) from outreach_prize_draw_history where kind='claimed'")),1);console.log('PASS 12 concurrent claims: exactly one permanent win and one claim audit');
 await assert.rejects(()=>send(`select private.outreach_prize_select('${campaign}','${pool}','Bike after win');`));await assert.rejects(()=>send(`select private.outreach_prize_select('${campaign}','${otherPool}','Tablet after win');`));console.log('PASS one-win exclusion persists across both categories');
}finally{if(started)execFileSync(path('pg_ctl'),['-D',data,'-m','fast','-w','stop'],{stdio:'ignore'});rmSync(root,{recursive:true,force:true});}
