// True local PostgreSQL overlap on a disposable socket-only cluster. No remote DSN or secrets.
import assert from'node:assert/strict';import{mkdtempSync,mkdirSync,readFileSync,rmSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';import{execFileSync,execFile}from'node:child_process';import{promisify}from'node:util';import{randomUUID as uuid}from'node:crypto';import{migrationOrder}from'./migration-order.mjs';
const bin=process.env.TEST_POSTGRES_BIN||'/opt/homebrew/opt/postgresql@17/bin',exe=n=>join(bin,n),root=mkdtempSync(join(tmpdir(),'phased-pg-')),data=join(root,'data'),socket=join(root,'socket');mkdirSync(socket);const args=['-h',socket,'-p','55489','-U','postgres','-d','postgres','-X','-qAt','-v','ON_ERROR_STOP=1'],sql=s=>execFileSync(exe('psql'),args,{input:s,encoding:'utf8',maxBuffer:12e6}),run=promisify(execFile),lit=v=>"'"+String(v).replaceAll("'","''")+"'";let started=false;
const overlap=rows=>{const points=rows.flatMap(r=>[[Number(r.start),1],[Number(r.end),-1]]).sort((a,b)=>a[0]-b[0]||a[1]-b[1]);let n=0,max=0;for(const[,v]of points){n+=v;max=Math.max(max,n)}return max};
try{execFileSync(exe('initdb'),['-D',data,'-U','postgres','--auth=trust','--no-locale','--encoding=UTF8'],{stdio:'pipe'});execFileSync(exe('pg_ctl'),['-D',data,'-l',join(root,'server.log'),'-o',"-k "+socket+" -p 55489 -c listen_addresses=''",'-w','start'],{stdio:'ignore'});started=true;sql(readFileSync(new URL('fixtures/supabase-test-bootstrap.sql',import.meta.url),'utf8'));sql(readFileSync(new URL('../../supabase/bootstrap/automatic-rls.sql',import.meta.url),'utf8'));for(const f of migrationOrder)sql(readFileSync(new URL('../../supabase/migrations/'+f,import.meta.url),'utf8'));
 const c=sql("select id from outreach_campaigns where code='bessemer_al_2026'").trim(),user=uuid(),session=uuid(),pools=[uuid(),uuid(),uuid()];sql("insert into auth.users(id,email,email_confirmed_at)values('"+user+"','phase-d-race@example.test',now());insert into outreach_campaign_assignments(campaign_id,user_id,role_key,capabilities,reason)values('"+c+"','"+user+"','internal_team',array['view','prize.view','prize.manage','prize.draw','prize.claim'],'Synthetic Phase D concurrency authority');insert into outreach_prize_settings(campaign_id,digital_enabled,drawing_enabled,operation_mode,present_to_win)values('"+c+"',true,true,'hybrid',true);insert into outreach_prize_draw_sessions(id,campaign_id,status,started_by)values('"+session+"','"+c+"','active','"+user+"');");
 for(const [i,pool]of pools.entries())sql("insert into outreach_prize_pools(id,campaign_id,name,display_name,pool_key,quantity,draw_order,unclaimed_policy)values('"+pool+"','"+c+"','Pool "+(i+1)+"','Pool "+(i+1)+"','pool-"+(i+1)+"',1,"+(i+1)+",'exclude_participant');");
 const participants=[...Array(18)].map(()=>uuid());for(const p of participants)sql("insert into outreach_prize_participants(id,campaign_id,checked_in_at,active)values('"+p+"','"+c+"',now(),true);");sql("set request.jwt.claim.sub='"+user+"';"+participants.slice(0,2).map(p=>"select private.outreach_prize_assign_number('"+c+"','"+p+"');").join(''));for(const pool of pools)sql("insert into outreach_prize_pool_locks(campaign_id,session_id,pool_id,eligible_count)values('"+c+"','"+session+"','"+pool+"',18);");
 for(const pool of pools.slice(0,2))sql("insert into outreach_prize_pool_entries(campaign_id,pool_id,participant_id)values('"+c+"','"+pool+"','"+participants[0]+"');");for(const p of participants.slice(1))sql("insert into outreach_prize_pool_entries(campaign_id,pool_id,participant_id)values('"+c+"','"+pools[2]+"','"+p+"');");
 sql("create table public.phased_barrier(run uuid,worker integer,pid integer,primary key(run,worker));create policy phased_barrier_test on public.phased_barrier for all to authenticated using(true) with check(true);grant select,insert on phased_barrier to authenticated;create function public.phased_race(run uuid,n integer,action text,c uuid,p jsonb)returns jsonb language plpgsql security definer as $$declare began numeric;answer jsonb;outcome text:='success';code text;deadline timestamptz:=clock_timestamp()+interval '15 seconds';begin while(select count(*) from public.phased_barrier b where b.run=phased_race.run)<n loop if clock_timestamp()>deadline then raise exception 'Barrier timeout';end if;perform pg_sleep(.01);end loop;began:=extract(epoch from clock_timestamp());begin if action='number' then answer:=to_jsonb(private.outreach_prize_assign_number(c,(p->>'participant_id')::uuid));else answer:=public.outreach_prize_workspace(action,c,p);end if;exception when others then outcome:='safe_denial';get stacked diagnostics code=returned_sqlstate;answer:=jsonb_build_object('code',code);end;perform pg_sleep(.25);return jsonb_build_object('pid',pg_backend_pid(),'start',began,'end',extract(epoch from clock_timestamp()),'outcome',outcome,'result',answer);end$$;grant execute on function phased_race(uuid,integer,text,uuid,jsonb) to authenticated;");
 const coordinator=execFile(exe('psql'),args,{maxBuffer:1e6});coordinator.stdin.write('select pg_backend_pid();\n');const coord=await new Promise((resolve,reject)=>{coordinator.stdout.once('data',s=>resolve(Number(s.toString().trim())));coordinator.once('error',reject)});
 async function group(label,action,payloads){const key=uuid(),n=payloads.length;const rows=await Promise.all(payloads.map((p,i)=>run(exe('psql'),args.concat(['-c',"set request.jwt.claim.sub='"+user+"';set role authenticated;insert into phased_barrier values('"+key+"',"+i+",pg_backend_pid());",'-c',"select phased_race('"+key+"',"+n+","+lit(action)+",'"+c+"',"+lit(JSON.stringify(p))+"::jsonb);"]),{maxBuffer:2e6}).then(r=>JSON.parse(r.stdout.trim()))));assert.equal(new Set(rows.map(r=>r.pid)).size,n);assert(rows.every(r=>r.pid!==coord));assert.equal(overlap(rows),n);console.log('PASS '+label+' '+JSON.stringify({workers:n,distinct_backends:n,coordinator:coord,server_interval_overlap:overlap(rows),success:rows.filter(x=>x.outcome==='success').length,safe_denial:rows.filter(x=>x.outcome==='safe_denial').length}));return rows}
 try{
  const numberRows=await group('sixteen concurrent number assignments','number',participants.slice(2).map(participant_id=>({participant_id})));assert.equal(numberRows.filter(x=>x.outcome==='success').length,16);assert.equal(Number(sql("select count(*) from outreach_drawing_numbers where campaign_id='"+c+"'")),18);assert.equal(Number(sql("select count(distinct number) from outreach_drawing_numbers where campaign_id='"+c+"'")),18);
  const cross=await group('same participant across two pools','draw',[{pool_id:pools[0]},{pool_id:pools[1]}]);assert.equal(Number(sql("select count(*) from outreach_prize_draws where participant_id='"+participants[0]+"'")),1);assert.equal(cross.filter(x=>x.outcome==='success').length,1);
  const first=sql("select id from outreach_prize_draws where participant_id='"+participants[0]+"'").trim();await group('duplicate claim canonical','claim',Array(8).fill({draw_id:first}));assert.equal(Number(sql("select count(*) from outreach_prize_wins where participant_id='"+participants[0]+"'")),1);assert.equal(Number(sql("select count(*) from outreach_prize_draw_history where draw_id='"+first+"' and kind='claimed'")),1);
  const finalDraws=await group('two operators same final prize','draw',Array(8).fill({pool_id:pools[2]}));assert.equal(finalDraws.filter(x=>x.outcome==='success').length,8);assert.equal(Number(sql("select count(*) from outreach_prize_draws where pool_id='"+pools[2]+"'")),1);const final=sql("select id from outreach_prize_draws where pool_id='"+pools[2]+"'").trim();await group('final inventory unit claim','claim',Array(8).fill({draw_id:final}));assert.equal(Number(sql("select count(*) from outreach_prize_wins w join outreach_prize_draws d on d.id=w.draw_id where d.pool_id='"+pools[2]+"'")),1);
  const winner=sql("select participant_id from outreach_prize_draws where id='"+final+"'").trim();const denied=await group('winner eligibility re-enable denied','participant_set',Array(8).fill({participant_id:winner,pool_id:pools[1],active:true}));assert.equal(denied.filter(x=>x.outcome==='safe_denial').length,8);assert.equal(Number(sql("select count(*) from outreach_prize_pool_entries where participant_id='"+winner+"' and active")),0);
  console.log('PASS Phase D races: maximum one cross-pool win, one final-unit award, one canonical claim and no winner re-enable');
 }finally{coordinator.stdin.end();await new Promise(r=>coordinator.once('exit',r))}
}finally{if(started)execFileSync(exe('pg_ctl'),['-D',data,'-m','fast','-w','stop'],{stdio:'ignore'});rmSync(root,{recursive:true,force:true})}
