import assert from 'node:assert/strict';import {PGlite} from '@electric-sql/pglite';import {readFileSync} from 'node:fs';import {randomUUID} from 'node:crypto';import {migrationOrder} from './migration-order.mjs';
const db=new PGlite(),q=(s,a=[])=>db.query(s,a);let checks=0;const check=(v,m)=>{assert.ok(v,m);checks++;console.log('PASS '+m)},deny=async(f,m)=>{await assert.rejects(f);check(true,m)};
try{
 await db.exec(readFileSync(new URL('fixtures/supabase-test-bootstrap.sql',import.meta.url),'utf8'));await db.exec(readFileSync(new URL('../../supabase/bootstrap/automatic-rls.sql',import.meta.url),'utf8'));for(const f of migrationOrder)await db.exec(readFileSync(new URL('../../supabase/migrations/'+f,import.meta.url),'utf8'));
 const A=(await q("select id from outreach_campaigns where code='bessemer_al_2026'")).rows[0].id,B=(await q("select id from outreach_campaigns where code='huntsville_al_2026'")).rows[0].id,user=randomUUID();await q("insert into auth.users(id,email,email_confirmed_at)values($1,'synthetic-draw@example.test',now())",[user]);await q("select set_config('request.jwt.claim.sub',$1,false)",[user]);await deny(()=>q('select private.outreach_prize_select($1,$2,$3)',[A,randomUUID(),'Bike']),'draw permission must be explicit');await q("insert into outreach_campaign_assignments(campaign_id,user_id,role_key,capabilities,reason)values($1,$2,'internal_team',array['view','draw'],'Synthetic draw assignment')",[A,user]);
 const p=randomUUID(),notChecked=randomUUID(),wrongPool=randomUUID(),pool=randomUUID(),tablet=randomUUID();for(const id of [p,notChecked,wrongPool])await q('insert into outreach_prize_participants(id,campaign_id,checked_in_at)values($1,$2,$3)',[id,A,id===notChecked?null:new Date()]);for(const [id,name] of [[pool,'Bike'],[tablet,'Tablet']])await q("insert into outreach_prize_pools(id,campaign_id,name,unclaimed_policy)values($1,$2,$3,'remain_eligible')",[id,A,name]);for(const id of [p,notChecked])for(const pl of [pool,tablet])await q('insert into outreach_prize_pool_entries(campaign_id,pool_id,participant_id)values($1,$2,$3)',[A,pl,id]);
 const numbers=[];for(const id of [p,notChecked,wrongPool])numbers.push((await q('select private.outreach_drawing_number($1,$2) n',[A,id])).rows[0].n);check(numbers.every(x=>/^[1-9][0-9]{5}$/.test(x))&&new Set(numbers).size===3,'cryptographic six-digit campaign-unique numbers');check((await q('select private.outreach_drawing_number($1,$2) n',[A,p])).rows[0].n===numbers[0],'one number per participant idempotent');await deny(()=>q('insert into outreach_drawing_numbers(campaign_id,participant_id,number)values($1,$2,$3)',[A,p,'999999']),'database prevents second number');
 await deny(()=>q('select private.outreach_drawing_number($1,$2)',[B,p]),'cross-campaign number denied');let draw=(await q('select private.outreach_prize_select($1,$2,$3) v',[A,pool,'Bike'])).rows[0].v;check(draw.number===numbers[0],'unchecked and wrong-pool participants excluded');check(Object.keys(draw).sort().join(',')==='draw_id,number,prize','display projection no name/phone/participant');await deny(()=>q('select private.outreach_prize_select($1,$2,$3)',[A,tablet,'Tablet']),'pending selection reserves across pools');
 await q('select private.outreach_prize_resolve($1,$2,$3)',[A,draw.draw_id,'unclaimed']);check((await q('select count(*)::int n from outreach_prize_wins')).rows[0].n===0,'unclaimed/not-present is not a win');draw=(await q('select private.outreach_prize_select($1,$2,$3) v',[A,tablet,'Tablet'])).rows[0].v;check(draw.number===numbers[0],'explicit remain-eligible unclaimed policy');await q('select private.outreach_prize_resolve($1,$2,$3)',[A,draw.draw_id,'claimed']);check((await q('select count(*)::int n from outreach_prize_wins')).rows[0].n===1,'claim creates one immutable global win');await deny(()=>q('select private.outreach_prize_select($1,$2,$3)',[A,pool,'Bike']),'winner permanently excluded from bike after tablet');await deny(()=>q('select private.outreach_prize_resolve($1,$2,$3)',[A,draw.draw_id,'unclaimed']),'cannot undo a claimed win');await deny(()=>q('delete from outreach_prize_wins'),'trusted delete cannot reenable winner');await deny(()=>q("update outreach_prize_draw_history set kind='unclaimed'"),'draw audit immutable');await deny(()=>q('update outreach_drawing_numbers set number=$1',['111111']),'number immutable');
 const newp=randomUUID();await q('insert into outreach_prize_participants(id,campaign_id,checked_in_at)values($1,$2,now())',[newp,A]);await q('select private.outreach_drawing_number($1,$2)',[A,newp]);await q('insert into outreach_prize_pool_entries(campaign_id,pool_id,participant_id)values($1,$2,$3)',[A,pool,newp]);await q("update outreach_prize_pools set unclaimed_policy='exclude_participant' where id=$1",[pool]);draw=(await q('select private.outreach_prize_select($1,$2,$3) v',[A,pool,'Bike'])).rows[0].v;await q('select private.outreach_prize_resolve($1,$2,$3)',[A,draw.draw_id,'unclaimed']);await deny(()=>q('select private.outreach_prize_select($1,$2,$3)',[A,pool,'Bike']),'explicit exclude-participant policy');
 await db.exec('set role authenticated');for(const table of ['outreach_prize_wins','outreach_prize_participants','outreach_prize_draw_history'])await deny(()=>q('select * from '+table),'dormant '+table+' no client read');await deny(()=>q('select private.outreach_prize_select($1,$2,$3)',[A,pool,'Bike']),'no browser draw API in Phase A');await deny(()=>q('delete from outreach_prize_wins'),'direct API cannot reenable winner');await db.exec('reset role');check((await q("select count(*)::int n from outreach_campaign_events where kind in ('prize.won','prize.unclaimed') and delivery_state='held'")).rows[0].n===3,'prize events held not fake SMS');console.log(`${checks} dormant prize integrity checks passed`);
}catch(e){console.error({message:e.message,where:e.where});process.exitCode=1;}finally{await db.close();}
