import assert from 'node:assert/strict';import{JSDOM,VirtualConsole}from'jsdom';import{readFileSync}from'node:fs';import{config,campaign,user,response}from'./fixtures/outreach-registration-ui.mjs';let count=0;const ok=(v,m)=>{assert.ok(v,m);count++;console.log('PASS '+m)},tick=()=>new Promise(r=>setTimeout(r,30));
function base(){const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const d=new JSDOM('<div id="outreach-registration-staff"></div>',{url:'https://preview.example.test/staff-outreach-registration.html?campaign='+campaign,runScripts:'outside-only',virtualConsole:vc}),w=d.window;for(const s of['outreach-staff-common.js','outreach-registration-form.js'])w.eval(readFileSync(new URL('../../assets/js/'+s,import.meta.url),'utf8'));return{dom:d,w,d:w.document,errors}}
function set(t,label,value){const l=[...t.d.querySelectorAll('label')].find(l=>l.firstChild?.textContent===label||l.textContent===label);assert(l,label);const i=l.querySelector('input,select,textarea');if(i.type==='checkbox')i.checked=value;else i.value=value;return i}
async function click(t,text){const b=[...t.d.querySelectorAll('button')].find(b=>b.textContent===text);assert(b,text);b.click();await tick()}
const p=base(),root=p.d.getElementById('outreach-registration-staff'),sent=[];const editor=p.w.OutreachRegistrationForm.mount(root,config,async body=>{sent.push(body);throw Error('Synthetic connection interruption')});editor.addMember();ok(editor.rows.length===2,'family editor supports multiple attendees');const fields=editor.form.querySelectorAll('input');set(p,'Primary adult first name','Morgan');set(p,'Primary adult last name','Fixture');set(p,'Email','synthetic@example.test');set(p,'Mobile phone','+15555550100');set(p,'Address','Synthetic address');for(const [i,r]of editor.rows.entries()){r.first.value=i?'Alex':'Morgan';r.last.value='Fixture';r.age.value=i?'9':'38';r.relationship.value=i?'child':'self';r.guardian.value=i?'Parent':'';r.cover.checked=true}set(p,'Typed legal name','Morgan Fixture');set(p,'Signer relationship','parent');set(p,'I have read and acknowledge this waiver.',true);set(p,'I am an adult with authority to sign for each selected attendee.',true);
editor.form.dispatchEvent(new p.w.Event('submit',{bubbles:true,cancelable:true}));await tick();ok(sent.length===1&&sent[0].attendees.length===2,'public editor sends individual adult/minor payload');ok(sent[0].consents.marketing===false,'marketing is not inferred');ok(sent[0].waiver.covered_keys.length===2,'explicit coverage keys sent');ok(p.d.body.textContent.includes('Synthetic connection interruption'),'network failure visible and no false confirmation');editor.form.dispatchEvent(new p.w.Event('submit',{bubbles:true,cancelable:true}));await tick();ok(JSON.stringify(sent[0])===JSON.stringify(sent[1]),'ambiguous failure retry preserves exact payload/keys');const stored=p.w.sessionStorage.getItem('outreach-registration-keys:'+config.slug);ok(!stored.includes('Morgan')&&!stored.includes('synthetic@example'),'browser stores keys only no PII');root.replaceChildren();const refreshed=p.w.OutreachRegistrationForm.mount(root,config,async()=>{});refreshed.addMember();ok(refreshed.requestKey===editor.requestKey&&refreshed.rows[1].key===editor.rows[1].key,'refresh maintains submission and attendee identity keys');p.w.OutreachRegistrationForm.confirmation(root,config,{reference:'R-ABCDEF0123456789',attendee_count:2},sent[0]);ok(p.d.body.textContent.includes('REGISTRATION RECEIVED')&&p.d.body.textContent.includes('R-ABCDEF0123456789'),'confirmation reference and household summary');ok(p.d.body.textContent.includes('Event-day check-in is required'),'confirmation preserves present-to-win rule');ok(p.d.body.textContent.includes('No email or text confirmation has been sent.'),'no false messaging claim');ok(p.errors.length===0,'public form no console error');p.dom.window.close();
const t=base(),calls=[];let blocked=false,signed=true,listener;t.w.URL.createObjectURL=()=> 'blob:fixture';t.w.URL.revokeObjectURL=()=>{};t.w.HTMLAnchorElement.prototype.click=function(){calls.push({download:this.download})};t.w.print=()=>calls.push({print:true});t.w.ChampionLifeAuth={getUser:async()=>signed?{id:user}:null,client:{auth:{onAuthStateChange:fn=>listener=fn},rpc:async(name,p)=>{calls.push({name,p});return blocked?{error:{code:'42501'}}:{data:response(name,p)}}}};t.w.eval(readFileSync(new URL('../../assets/js/outreach-registration-staff.js',import.meta.url),'utf8'));await tick();ok(t.d.body.textContent.includes('Household lookup'),'staff registration list');ok(!t.d.querySelector('[role=status]'),'loading state cleared');await click(t,'Open household');ok(t.d.body.textContent.includes('Alex Fixture')&&t.d.body.textContent.includes('Guardian: Parent'),'household detail attendee and guardian');ok(t.d.body.textContent.includes('Waiver covered'),'check-in coverage shown');await click(t,'Check in attendee');ok(calls.some(c=>c.p?.p_action==='checkin'&&c.p.p_payload.attendee_id),'per-attendee check-in request');await click(t,'Export CSV');ok(calls.some(c=>c.p?.p_action==='csv')&&calls.some(c=>c.download),'authorized scoped CSV download');await click(t,'Print backup roster');ok(t.d.querySelector('table')&&t.d.body.textContent.includes('Guardian / Phone'),'private printable fallback');await click(t,'Add walk-up');ok(t.d.body.textContent.includes('Walk-up household')&&t.d.querySelector('form'),'walkup uses native shared family editor');await click(t,'Configuration');ok(t.d.body.textContent.includes('Publish approved waiver version')&&t.d.body.textContent.includes('Prize choices JSON'),'campaign configurable waiver/prize catalog');await click(t,'Registrations');blocked=true;await click(t,'Open household');ok(t.d.body.textContent.includes('Registration access unavailable')&&!t.d.body.textContent.includes('Alex Fixture')&&!t.d.querySelector('input'),'403 clears protected content');ok(t.d.querySelector('a[href="staff-home.html"]'),'denial returns to dedicated Staff Dashboard');blocked=false;await t.w.dispatchEvent(new t.w.Event('focus'));await tick();signed=false;listener('SIGNED_OUT',null);await tick();ok(t.d.body.textContent.includes('Sign in to continue')&&!t.d.body.textContent.includes('Fixture'),'session expiry clears household');ok(t.errors.length===0,'staff UI no console error');t.dom.window.close();

// Exercise the real guest entrypoint with disconnected RPC/challenge mocks.
const publicSource=readFileSync(new URL('../../assets/js/outreach-registration-public.js',import.meta.url),'utf8');
async function guest(slug='synthetic-outreach',data=config){
 const t=base();t.dom.reconfigure({url:'https://preview.example.test/outreach-register.html?campaign='+slug});
 t.d.body.innerHTML='<img id="registration-logo"><p id="registration-brand-name"></p><h1 id="registration-title"></h1><div id="outreach-registration-app"></div>';
 const calls=[];let challenge,resets=0;
 t.w.CHAMPION_LIFE_SUPABASE={url:'https://acceptance.example.test',publishableKey:'SYNTHETIC_PUBLIC',outreachSiteKey:'SYNTHETIC_SITE'};
 t.w.supabase={createClient:(url,key,opts)=>{calls.push({url,key,opts});return{rpc:async(name,p)=>{calls.push({name,p});return{data}}}}};
 t.w.turnstile={render:(el,opts)=>{challenge=opts;return 1},reset:()=>resets++};
 t.w.AbortSignal.timeout=()=>new t.w.AbortController().signal;
 t.w.fetch=async(url,init)=>{calls.push({url,init});return{ok:true,status:200,json:async()=>({accepted:true,reference:'R-ABCDEF0123456789',attendee_count:1})}};
 t.w.eval(publicSource);await tick();return{...t,calls,get challenge(){return challenge},get resets(){return resets}};
}
const g=await guest('synthetic-outreach',{...config,organization_name:'SowGo',logo_asset:'assets/images/sowgo-logo-light.png',waiver_required:false});
ok(g.calls[0].opts.auth.persistSession===false&&g.calls[0].opts.auth.detectSessionInUrl===false,'guest client does not require or persist an account session');
ok(g.d.getElementById('registration-logo').getAttribute('src')==='assets/images/sowgo-logo-light.png'&&g.d.getElementById('registration-brand-name').textContent==='SowGo · OUTREACH','owning campaign brand reuses approved logo');
ok(g.challenge.action==='outreach-registration','guest challenge uses dedicated action');
set(g,'Primary adult first name','Morgan');set(g,'Primary adult last name','Fixture');set(g,'Email','synthetic@example.test');set(g,'Mobile phone','+15555550100');set(g,'Address','Synthetic address');set(g,'Attendee first name','Morgan');set(g,'Attendee last name','Fixture');set(g,'Age','38');
const submitGuest=async()=>{g.d.querySelector('form').dispatchEvent(new g.w.Event('submit',{bubbles:true,cancelable:true}));await tick()};
await submitGuest();ok(g.d.body.textContent.includes('Complete the security check first.')&&!g.calls.some(c=>c.init),'missing challenge prevents gateway call');
set(g,'Primary adult first name','Changed');g.challenge.callback('synthetic-challenge');await submitGuest();
const sentGuest=JSON.parse(g.calls.find(c=>c.init).init.body);
ok(sentGuest.payload.waiver===null,'optional published waiver can be declined without signature');
ok(sentGuest.payload.first_name==='Changed','definite local rejection permits correction before retry');
ok(g.calls.find(c=>c.init).url==='https://acceptance.example.test/functions/v1/outreach-registration-submit'&&sentGuest.slug==='synthetic-outreach','guest submits through dedicated gateway with campaign slug');
ok(g.resets===1&&g.d.body.textContent.includes('REGISTRATION RECEIVED'),'successful guest bootstrap shows confirmation and resets challenge');
ok(g.errors.length===0,'guest entrypoint no console exception');g.dom.window.close();
const missing=await guest('synthetic-outreach',null);ok(missing.d.body.textContent.includes('Registration is not open.')&&!missing.d.querySelector('form'),'unavailable guest campaign fails closed');missing.dom.window.close();
console.log(`${count} Phase C DOM checks passed`);
