// True local PostgreSQL overlap on a disposable socket-only cluster. No remote DSN or secrets.
import assert from'node:assert/strict';import{mkdtempSync,mkdirSync,readFileSync,rmSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';import{execFileSync,execFile}from'node:child_process';import{promisify}from'node:util';import{randomUUID as uuid}from'node:crypto';import{migrationOrder}from'./migration-order.mjs';
const bin=process.env.TEST_POSTGRES_BIN||'/opt/homebrew/opt/postgresql@17/bin',exe=n=>join(bin,n),root=mkdtempSync(join(tmpdir(),'phasee-pg-')),data=join(root,'data'),socket=join(root,'socket');mkdirSync(socket);const args=['-h',socket,'-p','55490','-U','postgres','-d','postgres','-X','-qAt','-v','ON_ERROR_STOP=1'],sql=s=>execFileSync(exe('psql'),args,{input:s,encoding:'utf8',maxBuffer:15e6}),run=promisify(execFile),lit=v=>"'"+String(v).replaceAll("'","''")+"'";let started=false;
const overlap=rows=>{const pts=rows.flatMap(r=>[[Number(r.start),1],[Number(r.end),-1]]).sort((a,b)=>a[0]-b[0]||a[1]-b[1]);let n=0,max=0;for(const[,v]of pts){n+=v;max=Math.max(max,n)}return max};
try{execFileSync(exe('initdb'),['-D',data,'-U','postgres','--auth=trust','--no-locale','--encoding=UTF8'],{stdio:'pipe'});execFileSync(exe('pg_ctl'),['-D',data,'-l',join(root,'server.log'),'-o',"-k "+socket+" -p 55490 -c listen_addresses=''",'-w','start'],{stdio:'ignore'});started=true;sql(readFileSync(new URL('fixtures/supabase-test-bootstrap.sql',import.meta.url),'utf8'));sql(readFileSync(new URL('../../supabase/bootstrap/automatic-rls.sql',import.meta.url),'utf8'));for(const f of migrationOrder)sql(readFileSync(new URL('../../supabase/migrations/'+f,import.meta.url),'utf8'));
 const c=sql("select id from outreach_campaigns where code='bessemer_al_2026'").trim(),org=sql("select organization_id from outreach_campaigns where id='"+c+"'").trim(),user=uuid(),signup=uuid(),member=uuid(),template='e0000000-0000-4000-8000-000000000001';sql("insert into auth.users(id,email,email_confirmed_at)values('"+user+"','phase-e-race@example.test',now());insert into outreach_campaign_assignments(campaign_id,user_id,role_key,capabilities,reason)values('"+c+"','"+user+"','internal_team',array['view','ops.view','ops.manage','inventory.view','inventory.manage','issue.manage'],'Synthetic Phase E concurrency authority');set request.jwt.claim.sub='"+user+"';set role authenticated;select outreach_event_day_workspace('instantiate','"+c+"',jsonb_build_object('template_id','"+template+"'));reset role;insert into outreach_team_signups(id,campaign_id,organization_id,applicant_user_id,party_label)values('"+signup+"','"+c+"','"+org+"','"+user+"','Synthetic Phase E Race');insert into outreach_team_members(id,campaign_id,signup_id,organization_id,primary_applicant,first_name,last_name,email,relationship,age,attending,volunteering,status,transport_preference,travel_mode,lodging_preference)values('"+member+"','"+c+"','"+signup+"','"+org+"',true,'Race','Volunteer','race@example.test','self',35,true,true,'approved','own_transport','local_attendee','local');");
 const areas=sql("select id from outreach_event_areas where campaign_id='"+c+"' order by display_order limit 2").trim().split('\n'),item=sql("select id from outreach_event_checklist_items where campaign_id='"+c+"' order by display_order limit 1").trim(),inventory=sql("select id from outreach_event_inventory where campaign_id='"+c+"' order by item_name limit 1").trim();sql("update outreach_event_inventory set available_quantity=10,loaded_quantity=0,on_site_quantity=0,returned_quantity=0,missing_quantity=0,damaged_quantity=0,status='committed',revision=2 where id='"+inventory+"';");const issue=sql("set request.jwt.claim.sub='"+user+"';set role authenticated;select outreach_event_day_workspace('issue_save','"+c+"',jsonb_build_object('area_id','"+areas[0]+"','severity','needs_attention','issue','Synthetic race issue'))->>'id';").trim();
 sql("create table public.phasee_barrier(run uuid,worker integer,pid integer,primary key(run,worker));create policy phasee_barrier_test on public.phasee_barrier for all to authenticated using(true) with check(true);grant select,insert on phasee_barrier to authenticated;create function public.phasee_race(run uuid,n integer,action text,c uuid,p jsonb)returns jsonb language plpgsql security definer as $$declare began numeric;answer jsonb;outcome text:='success';code text;deadline timestamptz:=clock_timestamp()+interval '15 seconds';begin while(select count(*) from public.phasee_barrier b where b.run=phasee_race.run)<n loop if clock_timestamp()>deadline then raise exception 'Barrier timeout';end if;perform pg_sleep(.01);end loop;began:=extract(epoch from clock_timestamp());begin answer:=public.outreach_event_day_workspace(action,c,p);exception when others then outcome:='safe_denial';get stacked diagnostics code=returned_sqlstate;answer:=jsonb_build_object('code',code);end;perform pg_sleep(.25);return jsonb_build_object('pid',pg_backend_pid(),'start',began,'end',extract(epoch from clock_timestamp()),'outcome',outcome,'result',answer);end$$;grant execute on function phasee_race(uuid,integer,text,uuid,jsonb) to authenticated;");
 const coordinator=execFile(exe('psql'),args,{maxBuffer:1e6});coordinator.stdin.write('select pg_backend_pid();\n');const coord=await new Promise((resolve,reject)=>{coordinator.stdout.once('data',s=>resolve(Number(s.toString().trim())));coordinator.once('error',reject)});
 async function group(label,action,payloads){const key=uuid(),n=payloads.length;const rows=await Promise.all(payloads.map((p,i)=>run(exe('psql'),args.concat(['-c',"set request.jwt.claim.sub='"+user+"';set role authenticated;insert into phasee_barrier values('"+key+"',"+i+",pg_backend_pid());",'-c',"select phasee_race('"+key+"',"+n+","+lit(action)+",'"+c+"',"+lit(JSON.stringify(p))+"::jsonb);"]),{maxBuffer:2e6}).then(r=>JSON.parse(r.stdout.trim()))));assert.equal(new Set(rows.map(r=>r.pid)).size,n);assert(rows.every(r=>r.pid!==coord));assert.equal(overlap(rows),n);console.log('PASS '+label+' '+JSON.stringify({workers:n,distinct_backends:n,coordinator_separate:true,server_barrier_ready:n,max_overlapping_intervals:overlap(rows),success:rows.filter(x=>x.outcome==='success').length,safe_conflicts:rows.filter(x=>x.outcome==='safe_denial').length}));return rows}
 try{
  const checklist=await group('duplicate checklist completion', 'checklist_complete',Array(8).fill({item_id:item,revision:1,note:'Concurrent complete',quantity:'8',issue_flag:false}));assert.equal(checklist.filter(x=>x.outcome==='success').length,8);assert.equal(Number(sql("select count(*) from outreach_event_ops_history where subject_id='"+item+"' and kind='checklist_completed'")),1);assert.equal(sql("select completed::text from outreach_event_checklist_items where id='"+item+"'").trim(),'true');
  const counts=await group('competing inventory counts','inventory_save',Array(8).fill({id:inventory,revision:2,available_quantity:10,loaded_quantity:8,on_site_quantity:8,returned_quantity:0,missing_quantity:0,damaged_quantity:0,status:'on_site'}));assert.equal(counts.filter(x=>x.outcome==='success').length,1);assert.equal(counts.filter(x=>x.outcome==='safe_denial').length,7);assert.equal(sql("select loaded_quantity||':'||on_site_quantity||':'||revision from outreach_event_inventory where id='"+inventory+"'").trim(),'8:8:3');
  const resolves=await group('duplicate issue resolution','issue_resolve',Array(8).fill({issue_id:issue,revision:1,resolution_note:'Resolved once'}));assert.equal(resolves.filter(x=>x.outcome==='success').length,8);assert.equal(Number(sql("select count(*) from outreach_event_ops_history where subject_id='"+issue+"' and kind='issue_resolved'")),1);assert.equal(sql("select status from outreach_event_issues where id='"+issue+"'").trim(),'resolved');
  await group('same volunteer competing area assignment','area_member_set',areas.flatMap(a=>Array(4).fill({area_id:a,member_id:member,role:'volunteer',arrival_status:'assigned'})));assert.equal(Number(sql("select count(*) from outreach_event_area_members where member_id='"+member+"' and active")),1);
  const before=sql("select loaded_quantity||':'||on_site_quantity||':'||missing_quantity||':'||damaged_quantity||':'||revision from outreach_event_inventory where id='"+inventory+"'").trim();const invalid=await group('invalid final equipment counts rejected','inventory_save',Array(8).fill({id:inventory,revision:3,available_quantity:10,loaded_quantity:8,on_site_quantity:8,returned_quantity:0,missing_quantity:7,damaged_quantity:7,status:'damaged'}));assert.equal(invalid.filter(x=>x.outcome==='safe_denial').length,8);assert.equal(sql("select loaded_quantity||':'||on_site_quantity||':'||missing_quantity||':'||damaged_quantity||':'||revision from outreach_event_inventory where id='"+inventory+"'").trim(),before);
  console.log('PASS Phase E races: one canonical checklist and issue transition, one inventory winner, one active volunteer area and no impossible counts');
 }finally{coordinator.stdin.end();await new Promise(r=>coordinator.once('exit',r))}
}finally{if(started)execFileSync(exe('pg_ctl'),['-D',data,'-m','fast','-w','stop'],{stdio:'ignore'});rmSync(root,{recursive:true,force:true})}
