import {migrationOrder} from './migration-order.mjs';
import {PGlite} from '@electric-sql/pglite';
import {readFileSync,readdirSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
const db=new PGlite(),q=(s,a=[])=>db.query(s,a);let count=0;
const check=(v,m)=>{assert.ok(v,m);count++;console.log('PASS '+m)},deny=async(f,m)=>{await assert.rejects(f);check(true,m)};
await db.exec(readFileSync(new URL('fixtures/supabase-test-bootstrap.sql',import.meta.url),'utf8'));
await db.exec(readFileSync(new URL('../../supabase/bootstrap/automatic-rls.sql',import.meta.url),'utf8'));
for(const f of migrationOrder)await db.exec(readFileSync(new URL('../../supabase/migrations/'+f,import.meta.url),'utf8'));
const org=(await q("select id from organizations where slug='sowgo'")).rows[0].id,other=(await q("select id from organizations where slug='champion-life'")).rows[0].id;
const ids=Array.from({length:4},()=>randomUUID());
for(let n=0;n<4;n++){await q('insert into auth.users(id,email,email_confirmed_at) values($1,$2,$3)',[ids[n],`outreach-${n}@example.test`,n===3?null:new Date()]);await q("insert into organization_staff_directory(organization_id,user_id,display_name) values($1,$2,'Synthetic')",[org,ids[n]]);}
for(const key of ['outreach.view','outreach.manage','people.read','people.create','people.update','followup.read','followup.manage'])await q('insert into organization_staff_permissions(organization_id,user_id,permission)values($1,$2,$3)',[org,ids[0],key]);
for(const n of [1,3])await q("insert into organization_staff_permissions(organization_id,user_id,permission)values($1,$2,'outreach.view')",[org,ids[n]]);
const as=async(n)=>{await db.exec('reset role');await q("select set_config('request.jwt.claim.sub',$1,false)",[n==null?'':ids[n]]);await db.exec('set role '+(n==null?'anon':'authenticated'))};
// Simulate the privileged gateway for canonical/staff workflow tests only.
// Rate behavior has its own independent suite; clear windows between these cases.
const submit=async p=>{const role=(await q('select current_user as r')).rows[0].r;try{await db.exec('reset role; delete from private.outreach_abuse_windows; set role service_role');const value=(await q('select public.outreach_partner_gateway($1,$2) v',[p,'a'.repeat(64)])).rows[0].v;if(!value.accepted)throw Error('Denied');return value}finally{await db.exec('reset role; set role '+role)}},staff=(a,p={},o=org)=>q('select outreach_partner_workspace($1,$2,$3) v',[o,a,p]).then(x=>x.rows[0].v);
const payload=()=>({brand:'champion-life',source_path:'/outreach.html',request_key:randomUUID(),bot_field:'',fields:{'first-name':'Synthetic','last-name':'Partner',email:' Outreach@Example.test ','address-line-1':'1 Example Lane','address-line-2':'','city':'Test','state-province':'FL','postal-code':'32548',phone:'+1 (555) 555-1234','commitment-amount':'25.75','commitment-frequency':'Monthly'}});
await as(null);let p=payload();check((await submit(p)).accepted,'guest submission');check((await submit(p)).accepted,'identical replay');await deny(()=>submit({...p,brand:'sowgo'}),'changed-payload replay denied');
for(const extra of [{organization_id:other},{person_id:randomUUID()},{payment_status:'paid'},{marketing_consent:true}])await deny(()=>submit({...payload(),...extra}),'unsupported authority field rejected');
await deny(()=>submit({...payload(),brand:'other'}),'unknown brand denied');await deny(()=>submit({...payload(),source_path:'https://attacker.test/?secret=1'}),'source restricted to path');
for(const [key,value] of [['first-name',''],['email','no-email'],['phone','12'],['commitment-amount','0'],['commitment-amount','1.001'],['commitment-frequency','Daily'],['city','x'.repeat(101)],['email',{}]])await deny(()=>submit({...payload(),fields:{...p.fields,[key]:value}}),'field validation '+key);
await submit({...payload(),bot_field:'robot'});await deny(()=>q('select * from outreach_partner_intakes'),'anonymous read denied');await deny(()=>q('delete from outreach_partner_intakes'),'anonymous write denied');await deny(()=>staff('list'),'anonymous workspace denied');
await as(0);let rows=await staff('list');check(rows.length===1,'replay and honeypot create no duplicate');let r=await staff('detail',{id:rows[0].id});check(r.organization_id===org&&r.source_site==='champion_life','SowGo owns Champion Life source');check(r.raw_submission.email===p.fields.email&&r.commitment_amount===25.75,'raw source preserved; commitment stored');check(!('request_key'in r)&&!('payload_hash'in r),'private replay fields omitted');await deny(()=>staff('detail',{id:r.id},other),'cross organization denied');
await as(1);check((await staff('list')).length===1,'explicit outreach reader');await deny(()=>staff('review',{id:r.id,revision:r.revision}),'viewer cannot review');await as(2);await deny(()=>staff('list'),'ordinary authenticated account denied');await as(3);await deny(()=>staff('list'),'unverified staff denied');
await as(0);await staff('review',{id:r.id,revision:r.revision});await deny(()=>staff('review',{id:r.id,revision:r.revision}),'stale review rejected');r=await staff('detail',{id:r.id});check(r.status==='reviewed'&&!r.person_id,'review does not infer identity');
await staff('create_contact',{id:r.id,revision:r.revision});r=await staff('detail',{id:r.id});check(r.status==='linked'&&r.person_id,'reviewed contact creation');await staff('followup',{id:r.id,revision:r.revision});r=await staff('detail',{id:r.id});await staff('followup',{id:r.id,revision:r.revision});check((await staff('list'))[0].followup_status==='open','existing follow-up reused');
await as(null);const p2={...payload(),brand:'sowgo'};await submit(p2);await as(0);let r2=(await staff('list')).find(x=>x.id!==r.id);r2=await staff('detail',{id:r2.id});check(r2.source_site==='sowgo'&&r2.organization_id===org,'both brands one owner/backend');await deny(()=>staff('create_contact',{id:r2.id,revision:r2.revision}),'possible duplicate requires explicit review');await deny(()=>staff('link',{id:r2.id,revision:r2.revision,person_id:randomUUID()}),'unknown contact denied');await staff('link',{id:r2.id,revision:r2.revision,person_id:r.person_id});
await db.exec('reset role');check((await q('select count(*)::int n from organization_people')).rows[0].n===1,'no silent People duplication');check((await q("select count(*)::int n from person_organization_relationships where relationship='partner'")).rows[0].n===1,'one reviewed partner relationship');check((await q('select count(*)::int n from followup_tasks')).rows[0].n===1,'followup idempotency');check((await q('select count(*)::int n from portal_account_links')).rows[0].n===0,'no portal authority');check((await q('select count(*)::int n from organization_staff_permissions')).rows[0].n===9,'no staff or finance grants');check((await q('select count(*)::int n from organization_affiliations')).rows[0].n===0,'no Auth affiliation');check((await q('select email_normalized,phone_normalized from outreach_partner_intakes limit 1')).rows[0].email_normalized==='outreach@example.test','non-destructive normalization');
await db.close();console.log(`${count} canonical/staff workflow checks passed`);
