// True local PostgreSQL overlap on a disposable socket-only cluster. No remote DSN or secrets.
import assert from'node:assert/strict';import{mkdtempSync,mkdirSync,readFileSync,rmSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';import{execFileSync,execFile}from'node:child_process';import{promisify}from'node:util';import{randomUUID as uuid}from'node:crypto';import{migrationOrder}from'./migration-order.mjs';
const bin=process.env.TEST_POSTGRES_BIN||'/opt/homebrew/opt/postgresql@17/bin',exe=n=>join(bin,n),root=mkdtempSync(join(tmpdir(),'phasef-pg-')),data=join(root,'data'),socket=join(root,'socket');mkdirSync(socket);const args=['-h',socket,'-p','55491','-U','postgres','-d','postgres','-X','-qAt','-v','ON_ERROR_STOP=1'],sql=s=>execFileSync(exe('psql'),args,{input:s,encoding:'utf8',maxBuffer:15e6}),run=promisify(execFile),lit=v=>"'"+String(v).replaceAll("'","''")+"'";let started=false;
const overlap=rows=>{const pts=rows.flatMap(r=>[[Number(r.start),1],[Number(r.end),-1]]).sort((a,b)=>a[0]-b[0]||a[1]-b[1]);let n=0,max=0;for(const[,v]of pts){n+=v;max=Math.max(max,n)}return max};
try{execFileSync(exe('initdb'),['-D',data,'-U','postgres','--auth=trust','--no-locale','--encoding=UTF8'],{stdio:'pipe'});execFileSync(exe('pg_ctl'),['-D',data,'-l',join(root,'server.log'),'-o',"-k "+socket+" -p 55491 -c listen_addresses=''",'-w','start'],{stdio:'ignore'});started=true;sql(readFileSync(new URL('fixtures/supabase-test-bootstrap.sql',import.meta.url),'utf8'));sql(readFileSync(new URL('../../supabase/bootstrap/automatic-rls.sql',import.meta.url),'utf8'));for(const f of migrationOrder)sql(readFileSync(new URL('../../supabase/migrations/'+f,import.meta.url),'utf8'));

 const org=sql("select id from organizations where slug='sowgo'").trim(),user=uuid(),host=uuid(),opp=uuid(),template=uuid(),c=uuid(),agr=uuid(),doc=uuid();
 sql(`insert into auth.users(id,email,email_confirmed_at) values('${user}','phasef-race@example.test',now());insert into organization_staff_directory(organization_id,user_id,display_name)values('${org}','${user}','Synthetic race leader');insert into outreach_campaign_admins(organization_id,user_id,capability,reason) values('${org}','${user}','manage','Synthetic race test only');insert into organizations(id,slug,name,kind)values('${host}','synthetic-race-host','Synthetic race host','church');insert into outreach_host_profiles(owner_organization_id,host_organization_id,city,country,reviewed_by)values('${org}','${host}','Test','CA','${user}');insert into outreach_workflow_templates(id,organization_id,template_key,version,title,steps)values('${template}','${org}','synthetic_f_race',1,'Synthetic race workflow','[{"key":"prepare","title":"Prepare","order":1,"phase_f":true,"visibility":"host_church","due_days":-30},{"key":"pending","title":"Remaining coordination","order":2,"phase_f":true,"required":false,"due_days":-14}]');insert into outreach_opportunities(id,organization_id,details)values('${opp}','${org}','{"church_name":"Synthetic race host","city":"Test","country":"CA"}');insert into outreach_campaigns(id,organization_id,code,name,city,country,timezone,template_id,host_organization_id,event_start,event_end,registration_start,venue,settings)values('${c}','${org}','synthetic_f_race','Synthetic race','Test','CA','America/Toronto','${template}','${host}','2027-06-01T12:00:00Z','2027-06-01T17:00:00Z','2027-06-01T11:00:00Z','{"site_name":"Test venue","address":"Test street"}','{"phase_f":true,"setup_arrival":"Prior day","training_gate":"warning","workflow_inputs":{"permits_required":"no","insurance_required":"no","personnel_final":true,"inventory_confirmed":true}}');insert into outreach_agreement_versions(id,organization_id,template_key,version,title,text_snapshot,fields,source,created_by)values('${agr}','${org}','synthetic_f_race',1,'Synthetic agreement','Synthetic test agreement only','[]','Synthetic fixture','${user}');update outreach_campaigns set settings=settings||jsonb_build_object('agreement_version_id','${agr}') where id='${c}';insert into outreach_campaign_documents(id,campaign_id,title,category,visibility,object_path,status,phase_f,revision)values('${doc}','${c}','Synthetic review','other','host_church','${c}/${doc}/file','uploaded',true,1);`);
 const step=sql(`select id from outreach_campaign_steps where campaign_id='${c}' and step_key='prepare'`).trim();
 sql(`create table public.phasef_barrier(run uuid,worker integer,pid integer,primary key(run,worker));create policy phasef_barrier_test on public.phasef_barrier for all to authenticated using(true) with check(true);grant select,insert on phasef_barrier to authenticated;create function public.phasef_race(run uuid,n integer,action text,c uuid,p jsonb)returns jsonb language plpgsql security definer as $$declare began numeric;answer jsonb;outcome text:='success';code text;deadline timestamptz:=clock_timestamp()+interval '20 seconds';begin while(select count(*) from public.phasef_barrier b where b.run=phasef_race.run)<n loop if clock_timestamp()>deadline then raise exception 'Barrier timeout';end if;perform pg_sleep(.01);end loop;began:=extract(epoch from clock_timestamp());begin answer:=public.outreach_pre_event_workspace(action,c,p);exception when others then outcome:='safe_denial';get stacked diagnostics code=returned_sqlstate;answer:=jsonb_build_object('code',code);end;return jsonb_build_object('pid',pg_backend_pid(),'start',began,'end',extract(epoch from clock_timestamp()),'outcome',outcome,'result',answer);end$$;grant execute on function phasef_race(uuid,integer,text,uuid,jsonb) to authenticated;`);
 const coordinator=execFile(exe('psql'),args,{maxBuffer:2e6}),pending=[];let buffer='';coordinator.stdout.on('data',s=>{buffer+=s.toString();let i;while((i=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,i).trim();buffer=buffer.slice(i+1);if(line&&pending.length)pending.shift()(line)}});const ask=s=>new Promise(resolve=>{pending.push(resolve);coordinator.stdin.write(s+'\n')});const coord=Number(await ask('select pg_backend_pid();'));
 async function group(label,items,lock){const key=uuid(),n=items.length;await ask('begin;'+lock+";select 'locked';");const jobs=items.map(([action,p,id=c],i)=>run(exe('psql'),args.concat(['-c',`set request.jwt.claim.sub='${user}';set role authenticated;insert into phasef_barrier values('${key}',${i},pg_backend_pid());`,'-c',`select phasef_race('${key}',${n},${lit(action)},${id?lit(id):'null'},${lit(JSON.stringify(p))}::jsonb);`]),{maxBuffer:2e6}).then(r=>JSON.parse(r.stdout.trim())));
 const deadline=Date.now()+15000;let active=0;while(Date.now()<deadline){active=Number(await ask(`select pg_stat_clear_snapshot();select count(*) from pg_stat_activity where pid<>pg_backend_pid() and query like '%${key}%' and state='active' and wait_event_type='Lock';`));if(active===n)break;await new Promise(r=>setTimeout(r,30))}await ask("commit;select 'released';");const rows=await Promise.all(jobs);assert.equal(active,n,'all RPC calls independently active and overlapping while coordinator holds target lock');assert.equal(new Set(rows.map(r=>r.pid)).size,n);assert(rows.every(r=>r.pid!==coord));assert.equal(overlap(rows),n);console.log('PASS '+label+' '+JSON.stringify({workers:n,distinct_backends:n,coordinator_separate:true,server_barrier_ready:n,peak_active_rpc_queries:active,max_overlapping_intervals:overlap(rows),success:rows.filter(r=>r.outcome==='success').length,safe_conflicts:rows.filter(r=>r.outcome==='safe_denial').length}));return rows}
 const repeat=(action,p,id=c)=>Array.from({length:8},()=>[action,p,id]),lockCampaign=`select id from outreach_campaigns where id='${c}' for update`;
 try{
 const cp={organization_id:org,id:opp,revision:1,code:'synthetic_f_conversion',name:'Converted once',timezone:'America/Toronto',template_id:template,host_organization_id:host,identity_review_reason:'Synthetic reviewed existing host'};let rows=await group('A duplicate conversion',repeat('convert',cp,null),`select id from outreach_opportunities where id='${opp}' for update`);assert.equal(rows.filter(r=>r.outcome==='success').length,8);assert.equal(Number(sql(`select count(*) from outreach_campaigns where opportunity_id='${opp}'`)),1);
 rows=await group('B duplicate signed agreement',repeat('agreement_submit',{request_key:uuid(),responses:{},signature_name:'Synthetic Signer',acknowledged:true}),lockCampaign);assert.equal(rows.filter(r=>r.outcome==='success').length,8);assert.equal(Number(sql(`select count(*) from outreach_campaign_agreements where campaign_id='${c}'`)),1);
 rows=await group('C duplicate task completion',repeat('step_complete',{id:step,revision:1}),lockCampaign);assert.equal(rows.filter(r=>r.outcome==='success').length,8);assert.equal(Number(sql(`select count(*) from outreach_campaign_audit where subject_id='${step}' and kind='outreach.task.step_complete'`)),1);
 rows=await group('D conflicting document review',Array.from({length:8},(_,i)=>['document_review',{id:doc,revision:1,status:i%2?'rejected':'approved',note:'Synthetic review decision'},c]),lockCampaign);assert.equal(rows.filter(r=>r.outcome==='success').length,1);assert.equal(rows.filter(r=>r.outcome==='safe_denial').length,7);assert.equal(sql(`select revision from outreach_campaign_documents where id='${doc}'`).trim(),'2');
 sql(`set request.jwt.claim.sub='${user}';set role authenticated;select outreach_pre_event_workspace('reminders','${c}','{}');`);const rev=Number(sql(`select revision from outreach_campaigns where id='${c}'`));rows=await group('E reschedule vs reminder recalculation',Array.from({length:8},(_,i)=>[i?'reminders':'reschedule',i?{}:{revision:rev,event_start:'2027-07-01T12:00:00Z',registration_start:'2027-07-01T11:00:00Z',event_end:'2027-07-01T17:00:00Z',reason:'Synthetic date change'},c]),lockCampaign);assert.equal(rows.filter(r=>r.outcome==='success').length,8);assert.equal(Number(sql(`select count(*) from outreach_task_reminders r join outreach_campaign_steps s on s.id=r.step_id where r.campaign_id='${c}' and r.state='pending' and r.due_snapshot is distinct from s.due_at`)),0);assert.equal(Number(sql(`select count(*)-count(distinct reminder_key) from outreach_task_reminders where campaign_id='${c}'`)),0);
 assert.equal(sql(`select to_char(due_at at time zone 'UTC','YYYY-MM-DD HH24:MI') from outreach_campaign_steps where campaign_id='${c}' and step_key='pending'`).trim(),'2027-06-17 12:00');assert.equal(Number(sql(`select count(*) from outreach_task_reminders where campaign_id='${c}' and state='pending'`)),6);rows=await group('F duplicate packet generation',repeat('packet_generate',{generation_key:uuid()}),lockCampaign);assert.equal(rows.filter(r=>r.outcome==='success').length,8);assert.equal(Number(sql(`select count(*) from outreach_campaign_packets where campaign_id='${c}'`)),1);console.log('PASS all six Phase F independent PostgreSQL races');
 }finally{coordinator.stdin.end();await new Promise(r=>coordinator.once('exit',r))}
}finally{if(started)execFileSync(exe('pg_ctl'),['-D',data,'-m','fast','-w','stop'],{stdio:'ignore'});rmSync(root,{recursive:true,force:true})}
