// Real PostgreSQL on a disposable local socket-only cluster. No remote DSN or secrets.
import assert from 'node:assert/strict';import{mkdtempSync,mkdirSync,readFileSync,rmSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';import{execFileSync,execFile}from'node:child_process';import{promisify}from'node:util';import{randomUUID as uuid}from'node:crypto';import{migrationOrder}from'./migration-order.mjs';
const bin=process.env.TEST_POSTGRES_BIN||'/opt/homebrew/opt/postgresql@17/bin',exe=n=>join(bin,n),root=mkdtempSync(join(tmpdir(),'phasec-pg-')),data=join(root,'data'),socket=join(root,'socket');mkdirSync(socket);const args=['-h',socket,'-p','55487','-U','postgres','-d','postgres','-X','-qAt','-v','ON_ERROR_STOP=1'],sql=s=>execFileSync(exe('psql'),args,{input:s,encoding:'utf8',maxBuffer:8e6}),run=promisify(execFile),literal=v=>"'"+String(v).replaceAll("'","''")+"'";let started=false;
const overlap=rows=>{const points=rows.flatMap(r=>[[Number(r.start),1],[Number(r.end),-1]]).sort((a,b)=>a[0]-b[0]||a[1]-b[1]);let n=0,max=0;for(const[,v]of points){n+=v;max=Math.max(max,n)}return max};
try{
 execFileSync(exe('initdb'),['-D',data,'-U','postgres','--auth=trust','--no-locale','--encoding=UTF8'],{stdio:'pipe'});execFileSync(exe('pg_ctl'),['-D',data,'-l',join(root,'server.log'),'-o',`-k ${socket} -p 55487 -c listen_addresses=''`,'-w','start'],{stdio:'ignore'});started=true;
 sql(readFileSync(new URL('fixtures/supabase-test-bootstrap.sql',import.meta.url),'utf8'));sql(readFileSync(new URL('../../supabase/bootstrap/automatic-rls.sql',import.meta.url),'utf8'));for(const f of migrationOrder)sql(readFileSync(new URL('../../supabase/migrations/'+f,import.meta.url),'utf8'));
 const org=sql("select organization_id from outreach_campaigns where code='bessemer_al_2026'").trim(),template=sql('select id from outreach_workflow_templates limit 1').trim(),campaign=uuid(),admin=uuid();
 sql(`insert into auth.users(id,email,email_confirmed_at)values('${admin}','phasec-race@example.test',now());insert into organization_staff_directory(organization_id,user_id,display_name)values('${org}','${admin}','Synthetic local operator');insert into outreach_campaign_admins(organization_id,user_id,capability,reason)values('${org}','${admin}','manage','Synthetic local concurrency authority');insert into outreach_campaigns(id,organization_id,code,name,city,country,timezone,template_id,status)values('${campaign}','${org}','phasec_race','Synthetic','Test','US','UTC','${template}','approved');set request.jwt.claim.sub='${admin}';select outreach_registration_workspace('configure','${campaign}','{"revision":0,"public_slug":"phasec-race","enabled":true,"waiver_required":true}');`);
 const version=JSON.parse(sql(`set request.jwt.claim.sub='${admin}';select outreach_registration_workspace('waiver_publish','${campaign}','{"template_key":"synthetic","version":1,"effective_at":"2026-01-01T00:00:00Z","text":"SYNTHETIC CONCURRENCY WAIVER ONLY. Not real legal wording."}');`).trim()).id;
 const attendee={client_key:uuid(),first_name:'Synthetic',last_name:'Child',age:9,relationship:'child',guardian_relationship:'Parent',prize_participation:true},payload=()=>({request_key:uuid(),first_name:'Synthetic',last_name:'Parent',email:'race@example.test',phone:'+15555550100',attendees:[{...attendee}],consents:{marketing:false},waiver:{request_key:uuid(),version_id:version,signer_name:'Synthetic Parent',signer_relationship:'parent',acknowledged:true,authority_acknowledged:true,covered_keys:[attendee.client_key]}});
 // Coordinator keeps its connection during every group. Workers register committed readiness
 // before waiting on the server-side advisory gate. One winner holds campaign serialization
 // long enough for the other independent active requests to overlap in PostgreSQL.
 sql(`create table public.phasec_barrier(run uuid,worker integer,pid integer,primary key(run,worker));create policy phasec_barrier_test_only on public.phasec_barrier for all to authenticated using(true) with check(true);create function public.phasec_race(run uuid,n integer,act text,c uuid,p jsonb) returns jsonb language plpgsql as $$declare began numeric;answer jsonb;outcome text:='success';deadline timestamptz:=clock_timestamp()+interval '15 seconds';begin
 while (select count(*) from public.phasec_barrier b where b.run=phasec_race.run)<n loop if clock_timestamp()>deadline then raise exception 'Barrier timeout';end if;perform pg_sleep(.01);end loop;
 began:=extract(epoch from clock_timestamp());begin
 if act='submit' then answer:=public.outreach_registration_gateway('phasec-race',p,repeat('a',64));if answer->>'accepted'<>'true' then outcome:='safe_denial';end if;
 else answer:=public.outreach_registration_workspace(act,c,p);end if;
 exception when others then raise;end;
 -- This hold is test-only instrumentation after the real RPC, retaining its row locks.
 perform pg_sleep(.3);return jsonb_build_object('pid',pg_backend_pid(),'start',began,'end',extract(epoch from clock_timestamp()),'outcome',outcome,'result',answer);end$$;grant select,insert on phasec_barrier to authenticated,service_role;grant execute on function phasec_race(uuid,integer,text,uuid,jsonb) to authenticated,service_role;`);
 const coordinator=execFile(exe('psql'),args,{maxBuffer:1e6});coordinator.stdin.write('select pg_backend_pid();\n');const coordPid=await new Promise((resolve,reject)=>{coordinator.stdout.once('data',s=>resolve(Number(s.toString().trim())));coordinator.once('error',reject)});
 async function group(label,action,payloads){const key=uuid(),n=payloads.length;const results=await Promise.all(payloads.map((p,i)=>run(exe('psql'),[...args,'-c',`set request.jwt.claim.sub='${admin}';set role ${action==='submit'?'service_role':'authenticated'};insert into phasec_barrier values('${key}',${i},pg_backend_pid());`,'-c',`select phasec_race('${key}',${n},${literal(action)},'${campaign}',${literal(JSON.stringify(p))}::jsonb);`],{maxBuffer:1e6}).then(r=>JSON.parse(r.stdout.trim()))));assert.equal(new Set(results.map(r=>r.pid)).size,n);assert(results.every(r=>r.pid!==coordPid));assert.equal(Number(sql(`select count(*) from phasec_barrier where run='${key}'`)),n);assert.equal(overlap(results),n,'every independent worker must genuinely overlap');console.log('PASS '+label+' '+JSON.stringify({workers:n,distinct_backends:n,coordinator:coordPid,server_barrier_ready:n,server_interval_overlap:overlap(results),success:results.filter(r=>r.outcome==='success').length,safe_denials:results.filter(r=>r.outcome==='safe_denial').length}));return results;}
 try{
 const p=payload(),results=await group('duplicate household submission','submit',Array(8).fill(p));assert(results.every(r=>r.result.reference===results[0].result.reference));assert.equal(Number(sql(`select count(*) from outreach_event_registrations where campaign_id='${campaign}'`)),1);const id=sql(`select id from outreach_event_registrations where campaign_id='${campaign}'`).trim(),aid=sql(`select id from outreach_event_attendees where registration_id='${id}'`).trim();
 await group('same attendee check-in','checkin',Array(8).fill({registration_id:id,attendee_id:aid}));assert.equal(Number(sql(`select count(*) from outreach_campaign_events where kind='outreach.attendee.checked_in' and campaign_id='${campaign}'`)),1);assert.equal(Number(sql(`select count(*) from outreach_prize_participants where attendee_id='${aid}'`)),1);
 const extra={registration_id:id,client_key:uuid(),first_name:'Other',last_name:'Synthetic',age:25,relationship:'other'};const add=await group('same attendee add','attendee_add',Array(8).fill(extra));assert(add.every(r=>r.result.id===add[0].result.id));assert.equal(Number(sql(`select count(*) from outreach_event_attendees where registration_id='${id}'`)),2);
 const sig={registration_id:id,request_key:uuid(),version_id:version,signer_name:'Synthetic Parent',signer_relationship:'parent',acknowledged:true,authority_acknowledged:true,covered_keys:[attendee.client_key,extra.client_key]};const signed=await group('same signature retry','sign',Array(8).fill(sig));assert(signed.every(r=>r.result.id===signed[0].result.id));assert.equal(Number(sql(`select count(*) from outreach_waiver_signatures where registration_id='${id}' and request_key='${sig.request_key}'`)),1);
 sql(`set request.jwt.claim.sub='${admin}';select outreach_registration_workspace('configure','${campaign}','{"revision":1,"public_slug":"phasec-race","enabled":true,"waiver_required":true,"household_limit":2}');`);const capacity=await group('last household capacity','submit',Array.from({length:8},payload));assert.equal(capacity.filter(r=>r.outcome==='success').length,1);assert.equal(capacity.filter(r=>r.outcome==='safe_denial').length,7);assert.equal(Number(sql(`select count(*) from outreach_event_registrations where campaign_id='${campaign}'`)),2);console.log('PASS all five Phase C integrity races; no capacity overflow, duplicate audit or live drawing numbers');
 }finally{coordinator.stdin.end();await new Promise(r=>coordinator.once('exit',r))}
}finally{if(started)execFileSync(exe('pg_ctl'),['-D',data,'-m','fast','-w','stop'],{stdio:'ignore'});rmSync(root,{recursive:true,force:true})}
