// Executes the release transaction against a synthetic cron API/catalog.
// Hosted extension installation and worker execution are deliberately NOT claimed.
import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {migrationOrder} from './migration-order.mjs';
const read=name=>readFileSync(new URL('../../supabase/release/'+name,import.meta.url),'utf8');
const original=read('outreach-cron-enable.sql'),rollback=read('outreach-cron-unschedule.sql');
function replaceOnce(sql,pattern,value){assert.equal([...sql.matchAll(new RegExp(pattern.source,'g'))].length,1);return sql.replace(pattern,value)}
// Only real-extension availability/configuration/install assertions are mocked.
let schedule=replaceOnce(original,/ if not exists\(select 1 from pg_available_extensions[\s\S]*?Supported preloaded local pg_cron configuration required';\n end if;/,'');
schedule=replaceOnce(schedule,/ if to_regnamespace\('cron'\)[\s\S]*?Unexpected existing cron schema; review without overwriting';\n end if;/,'');
schedule=replaceOnce(schedule,/create extension if not exists pg_cron with schema pg_catalog;/,'');
schedule=replaceOnce(schedule,/ if not exists\(select 1 from pg_extension where extname='pg_cron' and extnamespace=[\s\S]*?Unexpected pg_cron extension schema';\n end if;/,'');
assert.match(original,/create extension if not exists pg_cron with schema pg_catalog;/);
assert.equal((original.match(/cron\.schedule\(/g)||[]).length,1);
assert(!/\b(drop|truncate)\b/i.test(original+'\n'+rollback));
const db=new PGlite(),q=(sql,args=[])=>db.query(sql,args);
await db.exec(readFileSync(new URL('fixtures/supabase-test-bootstrap.sql',import.meta.url),'utf8'));
await db.exec(readFileSync(new URL('../../supabase/bootstrap/automatic-rls.sql',import.meta.url),'utf8'));
for(const name of migrationOrder)await db.exec(readFileSync(new URL('../../supabase/migrations/'+name,import.meta.url),'utf8'));
await db.exec(`create schema cron;
create table cron.job(jobid bigint generated by default as identity primary key,jobname text,schedule text,command text,database text default 'postgres',username text default 'postgres',nodename text default 'localhost',nodeport integer default 5432,active boolean default true);
create table cron.job_run_details(jobid bigint,runid bigint,status text,return_message text,start_time timestamptz,end_time timestamptz);
create function cron.schedule(text,text,text) returns bigint language plpgsql as $$declare result bigint;begin insert into cron.job(jobname,schedule,command,nodeport) values($1,$2,$3,current_setting('port')::int) returning jobid into result;return result;end$$;
create function cron.unschedule(bigint) returns boolean language plpgsql as $$begin delete from cron.job where jobid=$1;return found;end$$;
insert into cron.job(jobname,schedule,command,nodeport) values('unrelated-job','0 * * * *','select 1',current_setting('port')::int);
`);
const all=async()=>(await q('select * from cron.job order by jobid')).rows;
const denied=async(sql,pattern)=>{await assert.rejects(()=>db.exec(sql),pattern);await db.exec('rollback')};
await denied(schedule,/acknowledgement/);
await q("select set_config('champion.outreach_release_target','bkbmjisprwmkptywtmih',false)");
await denied(schedule,/acknowledgement/);
await q("select set_config('champion.outreach_release_target','exdocjbmylgxssanymjk',false)");
const unrelated=await all();
await db.exec(schedule);const first=await all();assert.equal(first.length,2);assert.deepEqual(first[0],unrelated[0]);
await db.exec(schedule);assert.deepEqual(await all(),first);
console.log('PASS target interlock, one exact named job, idempotent scheduling and unrelated-job preservation');
for(const [column,value] of [['command','select 2'],['schedule','* * * * *'],['username','other_owner'],['database','other_database'],['nodename','remote-host'],['nodeport',9999],['active',false]]){
 await q(`update cron.job set ${column}=$1 where jobname='outreach-abuse-cleanup'`,[value]);
 const before=await all();await denied(schedule,/Unexpected cleanup job/);assert.deepEqual(await all(),before);
 if(column!=='active'){await denied(rollback,/Unexpected cleanup job/);assert.deepEqual(await all(),before)}
 await q(`update cron.job set ${column}=$1 where jobname='outreach-abuse-cleanup'`,[first[1][column]]);
}
await db.exec("insert into cron.job(jobname,schedule,command,username) values('outreach-abuse-cleanup','*/5 * * * *','select private.outreach_abuse_cleanup()','other_owner')");
const duplicate=await all();await denied(schedule,/Duplicate/);await denied(rollback,/Duplicate/);assert.deepEqual(await all(),duplicate);
await db.exec("delete from cron.job where username='other_owner'");
await db.exec(read('outreach-cron-verify.sql'));
await db.exec(rollback);assert.deepEqual(await all(),unrelated);
await db.exec(rollback);assert.deepEqual(await all(),unrelated);
assert((await q("select to_regclass('private.outreach_abuse_windows') v")).rows[0].v);
assert((await q("select to_regclass('public.outreach_partner_intakes') v")).rows[0].v);
console.log('PASS conflicting command/schedule/owner/database/host/port/inactive/duplicate jobs fail safely; verification SQL executes; rollback removes only expected job and is idempotent');
await db.close();
