// Real disposable PostgreSQL, socket-only. No remote/production DSN is accepted.
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,readFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';import {join} from 'node:path';
import {execFileSync,execFile} from 'node:child_process';import {promisify} from 'node:util';import {randomUUID} from 'node:crypto';import {migrationOrder} from './migration-order.mjs';
const bin=process.env.TEST_POSTGRES_BIN||'',exe=n=>bin?join(bin,n):n,root=mkdtempSync(join(tmpdir(),'outreach-team-pg-')),data=join(root,'data'),socket=join(root,'socket');mkdirSync(socket,{mode:0o700});
const reuse=process.env.TEST_POSTGRES_LOCAL_REUSE==='1',database='codex_phaseb_'+randomUUID().replaceAll('-',''),clusterArgs=['-h','/private/tmp','-p','5432','-U','davesmacbookpro','-d','postgres','-X','-qAt','-v','ON_ERROR_STOP=1'],createdRoles=[];let createdDatabase=false;
const args=['-h',reuse?'/private/tmp':socket,'-p',reuse?'5432':'55484','-U',reuse?'davesmacbookpro':'postgres','-d',reuse?database:'postgres','-X','-qAt','-v','ON_ERROR_STOP=1'],sql=s=>execFileSync(exe('psql'),args,{input:s,encoding:'utf8',maxBuffer:8e6}),run=promisify(execFile);let started=false;
function overlap(rows){const points=rows.flatMap(r=>[[r.start,1],[r.end,-1]]).sort((a,b)=>a[0]-b[0]||a[1]-b[1]);let n=0,max=0;for(const [,d]of points){n+=d;max=Math.max(max,n);}return max;}
try{
 if(reuse){const proof=execFileSync(exe('psql'),[...clusterArgs,'-c',"select inet_server_addr() is null, current_setting('data_directory');"],{encoding:'utf8'}).trim();assert.equal(proof,'t|/opt/homebrew/var/postgresql@17');for(const role of ['anon','authenticated','service_role'])if(execFileSync(exe('psql'),[...clusterArgs,'-c',`select count(*) from pg_roles where rolname='${role}'`],{encoding:'utf8'}).trim()==='0')createdRoles.push(role);execFileSync(exe('psql'),[...clusterArgs,'-c',`create database ${database}`],{stdio:'ignore'});createdDatabase=true;}else{execFileSync(exe('initdb'),['-D',data,'-U','postgres','--auth=trust','--no-locale','--encoding=UTF8'],{stdio:'pipe'});execFileSync(exe('pg_ctl'),['-D',data,'-l',join(root,'server.log'),'-o',`-k ${socket} -p 55484 -c listen_addresses=''`,'-w','start'],{stdio:'ignore'});started=true;}
 let bootstrap=readFileSync(new URL('fixtures/supabase-test-bootstrap.sql',import.meta.url),'utf8');if(reuse)for(const role of ['anon','authenticated','service_role'])if(!createdRoles.includes(role))bootstrap=bootstrap.replace(new RegExp('create role '+role+'[^;]*;'),'');
 sql(bootstrap);let rls=readFileSync(new URL('../../supabase/bootstrap/automatic-rls.sql',import.meta.url),'utf8');if(reuse)rls=rls.replaceAll("'postgres'","'davesmacbookpro'");sql(rls);for(const f of migrationOrder)sql(readFileSync(new URL('../../supabase/migrations/'+f,import.meta.url),'utf8'));
 const org=sql("select organization_id from outreach_campaigns where code='bessemer_al_2026'").trim(),template=sql('select id from outreach_workflow_templates limit 1').trim(),campaign=randomUUID(),admin=randomUUID(),signup=randomUUID(),vehicle=randomUUID(),hotel=randomUUID(),room=randomUUID(),room2=randomUUID(),members=Array.from({length:16},()=>randomUUID());
 sql(`insert into auth.users(id,email,email_confirmed_at)values('${admin}','phaseb-concurrency@example.test',now());insert into organization_staff_directory(organization_id,user_id,display_name)values('${org}','${admin}','Synthetic local admin');insert into outreach_campaign_admins(organization_id,user_id,capability,reason)values('${org}','${admin}','manage','Explicit synthetic test authority');insert into organization_staff_permissions(organization_id,user_id,permission)select '${org}','${admin}',x from unnest(array['people.read','people.create','people.update'])x;set request.jwt.claim.sub='${admin}';insert into outreach_campaigns(id,organization_id,code,name,city,country,timezone,template_id,status)values('${campaign}','${org}','phaseb_concurrency','Synthetic concurrency','Test','US','UTC','${template}','approved');insert into outreach_team_signups(id,campaign_id,organization_id,applicant_user_id,party_label)values('${signup}','${campaign}','${org}','${admin}','Synthetic capacity fixture');`);
 for(const [i,id]of members.entries()){const person=randomUUID();sql(`set request.jwt.claim.sub='${admin}';insert into organization_people(id,organization_id,first_name,last_name)values('${person}','${org}','Synthetic ${i}','Traveler');insert into outreach_team_members(id,campaign_id,signup_id,organization_id,person_id,first_name,last_name,relationship,age,status)values('${id}','${campaign}','${signup}','${org}','${person}','Synthetic ${i}','Traveler','family',35,'approved');`);}
 sql(`insert into outreach_team_vehicles(id,campaign_id,label,vehicle_type,total_capacity,passenger_capacity)values('${vehicle}','${campaign}','Final seat','Bus',1,1);insert into outreach_team_lodgings(id,campaign_id,name,check_in,check_out)values('${hotel}','${campaign}','Hotel A','2026-11-01','2026-11-03');insert into outreach_team_rooms(id,campaign_id,lodging_id,label,capacity)values('${room}','${campaign}','${hotel}','Final room space',1),('${room2}','${campaign}','${hotel}','Other room',1);`);
 // Timing is collected across genuinely independent database backends; errors are classified,
 // unexpected errors rethrow. This helper exists only in this disposable test database.
 sql(`create function public.phaseb_race(a text,c uuid,p jsonb) returns jsonb language plpgsql as $$declare began numeric:=extract(epoch from clock_timestamp());outcome text;begin perform pg_sleep(0.25);begin perform outreach_team_workspace(a,c,p);outcome:='success';exception when others then if sqlerrm in ('Vehicle capacity reached','Room capacity reached','Member changed; reload','Conflicting lodging stay','Release existing primary vehicle before reassignment') then outcome:='safe_capacity_or_conflict';else raise;end if;end;return jsonb_build_object('pid',pg_backend_pid(),'start',began,'end',extract(epoch from clock_timestamp()),'outcome',outcome);end$$;grant execute on function public.phaseb_race(text,uuid,jsonb) to authenticated;`);
 const send=(action,p)=>run(exe('psql'),[...args,'-c',`set request.jwt.claim.sub='${admin}';set role authenticated;select phaseb_race('${action}','${campaign}','${JSON.stringify(p)}'::jsonb);`],{maxBuffer:1e6}).then(r=>JSON.parse(r.stdout.trim()));
 async function race(label,action,payload){const results=await Promise.all(members.map(id=>send(action,{member_id:id,revision:Number(sql(`select revision from outreach_team_members where id='${id}'`).trim()),...payload})));assert.equal(new Set(results.map(r=>r.pid)).size,16);assert.equal(results.filter(r=>r.outcome==='success').length,1);assert.equal(results.filter(r=>r.outcome==='safe_capacity_or_conflict').length,15);assert(overlap(results)>=2);console.log('PASS '+label+' '+JSON.stringify({callers:16,independent_backends:16,max_overlapping_requests:overlap(results),success:1,safe_denials:15}));}
 await race('concurrent final vehicle seat','vehicle_assign',{vehicle_id:vehicle,seat_role:'passenger'});assert.equal(Number(sql(`select count(*) from outreach_team_vehicle_assignments where vehicle_id='${vehicle}'`)),1);
 await race('concurrent final lodging space','lodging_assign',{room_id:room});assert.equal(Number(sql(`select count(*) from outreach_team_room_assignments where room_id='${room}'`)),1);
 const person=members.find(id=>sql(`select count(*) from outreach_team_room_assignments where member_id='${id}'`).trim()==='0'),revision=Number(sql(`select revision from outreach_team_members where id='${person}'`).trim());
 const outcomes=await Promise.all([send('lodging_assign',{member_id:person,revision,room_id:room2}),send('lodging_assign',{member_id:person,revision,room_id:room2})]);assert.equal(outcomes.filter(r=>r.outcome==='success').length,1);assert.equal(Number(sql(`select count(*) from outreach_team_room_assignments where member_id='${person}'`)),1);console.log('PASS simultaneous same-traveler lodging retries: one assignment, one safe conflict');
 const total=Number(sql("select count(*) from outreach_campaign_audit where kind in ('vehicle.assigned','lodging.assigned')"));assert.equal(total,3);console.log('PASS exactly three immutable assignment audit records, no failed-request events');
}finally{if(createdDatabase)execFileSync(exe('psql'),[...clusterArgs,'-c',`drop database ${database} with (force)`],{stdio:'ignore'});for(const role of createdRoles)execFileSync(exe('psql'),[...clusterArgs,'-c',`drop role ${role}`],{stdio:'ignore'});if(started)execFileSync(exe('pg_ctl'),['-D',data,'-m','fast','-w','stop'],{stdio:'ignore'});rmSync(root,{recursive:true,force:true});}
