import {JSDOM} from 'jsdom';import {readFileSync} from 'node:fs';import {webcrypto,createHash} from 'node:crypto';import assert from 'node:assert/strict';
const read=p=>readFileSync(new URL('../../'+p,import.meta.url),'utf8'),code=read('assets/js/outreach-partner.js');
const expected=['first-name','last-name','email','address-line-1','address-line-2','city','state-province','postal-code','phone','commitment-amount','commitment-frequency'];
for(const brand of ['champion-life','sowgo','forged']){
 const dom=new JSDOM('<main id="outreach-partner-root"></main>',{url:'https://preview.example/outreach-partner.html?brand='+brand,runScripts:'outside-only'}),w=dom.window;Object.defineProperty(w,'crypto',{value:webcrypto});w.TextEncoder=TextEncoder;w.CHAMPION_LIFE_SUPABASE={url:'https://isolated.example',publishableKey:'test-public'};const timers=[];w.setTimeout=fn=>timers.push(fn);const requests=[];let fail=true;
 w.fetch=async(url,args)=>{requests.push({url,p:JSON.parse(args.body).p_data});return{ok:!fail,json:async()=>fail?{}:{accepted:true}}};w.eval(code);
 const form=w.document.querySelector('form');assert.equal(form.hasAttribute('data-netlify'),false);assert.deepEqual([...form.querySelectorAll('[required]')].map(n=>n.name),expected.filter(k=>k!=='address-line-2'));assert.equal(form.elements.namedItem('email').maxLength,254);assert.equal(form.elements.namedItem('commitment-amount').min,'1');assert.equal(form.elements.namedItem('commitment-amount').step,'0.01');assert.deepEqual([...form.querySelector('select').options].slice(1).map(o=>o.value),['Weekly','Bi-weekly','Monthly']);assert.equal(form.querySelector('[type=submit]').textContent,brand==='sowgo'?'Submit & Continue to Sow':'Submit & Continue to Give');assert.equal(w.document.querySelector('img').getAttribute('src'),brand==='sowgo'?'/assets/images/sowgo-logo-light.png':'/assets/images/logo-gold.png');
 const values=['Synthetic','Partner','test@example.test','1 Example','', 'Test','FL','32548','5555551234','25.75','Monthly'];expected.forEach((k,i)=>form.elements.namedItem(k).value=values[i]);form.reportValidity=()=>true;
 const fire=()=>form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));const tick=()=>new Promise(r=>setTimeout(r,30));fire();fire();await tick();assert.equal(requests.length,1,'double click suppressed');assert.equal(form.querySelector('[type=submit]').disabled,false,'failure can retry');fail=false;fire();await tick();assert.equal(requests[0].p.request_key,requests[1].p.request_key,'network retry key retained');assert.equal(requests[1].p.brand,brand==='sowgo'?'sowgo':'champion-life');assert.equal(requests[1].p.source_path,'/outreach-partner.html');assert.equal(form.querySelector('[role=status] a').getAttribute('href'),'/outreach-giving.html');assert(!w.sessionStorage.getItem('outreach-partner-replay:'+requests[1].p.brand).includes('test@example.test'));
 // Remount simulates back/refresh with retained sessionStorage; exact input reuses server key.
 w.OutreachPartner.mount(w.document.querySelector('main'),brand);const fresh=w.document.querySelector('form');expected.forEach((k,i)=>fresh.elements.namedItem(k).value=values[i]);fresh.reportValidity=()=>true;fresh.dispatchEvent(new w.Event('submit',{cancelable:true}));await tick();assert.equal(requests[2].p.request_key,requests[1].p.request_key);dom.window.close();
}
const dom=new JSDOM('<button id="launch">Become a Partner</button>',{url:'https://preview.example/outreach.html',runScripts:'outside-only'});dom.window.eval(code);dom.window.document.querySelector('button').focus();dom.window.OutreachPartner.open();assert(dom.window.document.querySelector('#outreach-partner-modal').classList.contains('is-open'));assert.equal(dom.window.document.activeElement.name,'first-name');dom.window.document.dispatchEvent(new dom.window.KeyboardEvent('keydown',{key:'Escape'}));assert.equal(dom.window.document.activeElement.id,'launch');dom.window.close();
assert(!/name="outreach-partner"/.test(read('netlify-forms.html')));assert(!read('assets/js/site.js').includes('application/x-www-form-urlencoded'));
assert(read('outreach-giving.html').includes('https://www.community.givehub.com/forms/outreach-main-giving'));
assert(read('assets/css/outreach-partner.css').includes('#062943'));assert(read('assets/css/outreach-partner.css').includes('#ff4b00'));
console.log('PASS shared outreach fields, brands, logo, guest submit, double click, retry/back replay, continuation, modal focus and native-only capture');
