import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {JSDOM,VirtualConsole} from 'jsdom';import {campaign,person,response,form} from './fixtures/outreach-team-ui.mjs';
let count=0;const check=(v,m)=>{assert.ok(v,m);count++;console.log('PASS '+m)},tick=()=>new Promise(r=>setTimeout(r,25));
async function load(portal=false,mode='signup'){
 const errors=[],calls=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const dom=new JSDOM(`<div id="${portal?'outreach-team-portal':'outreach-team-app'}"></div>`,{url:'https://preview.example.test/'+(portal?'outreach-team.html':'staff-outreach-team.html')+'?campaign='+campaign,runScripts:'outside-only',virtualConsole:vc});const w=dom.window;let blocked=false,signed=true,listener;
 w.URL.createObjectURL=()=> 'blob:fixture';w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=function(){calls.push({download:this.download})};w.ChampionLifeAuth={getUser:async()=>signed?{id:person}:null,getSession:async()=>signed?{user:{id:person}}:null,client:{rpc:async(name,p)=>{calls.push({name,p});if(blocked)return {error:{code:'42501'},status:403};return {data:response(name,p,mode)};},auth:{onAuthStateChange:fn=>{listener=fn}}}};for(const name of ['outreach-staff-common.js',portal?'outreach-team-portal.js':'outreach-team.js'])w.eval(readFileSync(new URL('../../assets/js/'+name,import.meta.url),'utf8'));await tick();return {w,d:w.document,calls,errors,dom,block:()=>{blocked=true;},signout:()=>{signed=false;listener('SIGNED_OUT',null);}};
}
function click(t,label){const b=Array.from(t.d.querySelectorAll('button')).find(b=>b.textContent===label);assert.ok(b,'button '+label);b.click();return tick();}
function input(t,label,value){const l=Array.from(t.d.querySelectorAll('label')).find(l=>l.firstChild?.textContent===label||l.textContent.startsWith(label));assert(l,'input '+label);const i=l.querySelector('input,textarea,select');i.value=value;return i;}
const staff=await load();check(staff.d.body.textContent.includes('Huntsville-like Outreach'),'staff campaign list loads');check(staff.d.querySelector('[role=status]').hidden,'no residual loading state');check(Array.from(staff.d.querySelectorAll('option')).some(o=>o.value==='22222222-2222-4222-8222-222222222222'&&o.textContent==='Fowler Fixture Family'),'travel-party dropdown uses safe label and exact scoped ID');await click(staff,'Review applicant');check(staff.d.querySelector('select').value!==undefined,'detail controls accessible');check(staff.d.body.textContent.includes('Individual approval')&&staff.d.body.textContent.includes('Vehicle assignment')&&staff.d.body.textContent.includes('Lodging assignment'),'individual detail includes approval/vehicle/lodging controls');input(staff,'New status','waitlisted');input(staff,'Review reason','Synthetic individual review');await click(staff,'Save individual status');let call=staff.calls.find(c=>c.p?.p_action==='status');check(call.p.p_payload.member_id===person&&call.p.p_payload.revision===4&&call.p.p_payload.status==='waitlisted','status mutation scoped to one member/revision');
await click(staff,'Vehicles');check(staff.d.body.textContent.includes('Equipment only')&&staff.d.body.textContent.includes('Total seats 26'),'vehicles distinguish equipment and capacity');await click(staff,'Lodging');check(staff.d.body.textContent.includes('Family 101')&&staff.d.body.textContent.includes('Hotel A'),'lodging rooms and family grouping rendered');await click(staff,'Meetups & directions');check(staff.d.querySelector('a[href^="https://maps.google.com"]')?.rel.includes('noopener'),'map opens safe external destination');await click(staff,'Manifest');input(staff,'Status','approved');await click(staff,'Apply filters');check(staff.calls.some(c=>c.p?.p_action==='manifest'&&c.p.p_payload.status==='approved'),'manifest filters sent to scoped server');await click(staff,'Export travel CSV');check(staff.calls.some(c=>c.p?.p_action==='export'&&c.p.p_payload.kind==='travel')&&staff.calls.some(c=>c.download),'server authorized export downloaded');
await click(staff,'Signup setup');check(staff.d.body.textContent.includes('Official team target')&&staff.d.body.textContent.includes('Manual window override'),'configurable windows/capacity/roles UI');await click(staff,'Team & travel access');check(staff.d.body.textContent.includes('team.view')&&staff.d.body.textContent.includes('travel.manage'),'explicit Phase B grants rendered');await click(staff,'Applications');staff.block();await click(staff,'Review applicant');check(staff.d.body.textContent.includes('Team & travel access unavailable')&&!staff.d.body.textContent.includes('synthetic@example.test')&&!staff.d.querySelector('input'),'403 clears protected content');check(staff.errors.length===0,'staff UI no jsdom console errors');staff.dom.window.close();
const signup=await load(true);check(signup.d.body.textContent.includes('Applying is a request')&&signup.d.querySelector('input[type=email]').readOnly,'signup explanation and verified email');await click(signup,'Add spouse / child / family member');const cards=signup.d.querySelectorAll('.team-record');check(cards.length===2&&signup.d.body.textContent.includes('Use a reviewed family member'),'dynamic party member reuses authorized known member');const known=cards[1].querySelector('select');known.value=form.known_members[0].id;known.dispatchEvent(new signup.w.Event('change'));check(cards[1].querySelector('input').value==='Spouse','known member name not reentered');const volunteer=Array.from(cards[1].querySelectorAll('.team-check')).find(l=>l.textContent==='Volunteering / helping').querySelector('input');check(!volunteer.checked&&cards[1].querySelector('.team-inline-form').hidden,'child/attendee defaults do not imply volunteer');
input(signup,'Family / travel party name','Synthetic family');cards[0].querySelector('input[type=number]').value='38';cards[1].querySelector('input[type=number]').value='15';const f=signup.d.querySelector('form');f.dispatchEvent(new signup.w.Event('submit',{bubbles:true,cancelable:true}));await tick();const submitted=signup.calls.find(c=>c.p?.p_action==='submit');check(submitted.p.p_payload.members.length===2&&!submitted.p.p_payload.members[1].volunteering&&submitted.p.p_payload.members[1].person_id===known.value,'signup sends per-member attendee/known identity fields');check(signup.d.body.textContent.includes('YOUR TRIP INFORMATION'),'successful submit opens own trip');check(signup.errors.length===0,'participant UI no jsdom console errors');signup.dom.window.close();
const trip=await load(true,'trip');check(trip.d.body.textContent.includes('Church Bus')&&trip.d.body.textContent.includes('Family 101'),'participant renders own assignments');check(trip.d.body.textContent.includes('Trip sharing requires reviewed authority'),'adult household sharing not assumed');trip.signout();await tick();check(trip.d.body.textContent.includes('Sign in to join the team')&&!trip.d.body.textContent.includes('Family 101'),'session expiration clears private trip');trip.dom.window.close();
console.log(`${count} Phase B DOM checks passed`);
