import {PGlite} from '@electric-sql/pglite';import {readFileSync,readdirSync} from 'node:fs';import assert from 'node:assert/strict';
const db=new PGlite();let count=0;const ok=(v,n)=>{assert.ok(v,n);count++;console.log('PASS '+n)},id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,is_anonymous boolean default false);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth,public to anon,authenticated,service_role;grant execute on function auth.uid() to anon,authenticated,service_role;`);
const dir=new URL('../../supabase/migrations/',import.meta.url);for(const suffix of ['_organization_foundation.sql','_followup_tasks.sql','_staff_access_and_people.sql','_household_records.sql','_department_tags.sql','_tag_workflows.sql','_giving_configuration.sql','_participant_portals.sql'])await db.exec(readFileSync(new URL(readdirSync(dir).find(n=>n.endsWith(suffix)),dir),'utf8'));
const orgs=(await db.query('select id,slug from organizations')).rows,cl=orgs.find(x=>x.slug==='champion-life').id,sg=orgs.find(x=>x.slug==='sowgo').id;const areas=(await db.query('select * from portal_areas')).rows,member=areas.find(x=>x.area_key==='church_member'),dream=areas.find(x=>x.area_key==='dream_team'),partner=areas.find(x=>x.area_key==='sowgo_partner');
for(let n=1;n<=6;n++)await db.query('insert into auth.users values($1,$2,now(),false)',[id(n),`user${n}@example.test`]);
for(const org of [cl,sg])for(const permission of ['staff.manage','people.read','people.create','tags.read','tags.manage','portal.manage'])await db.query('insert into organization_staff_permissions(organization_id,user_id,permission) values($1,$2,$3)',[org,id(1),permission]);
for(const permission of ['people.read','tags.read','tags.manage'])await db.query('insert into organization_staff_permissions(organization_id,user_id,permission) values($1,$2,$3)',[cl,id(4),permission]);
async function as(n,role='authenticated'){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[n?id(n):'']);await db.exec('set role '+role)}async function no(sql,label){let failed=false;try{await db.exec(sql)}catch{failed=true}ok(failed,label)}
await as(1);const people={},tags={};for(const [org,label] of [[cl,'Church'],[sg,'Partner']]){people[org]=(await db.query(`insert into organization_people(organization_id,first_name,last_name) values($1,'Dual',$2) returning id`,[org,label])).rows[0].id;const dept=(await db.query('insert into organization_departments(organization_id,name) values($1,$2) returning id',[org,label])).rows[0].id;tags[org]=(await db.query('insert into organization_tags(organization_id,department_id,name) values($1,$2,$3) returning id',[org,dept,label])).rows[0].id;}
for(const area of areas){await db.query('insert into portal_resources(organization_id,area_id,title,body) values($1,$2,$3,$4)',[area.organization_id,area.id,area.title,'Private published content']);await db.query("update portal_resources set status='published' where area_id=$1",[area.id]);await db.query('insert into portal_resources(organization_id,area_id,title,body) values($1,$2,$3,$4)',[area.organization_id,area.id,'Draft only','Private draft']);}
await no(`insert into portal_resources(organization_id,area_id,title,body) values('${cl}','${partner.id}','Wrong','No')`,'resource cannot use other organization area');
await no(`select public.set_portal_tag_rule('${cl}','${partner.id}','${tags[cl]}',true,0)`,'church rule cannot grant partner organization area');
await db.query('select public.set_portal_tag_rule($1,$2,$3,true,0)',[cl,member.id,tags[cl]]);await db.query('select public.set_portal_tag_rule($1,$2,$3,true,0)',[sg,partner.id,tags[sg]]);
await as(4);await no(`insert into organization_person_tags(organization_id,person_id,tag_id) values('${cl}','${people[cl]}','${tags[cl]}')`,'ordinary tag manager cannot assign protected portal tag');
await as(1);for(const org of [cl,sg])await db.query('insert into organization_person_tags(organization_id,person_id,tag_id) values($1,$2,$3)',[org,people[org],tags[org]]);
await as(2);ok((await db.query('select * from portal_areas')).rows.length===0,'tag without reviewed account link grants no participant access');
await as(1);await no(`select public.set_portal_account_link('${cl}','${people[sg]}','user2@example.test',true,'Identity checked',0)`,'account link cannot claim other organization contact');await no(`select public.set_portal_account_link('${cl}','${people[cl]}','missing@example.test',true,'Identity checked',0)`,'unknown account cannot be linked');
for(const org of [cl,sg])await db.query('select public.set_portal_account_link($1,$2,$3,true,$4,0)',[org,people[org],'user2@example.test','Identity confirmed by administrator']);
await as(2);ok((await db.query('select * from portal_areas')).rows.length===2,'one login sees church and SowGo partner areas');ok((await db.query('select * from portal_resources')).rows.length===2,'dual participant sees published content for both organizations only');ok((await db.query("select * from portal_resources where title='Draft only'")).rows.length===0,'participant cannot read drafts');ok((await db.query('select * from portal_resources where area_id=$1',[dream.id])).rows.length===0,'member tag does not imply Dream Team area');
ok((await db.query('select * from organization_people')).rows.length===0,'portal link does not claim CRM contact ownership');ok((await db.query('select * from organization_staff_permissions')).rows.length===0,'portal access grants no staff permissions');ok((await db.query('select * from giving_destinations')).rows.length===0,'portal access grants no giving access');ok((await db.query('select * from portal_admin_events')).rows.length===0,'participant cannot read identity verification notes or admin history');ok((await db.query('select * from portal_account_links')).rows.length===0,'participant cannot enumerate account links');await no(`insert into portal_resources(organization_id,area_id,title,body) values('${cl}','${member.id}','No','No')`,'participant cannot publish resources');await no(`select public.set_portal_tag_rule('${cl}','${dream.id}','${tags[cl]}',true,0)`,'participant cannot self-upgrade');
await as(1);await db.query('select public.set_portal_tag_rule($1,$2,$3,true,0)',[cl,dream.id,tags[cl]]);await as(2);ok((await db.query('select * from portal_areas')).rows.length===3,'explicit Dream Team mapping adds third area');
await as(1);await db.query('select public.set_portal_tag_rule($1,$2,$3,false,1)',[cl,dream.id,tags[cl]]);await as(2);ok((await db.query('select * from portal_areas')).rows.length===2,'rule disable revokes area without token refresh');
await as(1);await db.query('update organization_person_tags set active=false where organization_id=$1',[cl]);await as(2);const remaining=(await db.query('select * from portal_areas')).rows;ok(remaining.length===1&&remaining[0].id===partner.id,'removing church tag preserves independent SowGo access');
await as(1);await db.query('update organization_person_tags set active=true where organization_id=$1',[cl]);await db.query('select public.set_portal_account_link($1,$2,null,false,$3,1)',[sg,people[sg],'Revoked at participant request']);await as(2);ok((await db.query('select * from portal_areas')).rows.length===1,'revoking partner account link preserves church access');
await as(1);await no(`select public.set_portal_account_link('${sg}','${people[sg]}',null,true,'Restoration verified',1)`,'stale account-link edit rejected');await db.query('select public.set_portal_account_link($1,$2,null,true,$3,2)',[sg,people[sg],'Restoration verified']);
const linked=(await db.query('select * from portal_account_links where organization_id=$1',[cl])).rows[0];await no(`select public.set_portal_account_link('${cl}','${people[cl]}','user3@example.test',true,'Existing identity cannot move',1)`,'explicit attempt to transfer existing link is rejected');ok((await db.query('select user_id from portal_account_links where id=$1',[linked.id])).rows[0].user_id===id(2),'existing link cannot silently transfer to another email');
await no('delete from portal_resources','resource deletion denied');await no('delete from portal_admin_events','portal audit deletion denied');await no("update portal_resources set area_id='"+partner.id+"'",'resource cannot move to another audience');
await as(4);await no("update organization_tags set active=false",'ordinary tag manager cannot archive a protected access tag');await no("update organization_departments set active=false",'ordinary tag manager cannot change protected department access');
await as(3);ok((await db.query('select * from portal_resources')).rows.length===0,'unrelated verified account cannot read portal content');
await db.exec('reset role');await db.query('update auth.users set email_confirmed_at=null where id=$1',[id(2)]);await as(2);ok((await db.query('select * from portal_resources')).rows.length===0,'unverified account loses participant content access');
await as(0,'anon');await no('select * from portal_resources','anonymous resources denied');await db.close();console.log(`${count} participant portal checks passed`);
