-- Run only on the authorized isolated acceptance branch. Every fixture rolls back.
begin;
do $test$
declare org uuid:=gen_random_uuid(); other_org uuid:=gen_random_uuid(); manager uuid:=gen_random_uuid(); viewer uuid:=gen_random_uuid();
 series jsonb; occurrence uuid; form jsonb; payload jsonb; result jsonb; reg uuid; att uuid; question uuid; ctx jsonb; n integer; passed integer:=0;
begin
 insert into public.organizations(id,slug,name,kind) values(org,'synthetic-registration-'||org,'Synthetic registration','church'),(other_org,'synthetic-registration-'||other_org,'Synthetic other','ministry');
 insert into auth.users(id,email,email_confirmed_at,is_anonymous) select x,'registration-'||x||'@example.test',now(),false from unnest(array[manager,viewer])x;
 insert into public.organization_staff_directory(organization_id,user_id,display_name) values(org,manager,'Synthetic manager'),(org,viewer,'Synthetic viewer');
 insert into public.organization_staff_permissions(organization_id,user_id,permission) select org,manager,k from unnest(array['events.manage','registrations.manage','registrations.restricted','checkin.manage','people.read','people.create'])k;
 insert into public.organization_staff_permissions(organization_id,user_id,permission) values(org,viewer,'registrations.view');
 perform set_config('request.jwt.claim.sub',manager::text,true);execute 'set local role authenticated';
 series:=public.events_workspace(org,'save',jsonb_build_object('title','Synthetic acceptance','local_start',(current_date+1)::text||'T10:00','local_end',(current_date+1)::text||'T11:00','timezone','UTC','visibility','public','registration_mode','native','capacity',1));
 series:=public.events_workspace(org,'save',jsonb_build_object('id',series->>'id','revision',series->'revision','status','published'));
 perform public.registrations_workspace(org,'settings',jsonb_build_object('series_id',series->>'id','revision',0,'enabled',true,'scope','occurrence','max_attendees',10));
 perform public.registrations_workspace(org,'question',jsonb_build_object('series_id',series->>'id','label','Private sample','kind','long_text','scope','attendee','sensitivity','restricted','required',true,'options','[]'::jsonb));
 ctx:=public.registrations_workspace(org,'context',jsonb_build_object('series_id',series->>'id'));occurrence:=(ctx#>>'{occurrences,0,id}')::uuid;question:=(ctx#>>'{questions,0,id}')::uuid;
 execute 'reset role';perform set_config('request.jwt.claim.sub','',true);execute 'set local role anon';
 form:=public.registration_public('synthetic-registration-'||org,'form',jsonb_build_object('series_id',series->>'id','occurrence_id',occurrence));
 if (form->>'remaining')::int<>1 or not(form->>'available')::boolean then raise exception 'Capacity projection failed';end if;passed:=passed+1;
 payload:=jsonb_build_object('series_id',series->>'id','occurrence_id',occurrence,'request_key',gen_random_uuid(),'form_revision',form->'revision','event_revision',form->'event_revision','registrant',jsonb_build_object('first_name','Synthetic','last_name','Parent','email','synthetic@example.test'),'attendees',jsonb_build_array(jsonb_build_object('first_name','Synthetic','last_name','Child','answers',jsonb_build_object(question::text,'PRIVATE ACCEPTANCE'))));
 result:=public.registration_public('synthetic-registration-'||org,'submit',payload);
 if result->>'status'<>'confirmed' or jsonb_array_length(result->'attendees')<>1 or result::text like '%PRIVATE ACCEPTANCE%' then raise exception 'Guest confirmation unsafe';end if;passed:=passed+1;
 if public.registration_public('synthetic-registration-'||org,'submit',payload)<>result then raise exception 'Idempotency failed';end if;passed:=passed+1;
 begin perform public.registration_public('synthetic-registration-'||org,'submit',payload||jsonb_build_object('request_key',gen_random_uuid()));raise exception 'Capacity bypass';exception when others then if sqlerrm='Capacity bypass' then raise;end if;end;passed:=passed+1;
 begin perform public.registration_public('synthetic-registration-'||org,'submit',payload||jsonb_build_object('payment_status','paid'));raise exception 'Payment injection';exception when others then if sqlerrm='Payment injection' then raise;end if;end;passed:=passed+1;
 begin perform 1 from public.event_registrations;raise exception 'Anon enumeration';exception when insufficient_privilege then null;end;passed:=passed+1;
 execute 'reset role';perform set_config('request.jwt.claim.sub',manager::text,true);execute 'set local role authenticated';
 result:=public.registrations_workspace(org,'list',jsonb_build_object('series_id',series->>'id','occurrence_id',occurrence));reg:=(result#>>'{registrations,0,id}')::uuid;att:=(result#>>'{registrations,0,attendees,0,id}')::uuid;
 if (result->>'checked_in')::int<>0 or result::text like '%PRIVATE ACCEPTANCE%' then raise exception 'Registration/list privacy failed';end if;passed:=passed+1;
 result:=public.registrations_workspace(org,'detail',jsonb_build_object('series_id',series->>'id','registration_id',reg));
 if result::text not like '%PRIVATE ACCEPTANCE%' then raise exception 'Restricted permission missing';end if;passed:=passed+1;
 execute 'reset role';perform set_config('request.jwt.claim.sub',viewer::text,true);execute 'set local role authenticated';
 result:=public.registrations_workspace(org,'detail',jsonb_build_object('series_id',series->>'id','registration_id',reg));
 if result::text like '%PRIVATE ACCEPTANCE%' then raise exception 'Restricted answer leaked';end if;passed:=passed+1;
 begin perform public.registrations_workspace(org,'status',jsonb_build_object('series_id',series->>'id','registration_id',reg,'revision',1,'status','cancelled'));raise exception 'Viewer mutation';exception when insufficient_privilege then null;end;passed:=passed+1;
 begin perform public.registrations_workspace(other_org,'detail',jsonb_build_object('series_id',series->>'id','registration_id',reg));raise exception 'Tenant bypass';exception when insufficient_privilege then null;end;passed:=passed+1;
 execute 'reset role';perform set_config('request.jwt.claim.sub',manager::text,true);execute 'set local role authenticated';
 perform public.registrations_workspace(org,'check_in',jsonb_build_object('series_id',series->>'id','occurrence_id',occurrence,'registration_id',reg,'revision',1));
 perform public.registrations_workspace(org,'check_in',jsonb_build_object('series_id',series->>'id','occurrence_id',occurrence,'registration_id',reg,'revision',2));
 result:=public.registrations_workspace(org,'detail',jsonb_build_object('series_id',series->>'id','registration_id',reg));
 if jsonb_array_length(result->'attendance')<>1 then raise exception 'Duplicate attendance';end if;passed:=passed+1;
 begin perform public.registrations_workspace(org,'status',jsonb_build_object('series_id',series->>'id','registration_id',reg,'revision',3,'status','cancelled'));raise exception 'Active attendance cancellation';exception when others then if sqlerrm='Active attendance cancellation' then raise;end if;end;passed:=passed+1;
 perform public.registrations_workspace(org,'undo',jsonb_build_object('series_id',series->>'id','occurrence_id',occurrence,'registration_id',reg,'revision',3));
 perform public.registrations_workspace(org,'status',jsonb_build_object('series_id',series->>'id','registration_id',reg,'revision',4,'status','cancelled'));
 result:=public.registrations_workspace(org,'detail',jsonb_build_object('series_id',series->>'id','registration_id',reg));
 if jsonb_array_length(result->'attendance')<>1 or result#>>'{attendance,0,reversed_at}' is null or result#>>'{registration,payment_status}'<>'not_required' then raise exception 'Durable attendance/payment separation';end if;passed:=passed+1;
 result:=public.registrations_workspace(org,'list',jsonb_build_object('series_id',series->>'id','occurrence_id',occurrence));if (result->>'remaining')::int<>1 then raise exception 'Capacity not restored';end if;passed:=passed+1;
 begin perform public.registrations_workspace(org,'status',jsonb_build_object('series_id',series->>'id','registration_id',reg,'revision',1,'status','confirmed'));raise exception 'Stale bypass';exception when others then if sqlerrm='Stale bypass' then raise;end if;end;passed:=passed+1;
 execute 'reset role';
 if exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='private' and p.proname like 'registration%' and p.prosecdef and p.proconfig is distinct from array['search_path=""']::text[]) then raise exception 'Unsafe path';end if;passed:=passed+1;
 raise notice '% Registration acceptance assertions passed',passed;
end $test$;
rollback;
select 'PASS: 17 Registration acceptance assertions; all synthetic records rolled back' as result;
