import{PGlite}from'@electric-sql/pglite';import{readFileSync,readdirSync}from'node:fs';import{randomUUID}from'node:crypto';import assert from'node:assert/strict';
const db=new PGlite(),q=(s,a=[])=>db.query(s,a);let count=0;const check=(v,m)=>{assert.ok(v,m);count++;console.log('PASS '+m);},deny=async(f,m)=>{await assert.rejects(f);check(true,m);};
await db.exec(readFileSync(new URL('fixtures/supabase-test-bootstrap.sql',import.meta.url),'utf8'));await db.exec(readFileSync(new URL('../../supabase/bootstrap/automatic-rls.sql',import.meta.url),'utf8'));for(const f of readdirSync(new URL('../../supabase/migrations',import.meta.url)).sort())await db.exec(readFileSync(new URL('../../supabase/migrations/'+f,import.meta.url),'utf8'));
const id=n=>`30000000-0000-4000-8000-${String(n).padStart(12,'0')}`,org=(await q("select id from organizations where slug='champion-life'")).rows[0].id,other=(await q("select id from organizations where slug='sowgo'")).rows[0].id;
for(let n=1;n<=6;n++){await q('insert into auth.users(id,email,email_confirmed_at) values($1,$2,now())',[id(n),`registration-${n}@example.test`]);await q("insert into organization_staff_directory(organization_id,user_id,display_name) values($1,$2,'Synthetic')",[org,id(n)]);}
await db.exec('alter table organization_departments disable trigger user');for(let n=11;n<=12;n++)await q('insert into organization_departments(id,organization_id,name) values($1,$2,$3)',[id(n),org,'Test Department '+n]);await db.exec('alter table organization_departments enable trigger user');
const permissions=['events.manage','registrations.manage','registrations.view','registrations.restricted','registrations.override','checkin.manage','people.read','people.create'];for(const key of permissions)await q('insert into organization_staff_permissions(organization_id,user_id,permission) values($1,$2,$3)',[org,id(1),key]);
for(const [n,key,scope]of[[2,'registrations.view',null],[3,'registrations.manage',[id(11)]],[3,'checkin.manage',[id(11)]],[4,'checkin.view',null],[6,'registrations.manage',null]])await q('insert into organization_staff_permissions(organization_id,user_id,permission,department_ids) values($1,$2,$3,$4)',[org,id(n),key,scope]);
const as=async(n,role=n?'authenticated':'anon')=>{await db.exec('reset role');await q("select set_config('request.jwt.claim.sub',$1,false)",[n?id(n):'']);await db.exec('set role '+role);};
const staff=async(a,d={},o=org)=>(await q('select registrations_workspace($1,$2,$3) v',[o,a,JSON.stringify(d)])).rows[0].v;
const pub=async(a,d={},slug='champion-life')=>(await q('select registration_public($1,$2,$3) v',[slug,a,JSON.stringify(d)])).rows[0].v;
const events=async(a,d)=>(await q('select events_workspace($1,$2,$3) v',[org,a,JSON.stringify(d)])).rows[0].v;
const tomorrow=(await q("select (current_date+1)::text d")).rows[0].d;
await as(1);
async function event(extra={},scope='occurrence'){
 let s=await events('save',{title:'Synthetic registration',local_start:tomorrow+'T10:00',local_end:tomorrow+'T11:00',timezone:'UTC',visibility:'public',registration_mode:'native',frequency:'daily',occurrence_count:3,...extra});
 s=await events('save',{id:s.id,revision:s.revision,status:'published',department_id:s.department_id});
 await staff('settings',{series_id:s.id,revision:0,scope,enabled:true,max_attendees:10,next_steps:'Arrive ten minutes early.'});const ctx=await staff('context',{series_id:s.id});return {s,ctx,occ:ctx.occurrences[0].id};
}
let e=await event({capacity:3,department_id:id(11)}),series=await event({capacity:2},'series');
async function question(kind,scope='registrant',sensitivity='general',required=true,options=[]){await staff('question',{series_id:e.s.id,revision:0,label:kind+' '+scope,kind,scope,sensitivity,required,active:true,display_order:1,options});return (await staff('context',{series_id:e.s.id})).questions.find(x=>x.kind===kind&&x.scope===scope);}
let consent=await question('consent'),sensitive=await question('long_text','attendee','restricted'),choice=await question('select','registrant','general',true,['A','B']);
const kinds=['short_text','email','phone','number','multi_select','yes_no','date'];for(const k of kinds)await question(k,'registrant','general',false,k==='multi_select'?['A','B']:[]);
const ctx=await staff('context',{series_id:e.s.id});check(ctx.questions.length===10,'bounded question types configured');
await deny(async()=>staff('settings',{series_id:e.s.id,revision:1,scope:'occurrence',max_attendees:10}),'stale settings rejected after questions');
await as(0);
const f=await pub('form',{series_id:e.s.id,occurrence_id:e.occ});check(f.remaining===3&&f.available,'bounded capacity form');check(!JSON.stringify(f).includes('restricted')&&!JSON.stringify(f).includes('email_confirmed'),'public form has intended fields only');
const payload=async(ev=e,n=1)=>{const form=await pub('form',{series_id:ev.s.id,occurrence_id:ev.occ});return {series_id:ev.s.id,occurrence_id:form.scope==='series'?null:ev.occ,request_key:randomUUID(),form_revision:form.revision,event_revision:form.event_revision,registrant:{first_name:'Parent',last_name:'Synthetic',email:'parent@example.test'},attendees:Array.from({length:n},(_,i)=>({first_name:i?'Child':'Parent',last_name:'Synthetic',is_registrant:!i,answers:ev===e?{[sensitive.id]:'PRIVATE MEDICAL ANSWER'}:{}})),answers:ev===e?{[consent.id]:true,[choice.id]:'A'}:{}};};
let p=await payload(e,2);let bad=structuredClone(p);bad.answers[consent.id]=false;await deny(async()=>pub('submit',bad),'required consent enforced');bad=structuredClone(p);delete bad.attendees[0].answers[sensitive.id];await deny(async()=>pub('submit',bad),'required attendee question enforced');bad=structuredClone(p);bad.answers[choice.id]='C';await deny(async()=>pub('submit',bad),'select choices enforced');
for(const [kind,val]of[['short_text','x'.repeat(501)],['email','wrong'],['phone','bad<>'],['number','3'],['multi_select',['C']],['yes_no','yes'],['date','2026-02-30']]){bad=structuredClone(p);bad.answers[ctx.questions.find(x=>x.kind===kind).id]=val;await deny(async()=>pub('submit',bad),kind+' validation');}
let confirmation=await pub('submit',p);check(confirmation.attendees.length===2,'guest parent and child registration');check(confirmation.status==='confirmed'&&confirmation.reference.startsWith('R-'),'confirmation and lifecycle');check(!JSON.stringify(confirmation).includes('PRIVATE')&&!JSON.stringify(confirmation).includes('person_id'),'no restricted or identity data in public confirmation');check((await pub('submit',p)).reference===confirmation.reference,'idempotent replay returns same confirmation');
bad=structuredClone(p);bad.attendees[0].first_name='Other';await deny(async()=>pub('submit',bad),'same key changed payload rejected');await deny(async()=>pub('detail',{series_id:e.s.id,occurrence_id:e.occ}),'anon cannot enumerate');await deny(async()=>q('select * from event_registrations'),'anon table read denied');await deny(async()=>q('select * from event_registration_answers'),'anon answers denied');
for(const extra of [{payment_status:'paid'},{payment_destination_id:randomUUID()},{status:'confirmed'},{person_id:randomUUID()}])await deny(async()=>pub('submit',{...p,request_key:randomUUID(),...extra}),'public privileged fields rejected '+Object.keys(extra)[0]);
check((await pub('form',{series_id:e.s.id,occurrence_id:e.occ})).remaining===1,'attendees consume capacity');await deny(async()=>pub('submit',payloadSync(p,2)),'last place refuses oversized group');
function payloadSync(p,n){return {...structuredClone(p),request_key:randomUUID(),attendees:structuredClone(p.attendees).slice(0,n)};}
const attempts=await Promise.allSettled([pub('submit',payloadSync(p,1)),pub('submit',payloadSync(p,1))]);check(attempts.filter(x=>x.status==='fulfilled').length===1,'concurrent client requests final slot has one winner (serialized local database)');check(!(await pub('form',{series_id:e.s.id,occurrence_id:e.occ})).available,'full form closes');
await as(1);let list=await staff('list',{series_id:e.s.id,occurrence_id:e.occ});check(list.used===3&&list.checked_in===0,'registration is not attendance');let reg=list.registrations.find(x=>x.reference===confirmation.reference),det=await staff('detail',{series_id:e.s.id,registration_id:reg.id,occurrence_id:e.occ});check(det.answers.some(x=>x.value==='PRIVATE MEDICAL ANSWER'),'restricted reader sees restricted answers');check(!JSON.stringify(list).includes('PRIVATE'),'list never contains answers');
await as(2);check((await staff('detail',{series_id:e.s.id,registration_id:reg.id})).answers.every(x=>!x.restricted),'ordinary viewer cannot read restricted answers');await deny(async()=>staff('status',{series_id:e.s.id,registration_id:reg.id,revision:reg.revision,status:'cancelled'}),'read-only permission cannot mutate');await deny(async()=>staff('undo',{series_id:e.s.id,occurrence_id:e.occ,registration_id:reg.id,revision:reg.revision}),'unauthorized reversal denied');
await as(4);check((await staff('detail',{series_id:e.s.id,registration_id:reg.id})).answers.length===0,'check-in viewer cannot read answers');await as(5);await deny(async()=>staff('detail',{series_id:e.s.id,registration_id:reg.id}),'ordinary member denied');await as(3);check((await staff('list',{series_id:e.s.id,occurrence_id:e.occ})).used===3,'department manager own scope');await deny(async()=>staff('context',{series_id:series.s.id}),'other department denied');await deny(async()=>staff('context',{series_id:e.s.id},other),'cross-org denied');await deny(async()=>staff('answer',{series_id:e.s.id,registration_id:reg.id,revision:reg.revision,answer_id:det.answers.find(x=>x.restricted).id,answer_revision:1,value:'Changed'}),'restricted edit needs extra permission');
await as(1);const change=async(action,data={})=>{const v=await staff(action,{series_id:e.s.id,registration_id:reg.id,occurrence_id:e.occ,revision:reg.revision,...data});reg.revision=v.revision;return v;};
await deny(async()=>change('check_in',{occurrence_id:e.ctx.occurrences[1].id}),'wrong occurrence denied');await change('check_in',{attendee_id:det.attendees[0].id});check((await staff('list',{series_id:e.s.id,occurrence_id:e.occ})).checked_in===1,'individual check-in');await change('check_in');await change('check_in');det=await staff('detail',{series_id:e.s.id,registration_id:reg.id});check(det.attendance.length===2,'group check-in unique records');await deny(async()=>change('status',{status:'cancelled'}),'cancellation with active attendance denied');await change('undo');await change('status',{status:'cancelled'});list=await staff('list',{series_id:e.s.id,occurrence_id:e.occ});check(list.remaining===2&&list.checked_in===0,'cancellation restores availability after reversal');check((await staff('detail',{series_id:e.s.id,registration_id:reg.id})).attendance.length===2,'attendance durable after reversal/cancellation');await deny(async()=>change('check_in'),'cancelled registration cannot check in');await deny(async()=>change('status',{revision:1,status:'confirmed'}),'stale revision denied');await change('status',{status:'confirmed'});check((await staff('list',{series_id:e.s.id,occurrence_id:e.occ})).used===3,'reinstatement reserves places');
await deny(async()=>staff('settings',{series_id:e.s.id,revision:(await staff('context',{series_id:e.s.id})).settings.revision,scope:'series',enabled:true,max_attendees:10}),'scope immutable after enrollment');
const answer=det.answers.find(x=>x.restricted);await staff('answer',{series_id:e.s.id,registration_id:reg.id,revision:reg.revision,answer_id:answer.id,answer_revision:answer.revision,value:'UPDATED PRIVATE'});reg.revision++;det=await staff('detail',{series_id:e.s.id,registration_id:reg.id});check(det.history.some(x=>x.action==='restricted_answer_changed')&&!JSON.stringify(det.history).includes('UPDATED PRIVATE'),'restricted edits audited without values');
await deny(async()=>staff('question',{series_id:e.s.id,...sensitive,organization_id:undefined,sensitivity:'general'}),'answered privacy cannot be downgraded');
let walk={series_id:e.s.id,occurrence_id:e.occ,request_key:randomUUID(),first_name:'Walk',last_name:'Unique',create_person:true,answers:{[consent.id]:true,[choice.id]:'A'},attendee_answers:{[sensitive.id]:'WALK-IN PRIVATE'}};await deny(async()=>staff('walk_in',walk),'full walk-in requires explicit override');await as(6);await deny(async()=>staff('walk_in',{...walk,override:true,override_reason:'Synthetic override'}),'registration manager cannot check in or override');await as(1);let walked=await staff('walk_in',{...walk,override:true,override_reason:'Synthetic extra seat approved'});check((await staff('walk_in',{...walk,override:true,override_reason:'Synthetic extra seat approved'})).id===walked.id,'walk-in idempotency');let wd=await staff('detail',{series_id:e.s.id,registration_id:walked.id});check(wd.attendance.length===1&&wd.registration.person_id,'walk-in creates contact and durable attendance');check(wd.history.some(x=>x.action==='capacity_override'),'override audit');await deny(async()=>staff('walk_in',{...walk,request_key:randomUUID(),override:true,override_reason:'Synthetic override'}),'ambiguous contact match requires explicit reconciliation');
await db.exec('reset role');check((await q('select count(*)::int n from organization_staff_permissions where user_id not in ($1,$2,$3,$4,$5,$6)',[1,2,3,4,5,6].map(id))).rows[0].n===0,'no privilege created by walk-in');await q("insert into portal_account_links(organization_id,person_id,user_id,verification_note) values($1,$2,$3,'Reviewed synthetic fixture')",[org,wd.registration.person_id,id(5)]);await as(5);let sp=await payload(series,1);let sc=await pub('submit',sp);check(sc.scope==='series','series enrollment');await as(1);let sl=await staff('list',{series_id:series.s.id,occurrence_id:series.ctx.occurrences[1].id});let sr=sl.registrations[0];let sd=await staff('detail',{series_id:series.s.id,registration_id:sr.id});check(sd.registration.person_id===wd.registration.person_id&&sd.attendees[0].person_id===wd.registration.person_id,'reviewed account link reused without duplicate person');await staff('check_in',{series_id:series.s.id,registration_id:sr.id,revision:sr.revision,occurrence_id:series.ctx.occurrences[1].id});check((await staff('list',{series_id:series.s.id,occurrence_id:series.ctx.occurrences[0].id})).used===1,'series capacity shared across dates');
let unlimited=await event(),paid=await event({payment_required:true}),external=await event({registration_mode:'external',registration_url:'https://example.test/registration'});await as(0);check((await pub('form',{series_id:unlimited.s.id,occurrence_id:unlimited.occ})).remaining===null,'unlimited capacity');let up=await payload(unlimited,3);check((await pub('submit',up)).attendees.length===3,'unlimited multi-attendee');await deny(async()=>pub('submit',{...await payload(paid),payment_status:undefined}),'payment-required fails closed');await deny(async()=>pub('form',{series_id:external.s.id,occurrence_id:external.occ}),'external mode is preserved');
await as(1);await deny(async()=>staff('edit',{series_id:e.s.id,registration_id:reg.id,revision:reg.revision,first_name:'Parent',last_name:'Synthetic',payment_status:'paid'}),'staff browser cannot forge paid');
let ul=await staff('list',{series_id:unlimited.s.id,occurrence_id:unlimited.occ}),ur=ul.registrations[0];
await staff('add_attendee',{series_id:unlimited.s.id,registration_id:ur.id,revision:ur.revision,first_name:'Added',last_name:'Attendee',answers:{}});
let ud=await staff('detail',{series_id:unlimited.s.id,registration_id:ur.id});check(ud.attendees.length===4,'staff adds attendee');
await staff('remove_attendee',{series_id:unlimited.s.id,registration_id:ur.id,revision:ud.registration.revision,attendee_id:ud.attendees.find(x=>x.first_name==='Added').id});
ud=await staff('detail',{series_id:unlimited.s.id,registration_id:ur.id});check(ud.attendees.length===3&&ud.history.some(x=>x.action==='attendee_removed'),'staff removes un-attended attendee with audit');
await deny(async()=>staff('remove_attendee',{series_id:e.s.id,registration_id:reg.id,revision:reg.revision,attendee_id:det.attendees[0].id}),'attendee with historical attendance cannot be removed');
await db.exec('reset role');check((await q('select count(*)::int n from event_registrations where payment_status<>\'not_required\'')).rows[0].n===0,'payment and lifecycle remain independent');check((await q("select count(*)::int n from pg_class where relnamespace='public'::regnamespace and relname in ('event_registration_settings','event_registration_questions','event_registrations','event_registration_attendees','event_registration_answers','event_attendance','registration_audit') and relrowsecurity")).rows[0].n===7,'all registration tables RLS');
await db.exec(readFileSync(new URL('registration.acceptance.sql',import.meta.url),'utf8'));
console.log(`${count} Registration + Check-in checks plus 17 rollback assertions passed`);await db.close();
