const {JSDOM}=require('jsdom'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const root=path.resolve(__dirname,'../..');
const dom=new JSDOM(fs.readFileSync(path.join(root,'staff-people.html'),'utf8'),{runScripts:'outside-only',url:'https://workspace.test/staff-people.html'}),w=dom.window,d=w.document;
w.HTMLDialogElement.prototype.close=function(){this.open=false};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};
let member=null,person=null,callback,task=null;const calls=[];
const grants=['staff.manage','people.read','people.create','people.update','followup.read','followup.manage'];
w.ChampionLifeAuth={getUser:async()=>({id:'admin'}),client:{auth:{onAuthStateChange(fn){callback=fn}},async rpc(name,args){calls.push({name,args});if(name==='list_staff_directory')return {data:member?[member]:[],error:null};if(name==='set_staff_access'){member={user_id:'worker',display_name:args.p_name,permissions:args.p_permissions,revision:(member?.revision||0)+1};return {data:{user_id:'worker'},error:null}}},from(table){let mode='select',values;const q={select(){return q},eq(){return q},is(){return q},order(){return q},range(){return q},limit(){return q},maybeSingle(){return q},insert(v){mode='insert';values=v;return q},update(v){mode='update';values=v;return q},then(resolve){let data=[];
if(table==='organizations')data=[{id:'church',name:'Champion Life'}];if(table==='organization_staff_permissions')data=grants.map(permission=>({organization_id:'church',permission}));
if(table==='organization_people'){if(mode==='insert'){person={...values,id:'person',updated_at:'2026-09-26'};data={id:'person'};}else data=person?[person]:[];}
if(table==='followup_tasks'){if(mode==='insert'){task={...values,id:'task',status:'open',revision:1,person};data={id:'task'};}else data=task?[task]:[];}
return Promise.resolve({data,error:null}).then(resolve);}};return q;}}};
w.eval(fs.readFileSync(path.join(root,'assets/js/staff-admin.js'),'utf8'));w.eval(fs.readFileSync(path.join(root,'assets/js/staff-people.js'),'utf8'));
const wait=()=>new Promise(r=>setTimeout(r,0)),click=s=>d.querySelector(s).click(),submit=id=>d.getElementById(id).dispatchEvent(new w.Event('submit',{cancelable:true}));
(async()=>{await wait();click('.sidebar [data-view="staff"]');await wait();click('#staff-add');d.getElementById('staff-email').value='worker@example.test';d.getElementById('staff-name').value='Team Member';
assert.equal(d.querySelector('[value="staff.manage"]'),null);assert.equal(d.querySelector('[value="finance.read"]'),null);
for(const permission of ['people.read','followup.read'])d.querySelector(`#staff-permissions input[value="${permission}"]`).checked=true;submit('staff-form');await wait();await wait();assert.match(d.getElementById('staff-list').textContent,/Team Member/);assert.equal(calls.find(c=>c.name==='set_staff_access').args.p_revision,0);
click('.sidebar [data-view="people"]');await wait();assert.equal(d.getElementById('person-add').hidden,false);click('#person-add');const form=d.getElementById('person-form');form.elements.namedItem('first_name').value='Jane';form.elements.namedItem('last_name').value='Example';form.elements.namedItem('email').value='jane@example.test';submit('person-form');await wait();await wait();assert.equal(person.organization_id,'church');assert.equal(person.user_id,undefined);assert.match(d.getElementById('people').textContent,/Jane Example/);
click('#people button:last-child');await wait();assert.equal(d.querySelector('#task-assignee option[value="worker"]').textContent,'Team Member');d.getElementById('task-title').value='Welcome call';d.getElementById('task-assignee').value='worker';submit('task-form');await wait();await wait();assert.equal(task.assigned_user_id,'worker');
click('.sidebar [data-view="staff"]');await wait();click('#staff-list button');assert.equal(d.getElementById('staff-email-label').hidden,true);d.querySelectorAll('#staff-permissions input').forEach(input=>input.checked=false);submit('staff-form');await wait();await wait();assert.match(d.getElementById('staff-list').textContent,/Access removed/);assert.equal(calls.filter(c=>c.name==='set_staff_access').at(-1).args.p_revision,1);
click('#staff-add');d.getElementById('staff-email').value='private@example.test';callback('SIGNED_OUT',null);assert.equal(d.getElementById('staff-editor').open,false);assert.equal(d.getElementById('staff-email').value,'');assert.equal(d.getElementById('staff-list').textContent,'');
console.log('PASS staff UI: delegation choices, grant, contact creation, team assignment, revocation, revision and account clearing');dom.window.close();})().catch(e=>{console.error(e);process.exitCode=1;dom.window.close()});
