import {PGlite} from '@electric-sql/pglite';import {readFileSync,readdirSync} from 'node:fs';import assert from 'node:assert/strict';
const db=new PGlite();let count=0;const ok=(v,n)=>{assert.ok(v,n);count++;console.log('PASS '+n)};const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,is_anonymous boolean default false);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth,public to anon,authenticated,service_role;grant execute on function auth.uid() to anon,authenticated,service_role;`);
const dir=new URL('../../supabase/migrations/',import.meta.url);for(const suffix of ['_organization_foundation.sql','_followup_tasks.sql','_staff_access_and_people.sql'])await db.exec(readFileSync(new URL(readdirSync(dir).find(n=>n.endsWith(suffix)),dir),'utf8'));
const orgs=(await db.query('select id,slug from organizations')).rows,cl=orgs.find(x=>x.slug==='champion-life').id,sg=orgs.find(x=>x.slug==='sowgo').id;
for(let n=1;n<=6;n++)await db.query('insert into auth.users values($1,$2,$3,false)',[id(n),`staff${n}@example.test`,n===5?null:new Date().toISOString()]);
for(const permission of ['staff.manage','people.read','people.create','people.update','followup.read','followup.manage'])await db.query('insert into organization_staff_permissions(organization_id,user_id,permission) values($1,$2,$3)',[cl,id(1),permission]);
await db.query("insert into organization_staff_permissions(organization_id,user_id,permission) values($1,$2,'staff.manage')",[sg,id(3)]);
async function as(n,role='authenticated'){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[n?id(n):'']);await db.exec('set role '+role)}
async function rejects(fn,label){let rejected=false;try{await fn()}catch{rejected=true}ok(rejected,label)}
async function set(target,email,perms,rev=0,org=cl,name='Staff member'){return (await db.query('select public.set_staff_access($1,$2,$3,$4,$5,$6) as value',[org,target,email,name,perms,rev])).rows[0].value}
const directory=async (org=cl,assign=true)=>(await db.query('select public.list_staff_directory($1,$2) as value',[org,assign])).rows[0].value;
await as(2);await rejects(()=>set(null,'staff4@example.test',['people.read']),'non-admin cannot grant access');await rejects(()=>directory(cl,false),'non-admin cannot inspect staff permissions');
await as(1);await rejects(()=>set(null,'staff2@example.test',['staff.manage']),'admin cannot delegate administrator permission');await rejects(()=>set(null,'staff2@example.test',['finance.read']),'cannot grant permission actor does not own');await rejects(()=>set(null,'staff1@example.test',['people.read']),'cannot modify own access');await rejects(()=>set(null,'staff3@example.test',['people.read'],0,sg),'cross-organization administration denied');await rejects(()=>set(null,'staff5@example.test',['people.read']),'unverified target rejected');await rejects(()=>set(null,'missing@example.test',['people.read']),'unknown email rejected');await rejects(()=>set(null,'staff2@example.test',['followup.manage']),'permission dependencies enforced');
let granted=await set(null,'staff2@example.test',['people.read','people.create','followup.read','followup.manage']);ok(granted.user_id===id(2)&&granted.revision===1,'verified staff gets explicit scoped access');
let list=await directory(cl,false);ok(list.length===1&&list[0].permissions.includes('people.create'),'admin directory shows scoped permission set');await rejects(()=>set(id(2),null,['people.read'],0),'stale staff revision rejected');await rejects(()=>set(id(6),null,['people.read'],0),'arbitrary target UUID rejected');
ok((await directory()).length===1,'eligible assignee listed');
await as(2);list=await directory();ok(list.length===1&&list[0].permissions.length===0,'assignment directory hides permission details');await rejects(()=>directory(sg),'other organization directory denied');
const person=(await db.query(`insert into organization_people(organization_id,first_name,last_name,email) values($1,' New ',' Person ','family@example.test') returning *`,[cl])).rows[0];ok(person.user_id===null&&person.first_name==='New','new contact does not create or claim identity');
await rejects(()=>db.query(`insert into organization_people(organization_id,first_name,last_name) values($1,'No','Access')`,[sg]),'contact creation cannot cross organizations');await rejects(()=>db.query(`insert into organization_people(organization_id,user_id,first_name,last_name) values($1,$2,'No','Claim')`,[cl,id(4)]),'contact creation cannot forge account link');
ok((await db.query('select * from organization_admin_events')).rows.every(x=>x.kind!=='staff_access'),'people reader cannot see permission audit');
await as(1);const before=person.updated_at;const updated=(await db.query(`update organization_people set phone='123',updated_at='2000-01-01' where id=$1 returning updated_at`,[person.id])).rows[0];ok(new Date(updated.updated_at)>new Date('2000-01-01'),'server owns contact modification timestamp');
let events=(await db.query('select * from organization_admin_events')).rows;ok(events.some(x=>x.kind==='person_created')&&events.some(x=>x.kind==='person_updated')&&events.some(x=>x.kind==='staff_access'),'contact and staff actions audited');await rejects(()=>db.exec('delete from organization_admin_events'),'audit deletion denied');await rejects(()=>db.exec('update organization_staff_permissions set revoked_at=null'),'direct permission writes still denied');
await set(id(2),null,[],1);ok((await directory()).length===0,'revoked staff removed from assignment directory');await as(2);await rejects(()=>directory(),'revoked staff directory access denied immediately');await rejects(()=>db.query(`insert into organization_people(organization_id,first_name,last_name) values($1,'No','More')`,[cl]),'revoked contact creation denied immediately');
await as(1);await set(id(2),null,['people.read'],2);await as(2);await rejects(()=>db.query(`insert into organization_people(organization_id,first_name,last_name) values($1,'Read','Only')`,[cl]),'read access does not grant create');
await as(0,'anon');await rejects(()=>directory(),'anonymous directory access denied');await rejects(()=>set(null,'staff4@example.test',['people.read']),'anonymous staff administration denied');
await db.close();console.log(`${count} staff/contact checks passed`);
