import {PGlite} from '@electric-sql/pglite';
import {readFileSync,readdirSync} from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();let count=0;const ok=(v,n)=>{assert.ok(v,n);count++;console.log('PASS '+n)};
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,is_anonymous boolean default false);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth,public to anon,authenticated,service_role;grant execute on function auth.uid() to anon,authenticated,service_role;`);
const dir=new URL('../../supabase/migrations/',import.meta.url);
for(const suffix of ['_organization_foundation.sql','_followup_tasks.sql','_staff_access_and_people.sql','_household_records.sql','_department_tags.sql'])await db.exec(readFileSync(new URL(readdirSync(dir).find(n=>n.endsWith(suffix)),dir),'utf8'));
const orgs=(await db.query('select id,slug from organizations')).rows,cl=orgs.find(x=>x.slug==='champion-life').id,sg=orgs.find(x=>x.slug==='sowgo').id;
for(let n=1;n<=6;n++)await db.query('insert into auth.users values($1,$2,now(),false)',[id(n),`staff${n}@example.test`]);
for(const [org,user,perms] of [[cl,id(1),['staff.manage','people.read','people.create','tags.read','tags.manage','finance.read']],[cl,id(2),['people.read','tags.read']],[sg,id(3),['people.read','people.create','tags.read','tags.manage']],[cl,id(4),['people.read','followup.read']],[cl,id(5),['staff.manage']]])for(const permission of perms)await db.query('insert into organization_staff_permissions(organization_id,user_id,permission) values($1,$2,$3)',[org,user,permission]);
async function as(n,role='authenticated'){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[n?id(n):'']);await db.exec('set role '+role)}
async function no(sql,label){let failed=false;try{await db.exec(sql)}catch{failed=true}ok(failed,label)}
await as(1);
const p=(await db.query(`insert into organization_people(organization_id,first_name,last_name) values($1,'Test','Person') returning id`,[cl])).rows[0].id;
const d=(await db.query(`insert into organization_departments(organization_id,name,leader_user_id) values($1,' Serving ',$2) returning *`,[cl,id(4)])).rows[0];
ok(d.name==='Serving'&&d.revision===1,'department has trimmed name and server revision');
await no(`insert into organization_departments(organization_id,name) values('${cl}','serving')`,'case-insensitive duplicate department rejected');
await no(`update organization_departments set leader_user_id='${id(3)}'`,'cross-organization leader rejected');
await no(`update organization_departments set leader_user_id='${id(2)}'`,'leader without follow-up access rejected');
const t=(await db.query(`insert into organization_tags(organization_id,department_id,name) values($1,$2,'Dream Team') returning *`,[cl,d.id])).rows[0];
const m=(await db.query(`insert into organization_person_tags(organization_id,person_id,tag_id) values($1,$2,$3) returning *`,[cl,p,t.id])).rows[0];
ok(m.active,'assign operational tag');
ok((await db.query("select * from organization_tag_events where kind='tag_assigned'")).rows.length===1,'assignment produces one durable event');
await db.query('update organization_person_tags set active=true where id=$1',[m.id]);
ok((await db.query("select * from organization_tag_events where kind='tag_assigned'")).rows.length===1,'saving unchanged tag produces no duplicate event');
await no(`insert into organization_person_tags(organization_id,person_id,tag_id) values('${cl}','${p}','${t.id}')`,'duplicate assignment rejected');
await db.query('update organization_person_tags set active=false where id=$1 and revision=1',[m.id]);
ok((await db.query('update organization_person_tags set active=true where id=$1 and revision=1 returning id',[m.id])).rows.length===0,'stale assignment edit rejected');
await db.query('update organization_person_tags set active=true where id=$1 and revision=2',[m.id]);
ok((await db.query("select * from organization_tag_events where kind='tag_assigned'")).rows.length===2,'remove then restore records a new assignment event');
await no('update organization_person_tags set revision=99','cannot forge assignment revision');
await no(`update organization_person_tags set person_id='${id(6)}'`,'cannot transfer assignment identity');
await no('delete from organization_person_tags','cannot delete assignment history');
await no("update organization_tag_events set kind='tag_removed'",'cannot rewrite audit events');
await db.query('update organization_tags set active=false where id=$1',[t.id]);
await db.query('update organization_person_tags set active=false where id=$1',[m.id]);
await no('update organization_person_tags set active=true','archived tag blocks restoration');
await db.query('update organization_tags set active=true where id=$1',[t.id]);
await db.query('update organization_departments set active=false where id=$1',[d.id]);
await no('update organization_person_tags set active=true','archived department blocks restoration');
await db.query('update organization_departments set active=true where id=$1',[d.id]);
await as(3);
const other=(await db.query(`insert into organization_people(organization_id,first_name,last_name) values($1,'Other','Person') returning id`,[sg])).rows[0].id;
ok((await db.query('select * from organization_tags')).rows.length===0,'cross-organization tags hidden');
ok((await db.query('select * from organization_tag_events')).rows.length===0,'cross-organization history hidden');
await no(`insert into organization_tags(organization_id,department_id,name) values('${sg}','${d.id}','No')`,'cross-organization department rejected');
await as(1);await no(`insert into organization_person_tags(organization_id,person_id,tag_id) values('${cl}','${other}','${t.id}')`,'cross-organization person rejected');
await as(2);ok((await db.query('select * from organization_tags')).rows.length===1,'read-only staff can view tags');
ok((await db.query("update organization_tags set name='No' returning id")).rows.length===0,'read-only staff cannot edit tags');
await no(`insert into organization_departments(organization_id,name) values('${cl}','No')`,'read-only staff cannot create department');
await as(4);ok((await db.query('select * from organization_person_tags')).rows.length===0,'department leadership does not grant tag access');
ok((await db.query("select * from organization_staff_permissions where permission='finance.read'")).rows.length===0,'department leader has no inferred giving permission');
await as(5);await no(`select public.set_staff_access('${cl}',null,'staff6@example.test','Finance',array['finance.read'],0)`,'admin without finance authority cannot delegate giving access');
await as(1);await no(`select public.set_staff_access('${cl}',null,'staff6@example.test','Tags',array['people.read','tags.manage'],0)`,'tag delegation requires tag read');
await db.exec(`select public.set_staff_access('${cl}',null,'staff6@example.test','Finance',array['finance.read'],0)`);
await as(6);ok((await db.query("select * from organization_staff_permissions where permission='finance.read' and revoked_at is null")).rows.length===1,'admin explicitly grants giving access');
await no(`insert into organization_staff_permissions(organization_id,user_id,permission) values('${cl}','${id(6)}','tags.manage')`,'staff cannot self-grant permissions');
await as(1);await db.exec(`select public.set_staff_access('${cl}','${id(6)}',null,'Finance',array[]::text[],1)`);
await as(6);ok((await db.query("select * from organization_staff_permissions where permission='finance.read' and revoked_at is null")).rows.length===0,'admin revokes giving permission');
await db.exec('reset role');await db.exec(`update organization_staff_permissions set revoked_at=now() where user_id='${id(2)}' and permission='tags.read'`);
await as(2);ok((await db.query('select * from organization_tag_events')).rows.length===0,'revocation removes tag history access');
await as(0,'anon');await no('select * from organization_tags','anonymous tags access denied');
await db.close();console.log(`${count} tag and finance permission checks passed`);
