const {JSDOM}=require('jsdom'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..'),dom=new JSDOM(fs.readFileSync(path.join(root,'staff-people.html'),'utf8'),{runScripts:'outside-only',url:'https://workspace.test/staff-people.html'}),w=dom.window,d=w.document;
w.HTMLDialogElement.prototype.close=function(){this.open=false};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};
let invalid=false,canManage=true,conflict=false,late=null;const calls=[],rows={organization_departments:[],organization_tags:[],organization_person_tags:[]};
const auth={getUser:async()=>({id:'staff'}),client:{rpc:async()=>({data:[{user_id:'leader',display_name:'Team leader'}]}),from(table){let mode='select',values,single=false;const filters={},q={select(){return q},eq(k,v){filters[k]=v;return q},order(){return q},range(){return q},limit(){return q},ilike(){return q},maybeSingle(){single=true;return q},insert(v){mode='insert';values=v;return q},update(v){mode='update';values=v;return q},then(resolve){calls.push({table,mode,filters,values});
if(late&&mode==='select')return late.then(resolve);
let data=[];if(mode==='insert'){const row={...values,id:table+'1',active:true,revision:1};if(table==='organization_person_tags')row.tag={name:'Dream Team <script>'};rows[table].push(row);data={id:row.id};}
else if(mode==='update'){const row=rows[table].find(x=>x.id===filters.id);if(conflict)data=null;else{Object.assign(row,values,{revision:row.revision+1});data={id:row.id};}}
else data=rows[table].filter(x=>Object.entries(filters).every(([k,v])=>x[k]===v));return Promise.resolve({data,error:null}).then(resolve);}};return q;}}};
w.eval(fs.readFileSync(path.join(root,'assets/js/staff-tags.js'),'utf8'));const mod=w.ChampionTags({auth,getContext:()=>({user:{id:'staff'},organizationId:'church',invalid,can:p=>p==='tags.manage'?canManage:true}),onAccountChange:()=>{invalid=true;mod.clear()}});
const wait=()=>new Promise(r=>setTimeout(r,0)),click=s=>d.querySelector(s).click(),submit=id=>d.getElementById(id).dispatchEvent(new w.Event('submit',{cancelable:true})),change=(id,v)=>{d.getElementById(id).value=v;d.getElementById(id).dispatchEvent(new w.Event('change'));};
(async()=>{change('tags-kind','departments');await wait();click('#tags-add');await wait();d.getElementById('tag-name').value='Serving';d.getElementById('tag-leader').value='leader';submit('tag-form');await wait();await wait();assert.equal(rows.organization_departments[0].leader_user_id,'leader');assert.equal(rows.organization_departments[0].organization_id,'church');
change('tags-kind','tags');await wait();click('#tags-add');await wait();d.getElementById('tag-name').value='Dream Team <script>';d.getElementById('tag-department').value='organization_departments1';d.getElementById('tag-due-days').value='3';submit('tag-form');await wait();await wait();assert.equal(rows.organization_tags[0].due_after_days,3);assert.equal(d.querySelector('#tags-list script'),null);
await mod.openPerson({id:'person',first_name:'Jane',last_name:'Example'});click('#person-tag-find');await wait();submit('person-tag-form');await wait();await wait();assert.equal(rows.organization_person_tags[0].person_id,'person');assert.match(d.getElementById('person-tags-list').textContent,/Dream Team/);assert.equal(d.querySelector('#person-tags-list script'),null);
click('#person-tags-list button');await wait();await wait();assert.equal(rows.organization_person_tags[0].active,false);click('#person-tags-list button');await wait();await wait();assert.equal(rows.organization_person_tags[0].active,true);
conflict=true;click('#person-tags-list button');await wait();assert.match(d.getElementById('person-tags-status').textContent,/not saved/);assert.equal(rows.organization_person_tags[0].active,true);conflict=false;
click('#person-tags-close');click('#tags-list button');await wait();d.getElementById('tag-active').value='false';submit('tag-form');await wait();await wait();assert.equal(rows.organization_tags[0].active,false);
canManage=false;await mod.load();assert.equal(d.getElementById('tags-add').hidden,true);await mod.openPerson({id:'person',first_name:'Jane',last_name:'Example'});assert.equal(d.getElementById('person-tag-form').hidden,true);assert.equal(d.querySelectorAll('#person-tags-list button').length,0);
for(const call of calls.filter(c=>c.mode==='update')){assert.equal(call.filters.organization_id,'church');assert.ok(call.filters.revision);}
let resolveLate;late=new Promise(r=>resolveLate=r);const pending=mod.load();invalid=true;mod.clear();resolveLate({data:[{name:'Late private record',id:'late'}],error:null});await pending;assert.equal(d.getElementById('tags-list').textContent,'');assert.equal(d.getElementById('person-tags-list').textContent,'');assert.equal(d.getElementById('tag-name').value,'');
console.log('PASS tag UI: departments, leaders, tag setup, assignment/removal/restoration, conflict, archival, read-only, safe text and late-response isolation');dom.window.close();})().catch(e=>{console.error(e);process.exitCode=1;dom.window.close()});
