
create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  first_name text,
  last_name text,
  email text,
  phone text,
  givehub_contact_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  title text not null,
  description text,
  total_lessons integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.course_enrollments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  unique(user_id, course_id)
);

create table if not exists public.lesson_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  lesson_number integer not null check (lesson_number > 0),
  status text not null default 'not_started' check (status in ('not_started','in_progress','completed')),
  started_at timestamptz,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  unique(user_id, course_id, lesson_number)
);

create table if not exists public.lesson_answers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  lesson_number integer not null check (lesson_number > 0),
  question_number integer not null check (question_number > 0),
  answer text not null default '',
  updated_at timestamptz not null default now(),
  unique(user_id, course_id, lesson_number, question_number)
);

insert into public.courses (slug,title,description,total_lessons)
values ('getting-a-grip-on-the-basics','Getting a Grip on the Basics','Champion Life 13-week discipleship course',13)
on conflict (slug) do update set title=excluded.title, description=excluded.description, total_lessons=excluded.total_lessons;

alter table public.profiles enable row level security;
alter table public.courses enable row level security;
alter table public.course_enrollments enable row level security;
alter table public.lesson_progress enable row level security;
alter table public.lesson_answers enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles for select to authenticated using (auth.uid() = user_id);
drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own" on public.profiles for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "courses_read_authenticated" on public.courses;
create policy "courses_read_authenticated" on public.courses for select to authenticated using (true);

drop policy if exists "enrollments_select_own" on public.course_enrollments;
create policy "enrollments_select_own" on public.course_enrollments for select to authenticated using (auth.uid() = user_id);
drop policy if exists "enrollments_insert_own" on public.course_enrollments;
create policy "enrollments_insert_own" on public.course_enrollments for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "enrollments_update_own" on public.course_enrollments;
create policy "enrollments_update_own" on public.course_enrollments for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "progress_select_own" on public.lesson_progress;
create policy "progress_select_own" on public.lesson_progress for select to authenticated using (auth.uid() = user_id);
drop policy if exists "progress_insert_own" on public.lesson_progress;
create policy "progress_insert_own" on public.lesson_progress for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "progress_update_own" on public.lesson_progress;
create policy "progress_update_own" on public.lesson_progress for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "answers_select_own" on public.lesson_answers;
create policy "answers_select_own" on public.lesson_answers for select to authenticated using (auth.uid() = user_id);
drop policy if exists "answers_insert_own" on public.lesson_answers;
create policy "answers_insert_own" on public.lesson_answers for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "answers_update_own" on public.lesson_answers;
create policy "answers_update_own" on public.lesson_answers for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
