import nodemailer from 'npm:nodemailer@10.0.16';
import {bindingFor,smtpAdapter} from './activation.mjs';
export function runtime(){const environment=Deno.env.get('COMMUNICATIONS_ENVIRONMENT'),ref=Deno.env.get('COMMUNICATIONS_PROJECT_REF'),url=Deno.env.get('SUPABASE_URL');if(!environment||!['acceptance','production'].includes(environment)||!ref||url!=='https://'+ref+'.supabase.co'||(environment==='acceptance')!==(ref==='bkbmjisprwmkptywtmih'))throw Error('Environment unavailable');return{environment,project_ref:ref};}
export function enabled(){try{runtime();return Deno.env.get('COMMUNICATIONS_RUNTIME_ENABLED')==='true';}catch{return false;}}
export async function rpc(action:string,org:string,payload:unknown={},token?:string){const rt=runtime(),key=token?Deno.env.get('SUPABASE_ANON_KEY'):Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!key)throw Error('Service unavailable');const r=await fetch('https://'+rt.project_ref+'.supabase.co/rest/v1/rpc/'+(token?'communications_provider_workspace':'communications_provider_service'),{method:'POST',headers:{apikey:key,Authorization:'Bearer '+(token||key),'Content-Type':'application/json'},body:JSON.stringify({p_action:action,p_organization:org,p_payload:payload})});if(!r.ok)throw Error('Provider operation denied');return r.json();}
export function registry(){try{return JSON.parse(Deno.env.get('COMMUNICATIONS_PROVIDER_SECRETS_JSON')||'{}');}catch{throw Error('Provider configuration unavailable');}}
export function resolve(profile:Record<string,unknown>){const b=bindingFor(registry(),profile,runtime());if(profile.provider==='smtp_transport')return smtpAdapter(nodemailer,b);throw Error('NOT CONFIGURED / PROVIDER SELECTION REQUIRED');}
export async function user(token:string){const rt=runtime(),key=Deno.env.get('SUPABASE_ANON_KEY');if(!key)throw Error('Service unavailable');const r=await fetch('https://'+rt.project_ref+'.supabase.co/auth/v1/user',{headers:{apikey:key,Authorization:'Bearer '+token}});if(!r.ok)throw Error('Identity denied');const u=await r.json();if(!u.id||u.is_anonymous||!u.email_confirmed_at)throw Error('Verified identity required');return u;}

export function cors(req:Request){const origin=req.headers.get('origin')||'';let allowed;try{allowed=JSON.parse(Deno.env.get('COMMUNICATIONS_ADMIN_ORIGINS_JSON')||'[]');}catch{throw Error('Origin configuration unavailable');}if(!/^https:\/\/[a-z0-9.-]+$/.test(origin)||!Array.isArray(allowed)||!allowed.includes(origin))throw Error('Origin denied');return{'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Headers':'authorization,apikey,content-type,x-client-info','Access-Control-Allow-Methods':'POST,OPTIONS','Vary':'Origin','Cache-Control':'no-store'};}
